### Manipulation of PEAKS de novo results of Trocas 8 (low water, November 2019) non-incubation samples LC-MS/MS data using python.

Starting with:

    PEAKS de novo results (.csv) of PTM-optimized sequencing >50% ALC

Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 675) for another
#### 2. Change output file name in *IN 6*, *IN 7*, *IN 8*

In [1]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [2]:
    cd /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/685_Trocas8_June2021_DENOVO_112/

/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/685_Trocas8_June2021_DENOVO_112

In [3]:
# read the CSVs into a dataframe using the read_csv function and call 'peaks'

peaks685 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/685_Trocas8_June2021_DENOVO_112/685_Trocas8_June2021_DENOVO_112_DN50.csv")

print("# redundant Peaks peptides >50% ALC in combined dataframe:", len(peaks685))

print(peaks685.columns)

# These columns mess things up- get rid of them

del peaks685['Fraction']
del peaks685['Scan']
del peaks685['Source File']
del peaks685['Tag Length']
del peaks685['PTM']
del peaks685['tag (>=0%)']
del peaks685['mode']
del peaks685['local confidence (%)']


columns = ['Peptide', 'ALC', 'length', 'm/z', 'z', 'RT', 'Area',
       'Mass', 'ppm']

peaks685.columns = columns

mean_len = peaks685['length'].mean()
print(mean_len)

# look at the dataframe
peaks685.head()

# redundant Peaks peptides >50% ALC in combined dataframe: 66
Index(['Fraction', 'Scan', 'Source File', 'Peptide', 'Tag Length', 'ALC (%)',
       'length', 'm/z', 'z', 'RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'tag (>=0%)', 'mode'],
      dtype='object')
9.075757575757576

      Peptide  ALC  length       m/z  z     RT        Area       Mass  ppm
0  LSSPATLNSR   98      10  523.2849  2  45.05  10700000.0  1044.5564 -1.1
1  LSSPATLNSR   98      10  523.2853  2  44.55  10700000.0  1044.5564 -0.4
2  LSSPATLNSR   98      10  523.2852  2  44.05  10700000.0  1044.5564 -0.6
3  LSSPATLNSR   95      10  523.2852  2  45.59  10700000.0  1044.5564 -0.5
4    VATVSPLR   95       8  421.7581  2  57.43  15600000.0   841.5021 -0.5

The peptide column has the masses of modifications (e.g., 57.02 Da for carbamidomethylation of cysteine). We want to make new columns with all that information and make a column with only the 'stripped' peptide sequence that's just amino acids - this we can then align against other sequences, for example.

Modified residues were allowed for:

    fixed carbamodimethylation of cysteine 57.021464 C
    varialbe oxidation of methionine: 15.9949 M
    variable deamidation of asparagine, glumatine: 0.984016 NQ

We'll then write this manipulated dataframe to a new file.

In [4]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaks685['A'] = peaks685['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaks685['C'] = peaks685['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaks685['D'] = peaks685['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaks685['E'] = peaks685['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaks685['F'] = peaks685['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaks685['G'] = peaks685['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaks685['H'] = peaks685['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaks685 output, there will be no isoleucines (they're lumped in with leucines)
peaks685['I'] = peaks685['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaks685['K'] = peaks685['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaks685['L'] = peaks685['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaks685['M'] = peaks685['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaks685['N'] = peaks685['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaks685['P'] = peaks685['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaks685['Q'] = peaks685['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaks685['R'] = peaks685['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaks685['S'] = peaks685['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaks685['T'] = peaks685['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaks685['V'] = peaks685['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaks685['W'] = peaks685['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaks685['Y'] = peaks685['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaks685['c-carb'] = peaks685['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaks685['m-oxid'] = peaks685['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaks685['n-deam'] = peaks685['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a count function to enumerate the # of deamidated Q's in each peptide
peaks685['q-deam'] = peaks685['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaks685['stripped_peptide'] = peaks685['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaks685['stripped_length'] = peaks685['stripped_peptide'].apply(len)

# total the number of modifications in sequence
peaks685['ptm-total'] = peaks685['c-carb'] + peaks685['m-oxid'] + peaks685['n-deam'] + peaks685['q-deam']

# calculate NAAF numerator for each peptide k
peaks685['NAAF_num.'] = peaks685['Area'] / peaks685['stripped_length']

# write modified dataframe to new txt file, same name + 'stripped'
peaks685.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/677_CV_50_GF75_DN/685_CV_50_GF75_DN50.csv")

# check out the results
peaks685.head()

,Peptide,ALC,length,m/z,z,RT,Area,Mass,ppm,A,...,W,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,ptm-total,NAAF_num.
0,LSSPATLNSR,98,10,523.2849,2,45.05,10700000.0,1044.5564,-1.1,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,1070000.0
1,LSSPATLNSR,98,10,523.2853,2,44.55,10700000.0,1044.5564,-0.4,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,1070000.0
2,LSSPATLNSR,98,10,523.2852,2,44.05,10700000.0,1044.5564,-0.6,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,1070000.0
3,LSSPATLNSR,95,10,523.2852,2,45.59,10700000.0,1044.5564,-0.5,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,1070000.0
4,VATVSPLR,95,8,421.7581,2,57.43,15600000.0,841.5021,-0.5,1,...,0,0,0,0,0,0,VATVSPLR,8,0,1950000.0

In [5]:
# keep only stripped peptide I/L and NAAF
dn_685 = peaks685[['stripped_peptide', 'Area', 'NAAF_num.']]

dn_685.set_index('stripped_peptide')

# write modified dataframe to new txt file
dn_685.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/I-L_NAAFs/685_CV_50_GF75_DN50_ILnaafs.csv")

dn_685.head()

  stripped_peptide        Area  NAAF_num.
0       LSSPATLNSR  10700000.0  1070000.0
1       LSSPATLNSR  10700000.0  1070000.0
2       LSSPATLNSR  10700000.0  1070000.0
3       LSSPATLNSR  10700000.0  1070000.0
4         VATVSPLR  15600000.0  1950000.0

In [6]:
# made a new dataframe that contains the sums of certain columns 
# in the stripped peptide dataframe above (for >50% ALC)

index = ['sample total']

data = {'A': peaks685['A'].sum(),
        'C': peaks685['C'].sum(),
        'D': peaks685['D'].sum(),
        'E': peaks685['E'].sum(),
        'F': peaks685['F'].sum(),
        'G': peaks685['G'].sum(),
        'H': peaks685['H'].sum(),
        'I': peaks685['I'].sum(),
        'K': peaks685['K'].sum(),
        'L': peaks685['L'].sum(),
        'M': peaks685['M'].sum(),
        'N': peaks685['N'].sum(),
        'P': peaks685['P'].sum(),
        'Q': peaks685['Q'].sum(),
        'R': peaks685['R'].sum(),
        'S': peaks685['S'].sum(),
        'T': peaks685['T'].sum(),
        'V': peaks685['V'].sum(),
        'W': peaks685['W'].sum(),
        'Y': peaks685['Y'].sum(),
        'c-carb': peaks685['c-carb'].sum(),
        'm-oxid': peaks685['m-oxid'].sum(),
        'n-deam': peaks685['n-deam'].sum(),
        'q-deam': peaks685['q-deam'].sum(),
        'Total area': peaks685['Area'].sum(),
        'Total length': peaks685['stripped_length'].sum()
       }

totalpeaks685 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                            'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                            'c-carb', 'm-oxid', 'n-deam', 'q-deam', \
                                            'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaks685['% C w/ carb'] = totalpeaks685['c-carb'] / totalpeaks685['C'] 

# calculate percentage of M's that are oxidized
totalpeaks685['% M w/ oxid'] = totalpeaks685['m-oxid'] / totalpeaks685['M'] 

# calculate percentage of N's that are deamidated
totalpeaks685['% N w/ deam'] = totalpeaks685['n-deam'] / totalpeaks685['N'] 

# calculate percentage of N's that are deamidated
totalpeaks685['% Q w/ deam'] = totalpeaks685['q-deam'] / totalpeaks685['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaks685['NAAF denom.'] = totalpeaks685['Total area'] / totalpeaks685['Total length']

# write modified dataframe to new txt file
totalpeaks685.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/677_CV_50_GF75_DN/685_CV_50_GF75_DN50_totals.csv")

totalpeaks685.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,43,6,14,6,8,16,31,0,33,81,...,7,3,0,191302391.1,586,1.0,0.2,0.130435,0.0,326454.592321

In [7]:
# use the calculated NAAF factor (in totalpeaks dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

# don't have to worry here about DECOY hits messing with Area totals
# but we would with Comet results

NAAF50 = 326454.592321

# use NAAF >50% ALC to get NAAF factor
peaks685['NAAF factor'] = (peaks685['NAAF_num.'])/NAAF50

# make a dataframe that contains only what we need: sequences, AAs, PTMs
peaksAAPTM_685 = peaks685[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'I', 'L', \
                                'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', 'c-carb', 'm-oxid', \
                                'n-deam', 'q-deam']].copy()

# multiply the NAAF50 factor by the AA total to normalize its abundance by peak area and peptide length

peaksAAPTM_685['A-NAAF50'] = peaksAAPTM_685['A'] * peaks685['NAAF factor']
peaksAAPTM_685['C-NAAF50'] = peaksAAPTM_685['C'] * peaks685['NAAF factor']
peaksAAPTM_685['D-NAAF50'] = peaksAAPTM_685['D'] * peaks685['NAAF factor']
peaksAAPTM_685['E-NAAF50'] = peaksAAPTM_685['E'] * peaks685['NAAF factor']
peaksAAPTM_685['F-NAAF50'] = peaksAAPTM_685['F'] * peaks685['NAAF factor']
peaksAAPTM_685['G-NAAF50'] = peaksAAPTM_685['G'] * peaks685['NAAF factor']
peaksAAPTM_685['H-NAAF50'] = peaksAAPTM_685['H'] * peaks685['NAAF factor']
peaksAAPTM_685['I-NAAF50'] = peaksAAPTM_685['I'] * peaks685['NAAF factor']
peaksAAPTM_685['K-NAAF50'] = peaksAAPTM_685['K'] * peaks685['NAAF factor']
peaksAAPTM_685['L-NAAF50'] = peaksAAPTM_685['L'] * peaks685['NAAF factor']
peaksAAPTM_685['M-NAAF50'] = peaksAAPTM_685['M'] * peaks685['NAAF factor']
peaksAAPTM_685['N-NAAF50'] = peaksAAPTM_685['N'] * peaks685['NAAF factor']
peaksAAPTM_685['P-NAAF50'] = peaksAAPTM_685['P'] * peaks685['NAAF factor']
peaksAAPTM_685['Q-NAAF50'] = peaksAAPTM_685['Q'] * peaks685['NAAF factor']
peaksAAPTM_685['R-NAAF50'] = peaksAAPTM_685['R'] * peaks685['NAAF factor']
peaksAAPTM_685['S-NAAF50'] = peaksAAPTM_685['S'] * peaks685['NAAF factor']
peaksAAPTM_685['T-NAAF50'] = peaksAAPTM_685['T'] * peaks685['NAAF factor']
peaksAAPTM_685['V-NAAF50'] = peaksAAPTM_685['V'] * peaks685['NAAF factor']
peaksAAPTM_685['W-NAAF50'] = peaksAAPTM_685['W'] * peaks685['NAAF factor']
peaksAAPTM_685['Y-NAAF50'] = peaksAAPTM_685['Y'] * peaks685['NAAF factor']

# multiply the NAAF50 factor by the PTMs normalize its abundance by peak area and peptide length

peaksAAPTM_685['ccarb-NAAF50'] = peaksAAPTM_685['c-carb'] * peaksAAPTM_685['NAAF factor']
peaksAAPTM_685['moxid-NAAF50'] = peaksAAPTM_685['m-oxid'] * peaksAAPTM_685['NAAF factor']
peaksAAPTM_685['ndeam-NAAF50'] = peaksAAPTM_685['n-deam'] * peaksAAPTM_685['NAAF factor']
peaksAAPTM_685['qdeam-NAAF50'] = peaksAAPTM_685['q-deam'] * peaksAAPTM_685['NAAF factor']


# write the dataframe to a new csv
peaksAAPTM_685.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/677_CV_50_GF75_DN/685_CV_50_GF75_DN50_naaf.csv")

peaksAAPTM_685.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,K,...,R-NAAF50,S-NAAF50,T-NAAF50,V-NAAF50,W-NAAF50,Y-NAAF50,ccarb-NAAF50,moxid-NAAF50,ndeam-NAAF50,qdeam-NAAF50
0,LSSPATLNSR,3.277638,1,0,0,0,0,0,0,0,...,3.277638,9.832914,3.277638,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,LSSPATLNSR,3.277638,1,0,0,0,0,0,0,0,...,3.277638,9.832914,3.277638,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,LSSPATLNSR,3.277638,1,0,0,0,0,0,0,0,...,3.277638,9.832914,3.277638,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,LSSPATLNSR,3.277638,1,0,0,0,0,0,0,0,...,3.277638,9.832914,3.277638,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,VATVSPLR,5.973266,1,0,0,0,0,0,0,0,...,5.973266,5.973266,5.973266,11.946531,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
# made a dataframe that's the sum of NAAF corrected AAs and PTMs

index = ['sample total']

data = {'NAAF': peaksAAPTM_685['NAAF factor'].sum(),
        'A': peaksAAPTM_685['A-NAAF50'].sum(),
        'C': peaksAAPTM_685['C-NAAF50'].sum(),
        'D': peaksAAPTM_685['D-NAAF50'].sum(),
        'E': peaksAAPTM_685['E-NAAF50'].sum(),
        'F': peaksAAPTM_685['F-NAAF50'].sum(),
        'G': peaksAAPTM_685['G-NAAF50'].sum(),
        'H': peaksAAPTM_685['H-NAAF50'].sum(),
        'I': peaksAAPTM_685['I-NAAF50'].sum(),
        'K': peaksAAPTM_685['K-NAAF50'].sum(),
        'L': peaksAAPTM_685['L-NAAF50'].sum(),
        'M': peaksAAPTM_685['M-NAAF50'].sum(),
        'N': peaksAAPTM_685['N-NAAF50'].sum(),
        'P': peaksAAPTM_685['P-NAAF50'].sum(),
        'Q': peaksAAPTM_685['Q-NAAF50'].sum(),
        'R': peaksAAPTM_685['R-NAAF50'].sum(),
        'S': peaksAAPTM_685['S-NAAF50'].sum(),
        'T': peaksAAPTM_685['T-NAAF50'].sum(),
        'V': peaksAAPTM_685['V-NAAF50'].sum(),
        'W': peaksAAPTM_685['W-NAAF50'].sum(),
        'Y': peaksAAPTM_685['Y-NAAF50'].sum(),
        'c-carb': peaksAAPTM_685['ccarb-NAAF50'].sum(),
        'm-oxid': peaksAAPTM_685['moxid-NAAF50'].sum(),
        'n-deam': peaksAAPTM_685['ndeam-NAAF50'].sum(),
        'q-deam': peaksAAPTM_685['qdeam-NAAF50'].sum(),
       }

totalpeaks50_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', \
                                           'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', \
                                           'W', 'Y', 'c-carb', 'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaks50_NAAF['% C w/ carb.'] = totalpeaks50_NAAF['c-carb'] / totalpeaks50_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaks50_NAAF['% M w/ oxid'] = totalpeaks50_NAAF['m-oxid'] / totalpeaks50_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% N w/ deam'] = totalpeaks50_NAAF['n-deam'] / totalpeaks50_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% Q w/ deam'] = totalpeaks50_NAAF['q-deam'] / totalpeaks50_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaks50_NAAF['NAAF check'] = totalpeaks50_NAAF['NAAF'] / 326454.592321

# write modified dataframe to new txt file, same name + totals
totalpeaks50_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/677_CV_50_GF75_DN/685_CV_50_GF75_DN50_naaf_totals.csv")

totalpeaks50_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,70.126156,46.161944,0.354186,0.510884,0.04434,0.044042,3.180963,0.154344,0.0,1.034927,...,0.498869,0.354186,0.48844,0.069001,0.0,1.0,0.37851,0.005139,0.0,0.000215

## Export stripped peptides >50% ALC

In [9]:
##### keep only stripped peptide column 
pep50 = peaks685[["stripped_peptide"]]

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing

pep50.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/677_CV_50_GF75_DN/685_CV_50_GF75_DN50_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/677_CV_50_GF75_DN/685_CV_50_GF75_DN50_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/677_CV_50_GF75_DN/685_CV_50_GF75_DN50_stripped_peptides.fas

# removing redundancy
peaks50dedup = pd.DataFrame.drop_duplicates(pep50)

print("# redundant stripped Peaks peptides >50% ALC", len(pep50))
print("# nonredundant stripped Peaks peptides >50% ALC", len(peaks50dedup))
print("average peptide length Peaks peptides >50% ALC", peaks685['stripped_length'].mean())

# count all unique peptide (modified peptides included)
# keep only peptide column >50% ALC
pep50m = peaks685[["Peptide"]]

# deduplicate
pep50mdedup = pd.DataFrame.drop_duplicates(pep50m)

print("# redundant Peaks peptides >50% ALC", len(pep50m))
print("# nonredundant Peaks peptides", len(pep50mdedup))

# check
pep50.head()

# redundant stripped Peaks peptides >50% ALC 66
# nonredundant stripped Peaks peptides >50% ALC 46
average peptide length Peaks peptides >50% ALC 8.878787878787879
# redundant Peaks peptides >50% ALC 66
# nonredundant Peaks peptides 46

  stripped_peptide
0       LSSPATLNSR
1       LSSPATLNSR
2       LSSPATLNSR
3       LSSPATLNSR
4         VATVSPLR