### Manipulation of PEAKS de novo results of Trocas 7 (high water, April 2019) incubation samples LC-MS/MS data using python.

Starting with:

    PEAKS de novo results (.csv) of PTM-optimized sequencing >50% ALC

Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 101) for another
#### 2. Change output file name in *IN 6*, *IN 7*, *IN 8*

In [3]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [4]:
cd /home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/206_TROCAS7_Fusion_Apr2021_DENOVO_143/

/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/206_TROCAS7_Fusion_Apr2021_DENOVO_143

In [5]:
# read the CSVs into a dataframe using the read_csv function and call 'peaks'

peaks206 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/206_TROCAS7_Fusion_Apr2021_DENOVO_143/206_TROCAS7_Fusion_Apr2021_DENOVO_143_DN50.csv")

print("# redundant Peaks peptides >50% ALC in combined dataframe:", len(peaks206))

print(peaks206.columns)

# These columns mess things up- get rid of them

del peaks206['Fraction']
del peaks206['Scan']
del peaks206['Source File']
del peaks206['Tag Length']
del peaks206['PTM']
del peaks206['tag (>=0%)']
del peaks206['mode']
del peaks206['local confidence (%)']


columns = ['Peptide', 'ALC', 'length', 'm/z', 'z', 'RT', 'Area',
       'Mass', 'ppm']

peaks206.columns = columns

mean_len = peaks206['length'].mean()
print(mean_len)

# look at the dataframe
peaks206.head()

# redundant Peaks peptides >50% ALC in combined dataframe: 283
Index(['Fraction', 'Scan', 'Source File', 'Peptide', 'Tag Length', 'ALC (%)',
       'length', 'm/z', 'z', 'RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'tag (>=0%)', 'mode'],
      dtype='object')
10.325088339222615

         Peptide  ALC  length       m/z  z     RT        Area       Mass  ppm
0       VVEVSLPR   97       8  449.7718  2  67.51   1990000.0   897.5283  0.7
1  VLEGNEQFLNAAK   97      13  716.8757  2  70.69    681000.0  1431.7358  0.7
2     LSSPATLNSR   97      10  523.2859  2  46.32  73100000.0  1044.5564  0.8
3     LSSPATLNSR   97      10  523.2867  2  45.32  73100000.0  1044.5564  2.4
4     LSSPATLNSR   97      10  523.2866  2  45.82  73100000.0  1044.5564  2.2

The peptide column has the masses of modifications (e.g., 57.02 Da for carbamidomethylation of cysteine). We want to make new columns with all that information and make a column with only the 'stripped' peptide sequence that's just amino acids - this we can then align against other sequences, for example.

Modified residues were allowed for:

    fixed carbamodimethylation of cysteine 57.021464 C
    varialbe oxidation of methionine: 15.9949 M
    variable deamidation of asparagine, glumatine: 0.984016 NQ

We'll then write this manipulated dataframe to a new file.

In [7]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaks206['A'] = peaks206['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaks206['C'] = peaks206['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaks206['D'] = peaks206['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaks206['E'] = peaks206['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaks206['F'] = peaks206['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaks206['G'] = peaks206['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaks206['H'] = peaks206['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaks206 output, there will be no isoleucines (they're lumped in with leucines)
peaks206['I'] = peaks206['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaks206['K'] = peaks206['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaks206['L'] = peaks206['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaks206['M'] = peaks206['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaks206['N'] = peaks206['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaks206['P'] = peaks206['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaks206['Q'] = peaks206['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaks206['R'] = peaks206['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaks206['S'] = peaks206['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaks206['T'] = peaks206['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaks206['V'] = peaks206['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaks206['W'] = peaks206['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaks206['Y'] = peaks206['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaks206['c-carb'] = peaks206['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaks206['m-oxid'] = peaks206['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaks206['n-deam'] = peaks206['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a count function to enumerate the # of deamidated Q's in each peptide
peaks206['q-deam'] = peaks206['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaks206['stripped_peptide'] = peaks206['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaks206['stripped_length'] = peaks206['stripped_peptide'].apply(len)

# total the number of modifications in sequence
peaks206['ptm-total'] = peaks206['c-carb'] + peaks206['m-oxid'] + peaks206['n-deam'] + peaks206['q-deam']

# calculate NAAF numerator for each peptide k
peaks206['NAAF_num.'] = peaks206['Area'] / peaks206['stripped_length']

# write modified dataframe to new txt file, same name + 'stripped'
peaks206.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/206_CV_T00_GD_DN/206_CV_T00_GD_DN50.csv")

# check out the results
peaks206.head()

,Peptide,ALC,length,m/z,z,RT,Area,Mass,ppm,A,...,W,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,ptm-total,NAAF_num.
0,VVEVSLPR,97,8,449.7718,2,67.51,1990000.0,897.5283,0.7,0,...,0,0,0,0,0,0,VVEVSLPR,8,0,2.487500e+05
1,VLEGNEQFLNAAK,97,13,716.8757,2,70.69,681000.0,1431.7358,0.7,2,...,0,0,0,0,0,0,VLEGNEQFLNAAK,13,0,5.238462e+04
2,LSSPATLNSR,97,10,523.2859,2,46.32,73100000.0,1044.5564,0.8,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,7.310000e+06
3,LSSPATLNSR,97,10,523.2867,2,45.32,73100000.0,1044.5564,2.4,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,7.310000e+06
4,LSSPATLNSR,97,10,523.2866,2,45.82,73100000.0,1044.5564,2.2,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,7.310000e+06

In [8]:
# keep only stripped peptide I/L and NAAF
dn_206 = peaks206[['stripped_peptide', 'Area', 'NAAF_num.']]

dn_206.set_index('stripped_peptide')

# write modified dataframe to new txt file
dn_206.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/I-L_NAAFs/206_CV_T00_GD_DN50_ILnaafs.csv")

dn_206.head()

  stripped_peptide        Area     NAAF_num.
0         VVEVSLPR   1990000.0  2.487500e+05
1    VLEGNEQFLNAAK    681000.0  5.238462e+04
2       LSSPATLNSR  73100000.0  7.310000e+06
3       LSSPATLNSR  73100000.0  7.310000e+06
4       LSSPATLNSR  73100000.0  7.310000e+06

In [9]:
# made a new dataframe that contains the suMN of certain columns 
# in the stripped peptide dataframe above (for >50% ALC)

index = ['sample total']

data = {'A': peaks206['A'].sum(),
        'C': peaks206['C'].sum(),
        'D': peaks206['D'].sum(),
        'E': peaks206['E'].sum(),
        'F': peaks206['F'].sum(),
        'G': peaks206['G'].sum(),
        'H': peaks206['H'].sum(),
        'I': peaks206['I'].sum(),
        'K': peaks206['K'].sum(),
        'L': peaks206['L'].sum(),
        'M': peaks206['M'].sum(),
        'N': peaks206['N'].sum(),
        'P': peaks206['P'].sum(),
        'Q': peaks206['Q'].sum(),
        'R': peaks206['R'].sum(),
        'S': peaks206['S'].sum(),
        'T': peaks206['T'].sum(),
        'V': peaks206['V'].sum(),
        'W': peaks206['W'].sum(),
        'Y': peaks206['Y'].sum(),
        'c-carb': peaks206['c-carb'].sum(),
        'm-oxid': peaks206['m-oxid'].sum(),
        'n-deam': peaks206['n-deam'].sum(),
        'q-deam': peaks206['q-deam'].sum(),
        'Total area': peaks206['Area'].sum(),
        'Total length': peaks206['stripped_length'].sum()
       }

totalpeaks206 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                            'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                            'c-carb', 'm-oxid', 'n-deam', 'q-deam', \
                                            'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaks206['% C w/ carb'] = totalpeaks206['c-carb'] / totalpeaks206['C'] 

# calculate percentage of M's that are oxidized
totalpeaks206['% M w/ oxid'] = totalpeaks206['m-oxid'] / totalpeaks206['M'] 

# calculate percentage of N's that are deamidated
totalpeaks206['% N w/ deam'] = totalpeaks206['n-deam'] / totalpeaks206['N'] 

# calculate percentage of N's that are deamidated
totalpeaks206['% Q w/ deam'] = totalpeaks206['q-deam'] / totalpeaks206['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaks206['NAAF denom.'] = totalpeaks206['Total area'] / totalpeaks206['Total length']

# write modified dataframe to new txt file
totalpeaks206.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/206_CV_T00_GD_DN/206_CV_T00_GD_DN50_totals.csv")

totalpeaks206.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,157,54,71,75,100,113,218,0,141,372,...,40,26,3,1.777630e+09,2769,1.0,0.216216,0.180556,0.076923,641975.31654

In [10]:
# use the calculated NAAF factor (in totalpeaks dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

# don't have to worry here about DECOY hits messing with Area totals
# but we would with Comet results

NAAF50 = 641975.31654

# use NAAF >50% ALC to get NAAF factor
peaks206['NAAF factor'] = (peaks206['NAAF_num.'])/NAAF50

# make a dataframe that contains only what we need: sequences, AAs, PTMN
peaksAAPTM_206 = peaks206[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'I', 'L', \
                                'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', 'c-carb', 'm-oxid', \
                                'n-deam', 'q-deam']].copy()

# multiply the NAAF50 factor by the AA total to normalize its abundance by peak area and peptide length

peaksAAPTM_206['A-NAAF50'] = peaksAAPTM_206['A'] * peaks206['NAAF factor']
peaksAAPTM_206['C-NAAF50'] = peaksAAPTM_206['C'] * peaks206['NAAF factor']
peaksAAPTM_206['D-NAAF50'] = peaksAAPTM_206['D'] * peaks206['NAAF factor']
peaksAAPTM_206['E-NAAF50'] = peaksAAPTM_206['E'] * peaks206['NAAF factor']
peaksAAPTM_206['F-NAAF50'] = peaksAAPTM_206['F'] * peaks206['NAAF factor']
peaksAAPTM_206['G-NAAF50'] = peaksAAPTM_206['G'] * peaks206['NAAF factor']
peaksAAPTM_206['H-NAAF50'] = peaksAAPTM_206['H'] * peaks206['NAAF factor']
peaksAAPTM_206['I-NAAF50'] = peaksAAPTM_206['I'] * peaks206['NAAF factor']
peaksAAPTM_206['K-NAAF50'] = peaksAAPTM_206['K'] * peaks206['NAAF factor']
peaksAAPTM_206['L-NAAF50'] = peaksAAPTM_206['L'] * peaks206['NAAF factor']
peaksAAPTM_206['M-NAAF50'] = peaksAAPTM_206['M'] * peaks206['NAAF factor']
peaksAAPTM_206['N-NAAF50'] = peaksAAPTM_206['N'] * peaks206['NAAF factor']
peaksAAPTM_206['P-NAAF50'] = peaksAAPTM_206['P'] * peaks206['NAAF factor']
peaksAAPTM_206['Q-NAAF50'] = peaksAAPTM_206['Q'] * peaks206['NAAF factor']
peaksAAPTM_206['R-NAAF50'] = peaksAAPTM_206['R'] * peaks206['NAAF factor']
peaksAAPTM_206['S-NAAF50'] = peaksAAPTM_206['S'] * peaks206['NAAF factor']
peaksAAPTM_206['T-NAAF50'] = peaksAAPTM_206['T'] * peaks206['NAAF factor']
peaksAAPTM_206['V-NAAF50'] = peaksAAPTM_206['V'] * peaks206['NAAF factor']
peaksAAPTM_206['W-NAAF50'] = peaksAAPTM_206['W'] * peaks206['NAAF factor']
peaksAAPTM_206['Y-NAAF50'] = peaksAAPTM_206['Y'] * peaks206['NAAF factor']

# multiply the NAAF50 factor by the PTMN normalize its abundance by peak area and peptide length

peaksAAPTM_206['ccarb-NAAF50'] = peaksAAPTM_206['c-carb'] * peaksAAPTM_206['NAAF factor']
peaksAAPTM_206['moxid-NAAF50'] = peaksAAPTM_206['m-oxid'] * peaksAAPTM_206['NAAF factor']
peaksAAPTM_206['ndeam-NAAF50'] = peaksAAPTM_206['n-deam'] * peaksAAPTM_206['NAAF factor']
peaksAAPTM_206['qdeam-NAAF50'] = peaksAAPTM_206['q-deam'] * peaksAAPTM_206['NAAF factor']


# write the dataframe to a new csv
peaksAAPTM_206.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/206_CV_T00_GD_DN/206_CV_T00_GD_DN50_naaf.csv")

peaksAAPTM_206.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,K,...,R-NAAF50,S-NAAF50,T-NAAF50,V-NAAF50,W-NAAF50,Y-NAAF50,ccarb-NAAF50,moxid-NAAF50,ndeam-NAAF50,qdeam-NAAF50
0,VVEVSLPR,0.387476,0,0,0,1,0,0,0,0,...,0.387476,0.387476,0.000000,1.162428,0.0,0.0,0.0,0.0,0.0,0.0
1,VLEGNEQFLNAAK,0.081599,2,0,0,2,1,1,0,1,...,0.000000,0.000000,0.000000,0.081599,0.0,0.0,0.0,0.0,0.0,0.0
2,LSSPATLNSR,11.386731,1,0,0,0,0,0,0,0,...,11.386731,34.160192,11.386731,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,LSSPATLNSR,11.386731,1,0,0,0,0,0,0,0,...,11.386731,34.160192,11.386731,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,LSSPATLNSR,11.386731,1,0,0,0,0,0,0,0,...,11.386731,34.160192,11.386731,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
# made a dataframe that's the sum of NAAF corrected AAs and PTMN

index = ['sample total']

data = {'NAAF': peaksAAPTM_206['NAAF factor'].sum(),
        'A': peaksAAPTM_206['A-NAAF50'].sum(),
        'C': peaksAAPTM_206['C-NAAF50'].sum(),
        'D': peaksAAPTM_206['D-NAAF50'].sum(),
        'E': peaksAAPTM_206['E-NAAF50'].sum(),
        'F': peaksAAPTM_206['F-NAAF50'].sum(),
        'G': peaksAAPTM_206['G-NAAF50'].sum(),
        'H': peaksAAPTM_206['H-NAAF50'].sum(),
        'I': peaksAAPTM_206['I-NAAF50'].sum(),
        'K': peaksAAPTM_206['K-NAAF50'].sum(),
        'L': peaksAAPTM_206['L-NAAF50'].sum(),
        'M': peaksAAPTM_206['M-NAAF50'].sum(),
        'N': peaksAAPTM_206['N-NAAF50'].sum(),
        'P': peaksAAPTM_206['P-NAAF50'].sum(),
        'Q': peaksAAPTM_206['Q-NAAF50'].sum(),
        'R': peaksAAPTM_206['R-NAAF50'].sum(),
        'S': peaksAAPTM_206['S-NAAF50'].sum(),
        'T': peaksAAPTM_206['T-NAAF50'].sum(),
        'V': peaksAAPTM_206['V-NAAF50'].sum(),
        'W': peaksAAPTM_206['W-NAAF50'].sum(),
        'Y': peaksAAPTM_206['Y-NAAF50'].sum(),
        'c-carb': peaksAAPTM_206['ccarb-NAAF50'].sum(),
        'm-oxid': peaksAAPTM_206['moxid-NAAF50'].sum(),
        'n-deam': peaksAAPTM_206['ndeam-NAAF50'].sum(),
        'q-deam': peaksAAPTM_206['qdeam-NAAF50'].sum(),
       }

totalpeaks50_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', \
                                           'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', \
                                           'W', 'Y', 'c-carb', 'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaks50_NAAF['% C w/ carb.'] = totalpeaks50_NAAF['c-carb'] / totalpeaks50_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaks50_NAAF['% M w/ oxid'] = totalpeaks50_NAAF['m-oxid'] / totalpeaks50_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% N w/ deam'] = totalpeaks50_NAAF['n-deam'] / totalpeaks50_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% Q w/ deam'] = totalpeaks50_NAAF['q-deam'] / totalpeaks50_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaks50_NAAF['NAAF check'] = totalpeaks50_NAAF['NAAF'] / 641975.31654

# write modified dataframe to new txt file, same name + totals
totalpeaks50_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/206_CV_T00_GD_DN/206_CV_T00_GD_DN50_naaf_totals.csv")

totalpeaks50_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,326.860617,228.303107,5.095881,11.165425,9.512789,14.32418,16.053987,22.582918,0.0,11.695919,...,10.401806,5.095881,2.787297,3.232941,0.44415,1.0,0.197893,0.053236,0.112948,0.000509

## Export stripped peptides >50% ALC

In [12]:
##### keep only stripped peptide column 
pep50 = peaks206[["stripped_peptide"]]

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing

pep50.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/206_CV_T00_GD_DN/206_CV_T00_GD_DN50_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/206_CV_T00_GD_DN/206_CV_T00_GD_DN50_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/206_CV_T00_GD_DN/206_CV_T00_GD_DN50_stripped_peptides.fas

# removing redundancy
peaks50dedup = pd.DataFrame.drop_duplicates(pep50)

print("# redundant stripped Peaks peptides >50% ALC", len(pep50))
print("# nonredundant stripped Peaks peptides >50% ALC", len(peaks50dedup))
print("average peptide length Peaks peptides >50% ALC", peaks206['stripped_length'].mean())

# count all unique peptide (modified peptides included)
# keep only peptide column >50% ALC
pep50m = peaks206[["Peptide"]]

# deduplicate
pep50mdedup = pd.DataFrame.drop_duplicates(pep50m)

print("# redundant Peaks peptides >50% ALC", len(pep50m))
print("# nonredundant Peaks peptides", len(pep50mdedup))

# check
pep50.head()

# redundant stripped Peaks peptides >50% ALC 283
# nonredundant stripped Peaks peptides >50% ALC 165
average peptide length Peaks peptides >50% ALC 9.784452296819788
# redundant Peaks peptides >50% ALC 283
# nonredundant Peaks peptides 166

  stripped_peptide
0         VVEVSLPR
1    VLEGNEQFLNAAK
2       LSSPATLNSR
3       LSSPATLNSR
4       LSSPATLNSR