### Manipulation of PEAKS de novo results of Trocas 7 (high water, April 2019) incubation samples LC-MS/MS data using python.

Starting with:

    PEAKS de novo results (.csv) of PTM-optimized sequencing >50% ALC

Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 101) for another
#### 2. Change output file name in *IN 6*, *IN 7*, *IN 8*

In [1]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [2]:
cd /home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/402_TROCAS7_Fusion_Apr2021_DENOVO_130/

/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/402_TROCAS7_Fusion_Apr2021_DENOVO_130

In [3]:
# read the CSVs into a dataframe using the read_csv function and call 'peaks'

peaks402 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/402_TROCAS7_Fusion_Apr2021_DENOVO_130/402_TROCAS7_Fusion_Apr2021_DENOVO_130_DN50.csv")

print("# redundant Peaks peptides >50% ALC in combined dataframe:", len(peaks402))

print(peaks402.columns)

# These columns mess things up- get rid of them

del peaks402['Fraction']
del peaks402['Scan']
del peaks402['Source File']
del peaks402['Tag Length']
del peaks402['PTM']
del peaks402['tag (>=0%)']
del peaks402['mode']
del peaks402['local confidence (%)']


columns = ['Peptide', 'ALC', 'length', 'm/z', 'z', 'RT', 'Area',
       'Mass', 'ppm']

peaks402.columns = columns

mean_len = peaks402['length'].mean()
print(mean_len)

# look at the dataframe
peaks402.head()

# redundant Peaks peptides >50% ALC in combined dataframe: 119
Index(['Fraction', 'Scan', 'Source File', 'Peptide', 'Tag Length', 'ALC (%)',
       'length', 'm/z', 'z', 'RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'tag (>=0%)', 'mode'],
      dtype='object')
10.176470588235293

      Peptide  ALC  length       m/z  z     RT        Area       Mass  ppm
0    SPATLNSR   98       8  423.2275  2  25.88    125000.0   844.4402  0.3
1  LSSPATLNSR   97      10  523.2870  2  47.22  25200000.0  1044.5564  2.9
2  LSSPATLNSR   97      10  523.2858  2  47.73  25200000.0  1044.5564  0.7
3  LSSPATLDSR   97      10  523.7776  2  50.78    495000.0  1045.5403  0.4
4  LSSPATLNSR   96      10  523.2858  2  46.72  25200000.0  1044.5564  0.6

The peptide column has the masses of modifications (e.g., 57.02 Da for carbamidomethylation of cysteine). We want to make new columns with all that information and make a column with only the 'stripped' peptide sequence that's just amino acids - this we can then align against other sequences, for example.

Modified residues were allowed for:

    fixed carbamodimethylation of cysteine 57.021464 C
    varialbe oxidation of methionine: 15.9949 M
    variable deamidation of asparagine, glumatine: 0.984016 NQ

We'll then write this manipulated dataframe to a new file.

In [4]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaks402['A'] = peaks402['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaks402['C'] = peaks402['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaks402['D'] = peaks402['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaks402['E'] = peaks402['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaks402['F'] = peaks402['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaks402['G'] = peaks402['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaks402['H'] = peaks402['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaks402 output, there will be no isoleucines (they're lumped in with leucines)
peaks402['I'] = peaks402['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaks402['K'] = peaks402['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaks402['L'] = peaks402['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaks402['M'] = peaks402['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaks402['N'] = peaks402['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaks402['P'] = peaks402['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaks402['Q'] = peaks402['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaks402['R'] = peaks402['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaks402['S'] = peaks402['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaks402['T'] = peaks402['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaks402['V'] = peaks402['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaks402['W'] = peaks402['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaks402['Y'] = peaks402['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaks402['c-carb'] = peaks402['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaks402['m-oxid'] = peaks402['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaks402['n-deam'] = peaks402['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a count function to enumerate the # of deamidated Q's in each peptide
peaks402['q-deam'] = peaks402['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaks402['stripped_peptide'] = peaks402['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaks402['stripped_length'] = peaks402['stripped_peptide'].apply(len)

# total the number of modifications in sequence
peaks402['ptm-total'] = peaks402['c-carb'] + peaks402['m-oxid'] + peaks402['n-deam'] + peaks402['q-deam']

# calculate NAAF numerator for each peptide k
peaks402['NAAF_num.'] = peaks402['Area'] / peaks402['stripped_length']

# write modified dataframe to new txt file, same name + 'stripped'
peaks402.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/402_BY_T24_GD_DN/402A_BY_T24_GD_DN50.csv")

# check out the results
peaks402.head()

,Peptide,ALC,length,m/z,z,RT,Area,Mass,ppm,A,...,W,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,ptm-total,NAAF_num.
0,SPATLNSR,98,8,423.2275,2,25.88,125000.0,844.4402,0.3,1,...,0,0,0,0,0,0,SPATLNSR,8,0,15625.0
1,LSSPATLNSR,97,10,523.2870,2,47.22,25200000.0,1044.5564,2.9,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,2520000.0
2,LSSPATLNSR,97,10,523.2858,2,47.73,25200000.0,1044.5564,0.7,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,2520000.0
3,LSSPATLDSR,97,10,523.7776,2,50.78,495000.0,1045.5403,0.4,1,...,0,0,0,0,0,0,LSSPATLDSR,10,0,49500.0
4,LSSPATLNSR,96,10,523.2858,2,46.72,25200000.0,1044.5564,0.6,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,2520000.0

In [5]:
# keep only stripped peptide I/L and NAAF
dn_402 = peaks402[['stripped_peptide', 'Area', 'NAAF_num.']]

dn_402.set_index('stripped_peptide')

# write modified dataframe to new txt file
dn_402.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/I-L_NAAFs/402A_BY_T24_GD_DN50_ILnaafs.csv")

dn_402.head()

  stripped_peptide        Area  NAAF_num.
0         SPATLNSR    125000.0    15625.0
1       LSSPATLNSR  25200000.0  2520000.0
2       LSSPATLNSR  25200000.0  2520000.0
3       LSSPATLDSR    495000.0    49500.0
4       LSSPATLNSR  25200000.0  2520000.0

In [6]:
# made a new dataframe that contains the suMN of certain columns 
# in the stripped peptide dataframe above (for >50% ALC)

index = ['sample total']

data = {'A': peaks402['A'].sum(),
        'C': peaks402['C'].sum(),
        'D': peaks402['D'].sum(),
        'E': peaks402['E'].sum(),
        'F': peaks402['F'].sum(),
        'G': peaks402['G'].sum(),
        'H': peaks402['H'].sum(),
        'I': peaks402['I'].sum(),
        'K': peaks402['K'].sum(),
        'L': peaks402['L'].sum(),
        'M': peaks402['M'].sum(),
        'N': peaks402['N'].sum(),
        'P': peaks402['P'].sum(),
        'Q': peaks402['Q'].sum(),
        'R': peaks402['R'].sum(),
        'S': peaks402['S'].sum(),
        'T': peaks402['T'].sum(),
        'V': peaks402['V'].sum(),
        'W': peaks402['W'].sum(),
        'Y': peaks402['Y'].sum(),
        'c-carb': peaks402['c-carb'].sum(),
        'm-oxid': peaks402['m-oxid'].sum(),
        'n-deam': peaks402['n-deam'].sum(),
        'q-deam': peaks402['q-deam'].sum(),
        'Total area': peaks402['Area'].sum(),
        'Total length': peaks402['stripped_length'].sum()
       }

totalpeaks402 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                            'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                            'c-carb', 'm-oxid', 'n-deam', 'q-deam', \
                                            'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaks402['% C w/ carb'] = totalpeaks402['c-carb'] / totalpeaks402['C'] 

# calculate percentage of M's that are oxidized
totalpeaks402['% M w/ oxid'] = totalpeaks402['m-oxid'] / totalpeaks402['M'] 

# calculate percentage of N's that are deamidated
totalpeaks402['% N w/ deam'] = totalpeaks402['n-deam'] / totalpeaks402['N'] 

# calculate percentage of N's that are deamidated
totalpeaks402['% Q w/ deam'] = totalpeaks402['q-deam'] / totalpeaks402['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaks402['NAAF denom.'] = totalpeaks402['Total area'] / totalpeaks402['Total length']

# write modified dataframe to new txt file
totalpeaks402.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/402_BY_T24_GD_DN/402A_BY_T24_GD_DN50_totals.csv")

totalpeaks402.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,65,23,18,50,28,53,85,0,79,156,...,16,1,1,4.494296e+08,1155,1.0,0.207792,0.020408,0.0625,389116.503584

In [8]:
# use the calculated NAAF factor (in totalpeaks dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

# don't have to worry here about DECOY hits messing with Area totals
# but we would with Comet results

NAAF50 = 389116.503584

# use NAAF >50% ALC to get NAAF factor
peaks402['NAAF factor'] = (peaks402['NAAF_num.'])/NAAF50

# make a dataframe that contains only what we need: sequences, AAs, PTMN
peaksAAPTM_402 = peaks402[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'I', 'L', \
                                'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', 'c-carb', 'm-oxid', \
                                'n-deam', 'q-deam']].copy()

# multiply the NAAF50 factor by the AA total to normalize its abundance by peak area and peptide length

peaksAAPTM_402['A-NAAF50'] = peaksAAPTM_402['A'] * peaks402['NAAF factor']
peaksAAPTM_402['C-NAAF50'] = peaksAAPTM_402['C'] * peaks402['NAAF factor']
peaksAAPTM_402['D-NAAF50'] = peaksAAPTM_402['D'] * peaks402['NAAF factor']
peaksAAPTM_402['E-NAAF50'] = peaksAAPTM_402['E'] * peaks402['NAAF factor']
peaksAAPTM_402['F-NAAF50'] = peaksAAPTM_402['F'] * peaks402['NAAF factor']
peaksAAPTM_402['G-NAAF50'] = peaksAAPTM_402['G'] * peaks402['NAAF factor']
peaksAAPTM_402['H-NAAF50'] = peaksAAPTM_402['H'] * peaks402['NAAF factor']
peaksAAPTM_402['I-NAAF50'] = peaksAAPTM_402['I'] * peaks402['NAAF factor']
peaksAAPTM_402['K-NAAF50'] = peaksAAPTM_402['K'] * peaks402['NAAF factor']
peaksAAPTM_402['L-NAAF50'] = peaksAAPTM_402['L'] * peaks402['NAAF factor']
peaksAAPTM_402['M-NAAF50'] = peaksAAPTM_402['M'] * peaks402['NAAF factor']
peaksAAPTM_402['N-NAAF50'] = peaksAAPTM_402['N'] * peaks402['NAAF factor']
peaksAAPTM_402['P-NAAF50'] = peaksAAPTM_402['P'] * peaks402['NAAF factor']
peaksAAPTM_402['Q-NAAF50'] = peaksAAPTM_402['Q'] * peaks402['NAAF factor']
peaksAAPTM_402['R-NAAF50'] = peaksAAPTM_402['R'] * peaks402['NAAF factor']
peaksAAPTM_402['S-NAAF50'] = peaksAAPTM_402['S'] * peaks402['NAAF factor']
peaksAAPTM_402['T-NAAF50'] = peaksAAPTM_402['T'] * peaks402['NAAF factor']
peaksAAPTM_402['V-NAAF50'] = peaksAAPTM_402['V'] * peaks402['NAAF factor']
peaksAAPTM_402['W-NAAF50'] = peaksAAPTM_402['W'] * peaks402['NAAF factor']
peaksAAPTM_402['Y-NAAF50'] = peaksAAPTM_402['Y'] * peaks402['NAAF factor']

# multiply the NAAF50 factor by the PTMN normalize its abundance by peak area and peptide length

peaksAAPTM_402['ccarb-NAAF50'] = peaksAAPTM_402['c-carb'] * peaksAAPTM_402['NAAF factor']
peaksAAPTM_402['moxid-NAAF50'] = peaksAAPTM_402['m-oxid'] * peaksAAPTM_402['NAAF factor']
peaksAAPTM_402['ndeam-NAAF50'] = peaksAAPTM_402['n-deam'] * peaksAAPTM_402['NAAF factor']
peaksAAPTM_402['qdeam-NAAF50'] = peaksAAPTM_402['q-deam'] * peaksAAPTM_402['NAAF factor']


# write the dataframe to a new csv
peaksAAPTM_402.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/402_BY_T24_GD_DN/402A_BY_T24_GD_DN50_naaf.csv")

peaksAAPTM_402.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,K,...,R-NAAF50,S-NAAF50,T-NAAF50,V-NAAF50,W-NAAF50,Y-NAAF50,ccarb-NAAF50,moxid-NAAF50,ndeam-NAAF50,qdeam-NAAF50
0,SPATLNSR,0.040155,1,0,0,0,0,0,0,0,...,0.040155,0.080310,0.040155,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,LSSPATLNSR,6.476210,1,0,0,0,0,0,0,0,...,6.476210,19.428629,6.476210,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,LSSPATLNSR,6.476210,1,0,0,0,0,0,0,0,...,6.476210,19.428629,6.476210,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,LSSPATLDSR,0.127211,1,0,1,0,0,0,0,0,...,0.127211,0.381634,0.127211,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,LSSPATLNSR,6.476210,1,0,0,0,0,0,0,0,...,6.476210,19.428629,6.476210,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
# made a dataframe that's the sum of NAAF corrected AAs and PTMN

index = ['sample total']

data = {'NAAF': peaksAAPTM_402['NAAF factor'].sum(),
        'A': peaksAAPTM_402['A-NAAF50'].sum(),
        'C': peaksAAPTM_402['C-NAAF50'].sum(),
        'D': peaksAAPTM_402['D-NAAF50'].sum(),
        'E': peaksAAPTM_402['E-NAAF50'].sum(),
        'F': peaksAAPTM_402['F-NAAF50'].sum(),
        'G': peaksAAPTM_402['G-NAAF50'].sum(),
        'H': peaksAAPTM_402['H-NAAF50'].sum(),
        'I': peaksAAPTM_402['I-NAAF50'].sum(),
        'K': peaksAAPTM_402['K-NAAF50'].sum(),
        'L': peaksAAPTM_402['L-NAAF50'].sum(),
        'M': peaksAAPTM_402['M-NAAF50'].sum(),
        'N': peaksAAPTM_402['N-NAAF50'].sum(),
        'P': peaksAAPTM_402['P-NAAF50'].sum(),
        'Q': peaksAAPTM_402['Q-NAAF50'].sum(),
        'R': peaksAAPTM_402['R-NAAF50'].sum(),
        'S': peaksAAPTM_402['S-NAAF50'].sum(),
        'T': peaksAAPTM_402['T-NAAF50'].sum(),
        'V': peaksAAPTM_402['V-NAAF50'].sum(),
        'W': peaksAAPTM_402['W-NAAF50'].sum(),
        'Y': peaksAAPTM_402['Y-NAAF50'].sum(),
        'c-carb': peaksAAPTM_402['ccarb-NAAF50'].sum(),
        'm-oxid': peaksAAPTM_402['moxid-NAAF50'].sum(),
        'n-deam': peaksAAPTM_402['ndeam-NAAF50'].sum(),
        'q-deam': peaksAAPTM_402['qdeam-NAAF50'].sum(),
       }

totalpeaks50_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', \
                                           'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', \
                                           'W', 'Y', 'c-carb', 'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaks50_NAAF['% C w/ carb.'] = totalpeaks50_NAAF['c-carb'] / totalpeaks50_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaks50_NAAF['% M w/ oxid'] = totalpeaks50_NAAF['m-oxid'] / totalpeaks50_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% N w/ deam'] = totalpeaks50_NAAF['n-deam'] / totalpeaks50_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% Q w/ deam'] = totalpeaks50_NAAF['q-deam'] / totalpeaks50_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaks50_NAAF['NAAF check'] = totalpeaks50_NAAF['NAAF'] / 389116.503584

# write modified dataframe to new txt file, same name + totals
totalpeaks50_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/402_BY_T24_GD_DN/402A_BY_T24_GD_DN50_naaf_totals.csv")

totalpeaks50_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,140.283242,111.877653,9.56902,4.860215,1.340272,2.700839,8.468189,6.220307,0.0,3.590782,...,3.064258,9.56902,5.05883,0.020933,0.014488,1.0,0.513914,0.000965,0.014311,0.000361

## Export stripped peptides >50% ALC

In [10]:
##### keep only stripped peptide column 
pep50 = peaks402[["stripped_peptide"]]

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing

pep50.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/402_BY_T24_GD_DN/402A_BY_T24_GD_DN50_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/402_BY_T24_GD_DN/402A_BY_T24_GD_DN50_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/402_BY_T24_GD_DN/402A_BY_T24_GD_DN50_stripped_peptides.fas

# removing redundancy
peaks50dedup = pd.DataFrame.drop_duplicates(pep50)

print("# redundant stripped Peaks peptides >50% ALC", len(pep50))
print("# nonredundant stripped Peaks peptides >50% ALC", len(peaks50dedup))
print("average peptide length Peaks peptides >50% ALC", peaks402['stripped_length'].mean())

# count all unique peptide (modified peptides included)
# keep only peptide column >50% ALC
pep50m = peaks402[["Peptide"]]

# deduplicate
pep50mdedup = pd.DataFrame.drop_duplicates(pep50m)

print("# redundant Peaks peptides >50% ALC", len(pep50m))
print("# nonredundant Peaks peptides", len(pep50mdedup))

# check
pep50.head()

# redundant stripped Peaks peptides >50% ALC 119
# nonredundant stripped Peaks peptides >50% ALC 81
average peptide length Peaks peptides >50% ALC 9.705882352941176
# redundant Peaks peptides >50% ALC 119
# nonredundant Peaks peptides 81

  stripped_peptide
0         SPATLNSR
1       LSSPATLNSR
2       LSSPATLNSR
3       LSSPATLDSR
4       LSSPATLNSR