### Manipulation of PEAKS de novo results of Trocas 7 (high water, April 2019) incubation samples LC-MS/MS data using python.

Starting with:

    PEAKS de novo results (.csv) of PTM-optimized sequencing >50% ALC

Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 101) for another
#### 2. Change output file name in *IN 6*, *IN 7*, *IN 8*

In [1]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [2]:
cd /home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/406_TROCAS7_Fusion_Apr2021_DENOVO_132/

/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/406_TROCAS7_Fusion_Apr2021_DENOVO_132

In [3]:
# read the CSVs into a dataframe using the read_csv function and call 'peaks'

peaks406 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/406_TROCAS7_Fusion_Apr2021_DENOVO_132/406_TROCAS7_Fusion_Apr2021_DENOVO_132_DN50.csv")

print("# redundant Peaks peptides >50% ALC in combined dataframe:", len(peaks406))

print(peaks406.columns)

# These columns mess things up- get rid of them

del peaks406['Fraction']
del peaks406['Scan']
del peaks406['Source File']
del peaks406['Tag Length']
del peaks406['PTM']
del peaks406['tag (>=0%)']
del peaks406['mode']
del peaks406['local confidence (%)']


columns = ['Peptide', 'ALC', 'length', 'm/z', 'z', 'RT', 'Area',
       'Mass', 'ppm']

peaks406.columns = columns

mean_len = peaks406['length'].mean()
print(mean_len)

# look at the dataframe
peaks406.head()

# redundant Peaks peptides >50% ALC in combined dataframe: 142
Index(['Fraction', 'Scan', 'Source File', 'Peptide', 'Tag Length', 'ALC (%)',
       'length', 'm/z', 'z', 'RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'tag (>=0%)', 'mode'],
      dtype='object')
9.556338028169014

,Peptide,ALC,length,m/z,z,RT,Area,Mass,ppm
0,EC(+57.02)ELSC(+57.02)K,98,7,463.1911,2,37.47,48500.0,924.3681,-0.4
1,SC(+57.02)ELSC(+57.02)K,97,7,442.1864,2,22.83,61200.0,882.3575,0.7
2,LLTADEK,97,7,395.2213,2,30.43,42300.0,788.4280,0.2
3,SPATLNSR,97,8,423.2277,2,25.85,160000.0,844.4402,0.7
4,LSSPATLNSR,96,10,523.2870,2,47.37,35300000.0,1044.5564,3.0

The peptide column has the masses of modifications (e.g., 57.02 Da for carbamidomethylation of cysteine). We want to make new columns with all that information and make a column with only the 'stripped' peptide sequence that's just amino acids - this we can then align against other sequences, for example.

Modified residues were allowed for:

    fixed carbamodimethylation of cysteine 57.021464 C
    varialbe oxidation of methionine: 15.9949 M
    variable deamidation of asparagine, glumatine: 0.984016 NQ

We'll then write this manipulated dataframe to a new file.

In [4]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaks406['A'] = peaks406['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaks406['C'] = peaks406['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaks406['D'] = peaks406['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaks406['E'] = peaks406['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaks406['F'] = peaks406['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaks406['G'] = peaks406['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaks406['H'] = peaks406['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaks406 output, there will be no isoleucines (they're lumped in with leucines)
peaks406['I'] = peaks406['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaks406['K'] = peaks406['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaks406['L'] = peaks406['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaks406['M'] = peaks406['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaks406['N'] = peaks406['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaks406['P'] = peaks406['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaks406['Q'] = peaks406['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaks406['R'] = peaks406['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaks406['S'] = peaks406['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaks406['T'] = peaks406['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaks406['V'] = peaks406['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaks406['W'] = peaks406['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaks406['Y'] = peaks406['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaks406['c-carb'] = peaks406['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaks406['m-oxid'] = peaks406['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaks406['n-deam'] = peaks406['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a count function to enumerate the # of deamidated Q's in each peptide
peaks406['q-deam'] = peaks406['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaks406['stripped_peptide'] = peaks406['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaks406['stripped_length'] = peaks406['stripped_peptide'].apply(len)

# total the number of modifications in sequence
peaks406['ptm-total'] = peaks406['c-carb'] + peaks406['m-oxid'] + peaks406['n-deam'] + peaks406['q-deam']

# calculate NAAF numerator for each peptide k
peaks406['NAAF_num.'] = peaks406['Area'] / peaks406['stripped_length']

# write modified dataframe to new txt file, same name + 'stripped'
peaks406.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/406_CV_T24_GD_DN/406A_CV_T24_GD_DN50.csv")

# check out the results
peaks406.head()

,Peptide,ALC,length,m/z,z,RT,Area,Mass,ppm,A,...,W,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,ptm-total,NAAF_num.
0,EC(+57.02)ELSC(+57.02)K,98,7,463.1911,2,37.47,48500.0,924.3681,-0.4,0,...,0,0,2,0,0,0,ECK,3,2,1.616667e+04
1,SC(+57.02)ELSC(+57.02)K,97,7,442.1864,2,22.83,61200.0,882.3575,0.7,0,...,0,0,2,0,0,0,SCK,3,2,2.040000e+04
2,LLTADEK,97,7,395.2213,2,30.43,42300.0,788.4280,0.2,1,...,0,0,0,0,0,0,LLTADEK,7,0,6.042857e+03
3,SPATLNSR,97,8,423.2277,2,25.85,160000.0,844.4402,0.7,1,...,0,0,0,0,0,0,SPATLNSR,8,0,2.000000e+04
4,LSSPATLNSR,96,10,523.2870,2,47.37,35300000.0,1044.5564,3.0,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,3.530000e+06

In [5]:
# keep only stripped peptide I/L and NAAF
dn_406 = peaks406[['stripped_peptide', 'Area', 'NAAF_num.']]

dn_406.set_index('stripped_peptide')

# write modified dataframe to new txt file
dn_406.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/I-L_NAAFs/406A_CV_T24_GD_DN50_ILnaafs.csv")

dn_406.head()

  stripped_peptide        Area     NAAF_num.
0              ECK     48500.0  1.616667e+04
1              SCK     61200.0  2.040000e+04
2          LLTADEK     42300.0  6.042857e+03
3         SPATLNSR    160000.0  2.000000e+04
4       LSSPATLNSR  35300000.0  3.530000e+06

In [6]:
# made a new dataframe that contains the suMN of certain columns 
# in the stripped peptide dataframe above (for >50% ALC)

index = ['sample total']

data = {'A': peaks406['A'].sum(),
        'C': peaks406['C'].sum(),
        'D': peaks406['D'].sum(),
        'E': peaks406['E'].sum(),
        'F': peaks406['F'].sum(),
        'G': peaks406['G'].sum(),
        'H': peaks406['H'].sum(),
        'I': peaks406['I'].sum(),
        'K': peaks406['K'].sum(),
        'L': peaks406['L'].sum(),
        'M': peaks406['M'].sum(),
        'N': peaks406['N'].sum(),
        'P': peaks406['P'].sum(),
        'Q': peaks406['Q'].sum(),
        'R': peaks406['R'].sum(),
        'S': peaks406['S'].sum(),
        'T': peaks406['T'].sum(),
        'V': peaks406['V'].sum(),
        'W': peaks406['W'].sum(),
        'Y': peaks406['Y'].sum(),
        'c-carb': peaks406['c-carb'].sum(),
        'm-oxid': peaks406['m-oxid'].sum(),
        'n-deam': peaks406['n-deam'].sum(),
        'q-deam': peaks406['q-deam'].sum(),
        'Total area': peaks406['Area'].sum(),
        'Total length': peaks406['stripped_length'].sum()
       }

totalpeaks406 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                            'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                            'c-carb', 'm-oxid', 'n-deam', 'q-deam', \
                                            'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaks406['% C w/ carb'] = totalpeaks406['c-carb'] / totalpeaks406['C'] 

# calculate percentage of M's that are oxidized
totalpeaks406['% M w/ oxid'] = totalpeaks406['m-oxid'] / totalpeaks406['M'] 

# calculate percentage of N's that are deamidated
totalpeaks406['% N w/ deam'] = totalpeaks406['n-deam'] / totalpeaks406['N'] 

# calculate percentage of N's that are deamidated
totalpeaks406['% Q w/ deam'] = totalpeaks406['q-deam'] / totalpeaks406['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaks406['NAAF denom.'] = totalpeaks406['Total area'] / totalpeaks406['Total length']

# write modified dataframe to new txt file
totalpeaks406.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/406_CV_T24_GD_DN/406A_CV_T24_GD_DN50_totals.csv")

totalpeaks406.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,75,34,33,56,40,54,75,0,79,181,...,28,11,1,589803599.0,1245,1.0,0.325581,0.174603,0.052632,473737.830522

In [7]:
# use the calculated NAAF factor (in totalpeaks dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

# don't have to worry here about DECOY hits messing with Area totals
# but we would with Comet results

NAAF50 = 473737.830522

# use NAAF >50% ALC to get NAAF factor
peaks406['NAAF factor'] = (peaks406['NAAF_num.'])/NAAF50

# make a dataframe that contains only what we need: sequences, AAs, PTMN
peaksAAPTM_406 = peaks406[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'I', 'L', \
                                'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', 'c-carb', 'm-oxid', \
                                'n-deam', 'q-deam']].copy()

# multiply the NAAF50 factor by the AA total to normalize its abundance by peak area and peptide length

peaksAAPTM_406['A-NAAF50'] = peaksAAPTM_406['A'] * peaks406['NAAF factor']
peaksAAPTM_406['C-NAAF50'] = peaksAAPTM_406['C'] * peaks406['NAAF factor']
peaksAAPTM_406['D-NAAF50'] = peaksAAPTM_406['D'] * peaks406['NAAF factor']
peaksAAPTM_406['E-NAAF50'] = peaksAAPTM_406['E'] * peaks406['NAAF factor']
peaksAAPTM_406['F-NAAF50'] = peaksAAPTM_406['F'] * peaks406['NAAF factor']
peaksAAPTM_406['G-NAAF50'] = peaksAAPTM_406['G'] * peaks406['NAAF factor']
peaksAAPTM_406['H-NAAF50'] = peaksAAPTM_406['H'] * peaks406['NAAF factor']
peaksAAPTM_406['I-NAAF50'] = peaksAAPTM_406['I'] * peaks406['NAAF factor']
peaksAAPTM_406['K-NAAF50'] = peaksAAPTM_406['K'] * peaks406['NAAF factor']
peaksAAPTM_406['L-NAAF50'] = peaksAAPTM_406['L'] * peaks406['NAAF factor']
peaksAAPTM_406['M-NAAF50'] = peaksAAPTM_406['M'] * peaks406['NAAF factor']
peaksAAPTM_406['N-NAAF50'] = peaksAAPTM_406['N'] * peaks406['NAAF factor']
peaksAAPTM_406['P-NAAF50'] = peaksAAPTM_406['P'] * peaks406['NAAF factor']
peaksAAPTM_406['Q-NAAF50'] = peaksAAPTM_406['Q'] * peaks406['NAAF factor']
peaksAAPTM_406['R-NAAF50'] = peaksAAPTM_406['R'] * peaks406['NAAF factor']
peaksAAPTM_406['S-NAAF50'] = peaksAAPTM_406['S'] * peaks406['NAAF factor']
peaksAAPTM_406['T-NAAF50'] = peaksAAPTM_406['T'] * peaks406['NAAF factor']
peaksAAPTM_406['V-NAAF50'] = peaksAAPTM_406['V'] * peaks406['NAAF factor']
peaksAAPTM_406['W-NAAF50'] = peaksAAPTM_406['W'] * peaks406['NAAF factor']
peaksAAPTM_406['Y-NAAF50'] = peaksAAPTM_406['Y'] * peaks406['NAAF factor']

# multiply the NAAF50 factor by the PTMN normalize its abundance by peak area and peptide length

peaksAAPTM_406['ccarb-NAAF50'] = peaksAAPTM_406['c-carb'] * peaksAAPTM_406['NAAF factor']
peaksAAPTM_406['moxid-NAAF50'] = peaksAAPTM_406['m-oxid'] * peaksAAPTM_406['NAAF factor']
peaksAAPTM_406['ndeam-NAAF50'] = peaksAAPTM_406['n-deam'] * peaksAAPTM_406['NAAF factor']
peaksAAPTM_406['qdeam-NAAF50'] = peaksAAPTM_406['q-deam'] * peaksAAPTM_406['NAAF factor']


# write the dataframe to a new csv
peaksAAPTM_406.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/406_CV_T24_GD_DN/406A_CV_T24_GD_DN50_naaf.csv")

peaksAAPTM_406.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,K,...,R-NAAF50,S-NAAF50,T-NAAF50,V-NAAF50,W-NAAF50,Y-NAAF50,ccarb-NAAF50,moxid-NAAF50,ndeam-NAAF50,qdeam-NAAF50
0,ECK,0.034126,0,2,0,2,0,0,0,1,...,0.000000,0.034126,0.000000,0.0,0.0,0.0,0.068252,0.0,0.0,0.0
1,SCK,0.043062,0,2,0,1,0,0,0,1,...,0.000000,0.086124,0.000000,0.0,0.0,0.0,0.086124,0.0,0.0,0.0
2,LLTADEK,0.012756,1,0,1,1,0,0,0,1,...,0.000000,0.000000,0.012756,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,SPATLNSR,0.042217,1,0,0,0,0,0,0,0,...,0.042217,0.084435,0.042217,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,LSSPATLNSR,7.451379,1,0,0,0,0,0,0,0,...,7.451379,22.354136,7.451379,0.0,0.0,0.0,0.000000,0.0,0.0,0.0

In [8]:
# made a dataframe that's the sum of NAAF corrected AAs and PTMN

index = ['sample total']

data = {'NAAF': peaksAAPTM_406['NAAF factor'].sum(),
        'A': peaksAAPTM_406['A-NAAF50'].sum(),
        'C': peaksAAPTM_406['C-NAAF50'].sum(),
        'D': peaksAAPTM_406['D-NAAF50'].sum(),
        'E': peaksAAPTM_406['E-NAAF50'].sum(),
        'F': peaksAAPTM_406['F-NAAF50'].sum(),
        'G': peaksAAPTM_406['G-NAAF50'].sum(),
        'H': peaksAAPTM_406['H-NAAF50'].sum(),
        'I': peaksAAPTM_406['I-NAAF50'].sum(),
        'K': peaksAAPTM_406['K-NAAF50'].sum(),
        'L': peaksAAPTM_406['L-NAAF50'].sum(),
        'M': peaksAAPTM_406['M-NAAF50'].sum(),
        'N': peaksAAPTM_406['N-NAAF50'].sum(),
        'P': peaksAAPTM_406['P-NAAF50'].sum(),
        'Q': peaksAAPTM_406['Q-NAAF50'].sum(),
        'R': peaksAAPTM_406['R-NAAF50'].sum(),
        'S': peaksAAPTM_406['S-NAAF50'].sum(),
        'T': peaksAAPTM_406['T-NAAF50'].sum(),
        'V': peaksAAPTM_406['V-NAAF50'].sum(),
        'W': peaksAAPTM_406['W-NAAF50'].sum(),
        'Y': peaksAAPTM_406['Y-NAAF50'].sum(),
        'c-carb': peaksAAPTM_406['ccarb-NAAF50'].sum(),
        'm-oxid': peaksAAPTM_406['moxid-NAAF50'].sum(),
        'n-deam': peaksAAPTM_406['ndeam-NAAF50'].sum(),
        'q-deam': peaksAAPTM_406['qdeam-NAAF50'].sum(),
       }

totalpeaks50_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', \
                                           'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', \
                                           'W', 'Y', 'c-carb', 'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaks50_NAAF['% C w/ carb.'] = totalpeaks50_NAAF['c-carb'] / totalpeaks50_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaks50_NAAF['% M w/ oxid'] = totalpeaks50_NAAF['m-oxid'] / totalpeaks50_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% N w/ deam'] = totalpeaks50_NAAF['n-deam'] / totalpeaks50_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% Q w/ deam'] = totalpeaks50_NAAF['q-deam'] / totalpeaks50_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaks50_NAAF['NAAF check'] = totalpeaks50_NAAF['NAAF'] / 473737.830522

# write modified dataframe to new txt file, same name + totals
totalpeaks50_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/406_CV_T24_GD_DN/406A_CV_T24_GD_DN50_naaf_totals.csv")

totalpeaks50_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,151.348159,117.425026,4.19775,2.447502,1.419529,2.679228,5.383755,4.640279,0.0,2.911185,...,3.183292,4.19775,1.805503,0.430581,0.064593,1.0,0.317814,0.024177,0.068144,0.000319

## Export stripped peptides >50% ALC

In [9]:
##### keep only stripped peptide column 
pep50 = peaks406[["stripped_peptide"]]

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing

pep50.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/406_CV_T24_GD_DN/406A_CV_T24_GD_DN50_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/406_CV_T24_GD_DN/406A_CV_T24_GD_DN50_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDN/406_CV_T24_GD_DN/406A_CV_T24_GD_DN50_stripped_peptides.fas

# removing redundancy
peaks50dedup = pd.DataFrame.drop_duplicates(pep50)

print("# redundant stripped Peaks peptides >50% ALC", len(pep50))
print("# nonredundant stripped Peaks peptides >50% ALC", len(peaks50dedup))
print("average peptide length Peaks peptides >50% ALC", peaks406['stripped_length'].mean())

# count all unique peptide (modified peptides included)
# keep only peptide column >50% ALC
pep50m = peaks406[["Peptide"]]

# deduplicate
pep50mdedup = pd.DataFrame.drop_duplicates(pep50m)

print("# redundant Peaks peptides >50% ALC", len(pep50m))
print("# nonredundant Peaks peptides", len(pep50mdedup))

# check
pep50.head()

# redundant stripped Peaks peptides >50% ALC 142
# nonredundant stripped Peaks peptides >50% ALC 99
average peptide length Peaks peptides >50% ALC 8.767605633802816
# redundant Peaks peptides >50% ALC 142
# nonredundant Peaks peptides 102

  stripped_peptide
0              ECK
1              SCK
2          LLTADEK
3         SPATLNSR
4       LSSPATLNSR