### Manipulation of PeaskDB de novo-assisted database search results of Trocas 7 (high water, April 2019) incubation samples LC-MS/MS data using python.

Starting with:

    PeaksDB search results (.csv) of PTM-optimized database searches
    These were all searched with 15 ppm precursor tolerance and 0.5 ppm fragement ion tolerance
    Exported at <1.0% FDR
    
Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use for a different file:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 101) for another
#### 3. Update the NAAF factor calculated in *IN 6* into *IN 7*

In [1]:
cd /home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/417_TROCAS7_Fusion_Apr2021_PEAKS_180/

/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/417_TROCAS7_Fusion_Apr2021_PEAKS_180

In [2]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [3]:
ls

 417_TROCAS7_Fusion_Apr2021_PEAKS_180_peptide.csv
 417_TROCAS7_Fusion_Apr2021_PEAKS_180_protein.csv
 417_TROCAS7_Fusion_Apr2021_PEAKS_180_protein.fasta
'DB search psm.csv'
'de novo only peptides.csv'
 peptides.pep.xml
 protein-peptides.csv

In [5]:
# read the CSV into a dataframe using the pandas read_csv function
peaksdbdup417 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/T7-INC-UWPR_Apr2021_Fus_T00T24/DN50_10lgP15/417_TROCAS7_Fusion_Apr2021_PEAKS_180/417_TROCAS7_Fusion_Apr2021_PEAKS_180_peptide.csv")

# remove redundant rows
peaksdb417 = pd.DataFrame.drop_duplicates(peaksdbdup417)

print(peaksdb417.columns)

columns = ['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area', 'Fraction', 'Scan', 'Source_File',
       '#Spec', '#Spec', 'Accession', 'PTM',
       'AScore']

peaksdb417.columns = columns

#remmove # spec and accession columns because they mess parsing up

del peaksdb417['#Spec']
del peaksdb417['Accession']
del peaksdb417['PTM']
del peaksdb417['AScore']

mean_length = peaksdb417['Length'].mean()
print(mean_length)

print("# redundant peaksdb peptides in combined dataframe", len(peaksdbdup417))
print("# nonredundant peaksdb peptides in combined dataframe", len(peaksdb417))

#look at the dataframe
peaksdb417.head()

Index(['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area Trocas7-417-NMCP-DUP', 'Fraction', 'Scan', 'Source File', '#Spec',
       '#Spec Trocas7-417-NMCP-DUP', 'Accession', 'PTM', 'AScore'],
      dtype='object')
10.015151515151516
# redundant peaksdb peptides in combined dataframe 132
# nonredundant peaksdb peptides in combined dataframe 132

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,Source_File
0,SC(+57.02)AAAGTEC(+57.02)LISGWGNTK,65.83,1881.8350,18,2.1,941.9267,94.60,570000.0,110,17692,20210411_Trocas7_657_NMCP417_DDA_120min_2.raw
1,TN(+.98)AEN(+.98)EFVTIKK,57.70,1394.6929,12,2.0,465.9058,73.93,105000.0,110,14007,20210411_Trocas7_657_NMCP417_DDA_120min_2.raw
2,VLEGNEQFINAAK,56.72,1431.7357,13,2.4,716.8768,75.43,4060000.0,110,14286,20210411_Trocas7_657_NMCP417_DDA_120min_2.raw
3,LEGNEQFINAAK,48.60,1332.6674,12,2.5,667.3426,69.70,116000.0,110,13229,20210411_Trocas7_657_NMCP417_DDA_120min_2.raw
4,ALEESNYELEGK,47.66,1380.6409,12,1.6,691.3288,64.22,271000.0,110,12156,20210411_Trocas7_657_NMCP417_DDA_120min_2.raw

In [6]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaksdb417['A'] = peaksdb417['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaksdb417['C'] = peaksdb417['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaksdb417['D'] = peaksdb417['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaksdb417['E'] = peaksdb417['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaksdb417['F'] = peaksdb417['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaksdb417['G'] = peaksdb417['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaksdb417['H'] = peaksdb417['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaksdb417 output, there will be no isoleucines (they're lumped in with leucines)
peaksdb417['I'] = peaksdb417['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaksdb417['K'] = peaksdb417['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaksdb417['L'] = peaksdb417['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaksdb417['M'] = peaksdb417['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaksdb417['N'] = peaksdb417['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaksdb417['P'] = peaksdb417['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaksdb417['Q'] = peaksdb417['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaksdb417['R'] = peaksdb417['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaksdb417['S'] = peaksdb417['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaksdb417['T'] = peaksdb417['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaksdb417['V'] = peaksdb417['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaksdb417['W'] = peaksdb417['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaksdb417['Y'] = peaksdb417['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaksdb417['c-carb'] = peaksdb417['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaksdb417['m-oxid'] = peaksdb417['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaksdb417['n-deam'] = peaksdb417['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a lamba function to enumerate the # of deamidated Q's in each peptide
peaksdb417['q-deam'] = peaksdb417['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaksdb417['stripped_peptide'] = peaksdb417['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaksdb417['stripped_length'] = peaksdb417['stripped_peptide'].apply(len)

peaksdb417['NAAF_num.'] = peaksdb417['Area'] / peaksdb417['stripped_length']

# total the number of modifications in sequence
peaksdb417['ptm-total'] = peaksdb417['c-carb'] + peaksdb417['m-oxid'] + peaksdb417['n-deam'] + peaksdb417['q-deam']

# turn all isoleucines into leucines
# this helps later in comparing Unipept peptides to PeaksDB and Comet ones
peaksdb417['stripped_IL']= peaksdb417['stripped_peptide'].str.replace('I','L')

# write modified dataframe to new txt file
peaksdb417.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDB/417_MN_T24_GD_PDB/417B_MN_T24_GD_PDB.csv")

# check out the results
peaksdb417.head()

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,...,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,NAAF_num.,ptm-total,stripped_IL
0,SC(+57.02)AAAGTEC(+57.02)LISGWGNTK,65.83,1881.8350,18,2.1,941.9267,94.60,570000.0,110,17692,...,0,2,0,0,0,SCLISGWGNTK,11,51818.181818,2,SCLLSGWGNTK
1,TN(+.98)AEN(+.98)EFVTIKK,57.70,1394.6929,12,2.0,465.9058,73.93,105000.0,110,14007,...,0,0,0,2,0,TNEFVTIKK,9,11666.666667,2,TNEFVTLKK
2,VLEGNEQFINAAK,56.72,1431.7357,13,2.4,716.8768,75.43,4060000.0,110,14286,...,0,0,0,0,0,VLEGNEQFINAAK,13,312307.692308,0,VLEGNEQFLNAAK
3,LEGNEQFINAAK,48.60,1332.6674,12,2.5,667.3426,69.70,116000.0,110,13229,...,0,0,0,0,0,LEGNEQFINAAK,12,9666.666667,0,LEGNEQFLNAAK
4,ALEESNYELEGK,47.66,1380.6409,12,1.6,691.3288,64.22,271000.0,110,12156,...,1,0,0,0,0,ALEESNYELEGK,12,22583.333333,0,ALEESNYELEGK

In [7]:
# keep only stripped peptide I/L and NAAF
db_417 = peaksdb417[['stripped_IL', 'Area', 'NAAF_num.']]

db_417.set_index('stripped_IL')

# write modified dataframe to new txt file
db_417.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/I-L_NAAFs/417B_MN_T24_GD_PDB_ILnaafs.csv")

db_417.head()

     stripped_IL       Area      NAAF_num.
0    SCLLSGWGNTK   570000.0   51818.181818
1      TNEFVTLKK   105000.0   11666.666667
2  VLEGNEQFLNAAK  4060000.0  312307.692308
3   LEGNEQFLNAAK   116000.0    9666.666667
4   ALEESNYELEGK   271000.0   22583.333333

### Exporting txt files of stripped peptides at confidence cutoffs:

In [8]:
# keep only peptide column peptides <1% FDR (this is what we exported)
pep417moddup = peaksdb417[["Peptide"]]

# keep only the stripped peptide column <1% FDR
# this is what we'll use for UniPept input, etc
pep417dup = peaksdb417[["stripped_peptide"]]

# deduplicate both of these lists
pep417mod = pep417moddup.drop_duplicates()
pep417 = pep417dup.drop_duplicates()

# print out the #s of modified and stripped peptides, deduplicated and not

print("Total modified PeaksDB peptides in 417:", len(pep417moddup))
print("Deduplicated modified PeaksDB peptides in 417:", len(pep417mod))
print("Total stripped PeaksDB peptides in 417:", len(pep417dup))
print("Deduplicated stripped PeaksDB peptides in 417:", len(pep417))

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing
pep417.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDB/417_MN_T24_GD_PDB/417B_MN_T24_GD_PDB_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDB/417_MN_T24_GD_PDB/417B_MN_T24_GD_PDB_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDB/417_MN_T24_GD_PDB/417B_MN_T24_GD_PDB_stripped_peptides.fas

# look at the stripped peptides
pep417.head()

Total modified PeaksDB peptides in 417: 132
Deduplicated modified PeaksDB peptides in 417: 132
Total stripped PeaksDB peptides in 417: 132
Deduplicated stripped PeaksDB peptides in 417: 123

  stripped_peptide
0      SCLISGWGNTK
1        TNEFVTIKK
2    VLEGNEQFINAAK
3     LEGNEQFINAAK
4     ALEESNYELEGK

## NAAF correction and exporting files with AA and PTM totals:

In [9]:
# made a new dataframe that contains the suMN of certain columns in the modified
# peptide dataframe above 

index = ['sample total']

data = {'A': peaksdb417['A'].sum(),
        'C': peaksdb417['C'].sum(),
        'D': peaksdb417['D'].sum(),
        'E': peaksdb417['E'].sum(),
        'F': peaksdb417['F'].sum(),
        'G': peaksdb417['G'].sum(),
        'H': peaksdb417['H'].sum(),
        'I': peaksdb417['I'].sum(),
        'K': peaksdb417['K'].sum(),
        'L': peaksdb417['L'].sum(),
        'M': peaksdb417['M'].sum(),
        'N': peaksdb417['N'].sum(),
        'P': peaksdb417['P'].sum(),
        'Q': peaksdb417['Q'].sum(),
        'R': peaksdb417['R'].sum(),
        'S': peaksdb417['S'].sum(),
        'T': peaksdb417['T'].sum(),
        'V': peaksdb417['V'].sum(),
        'W': peaksdb417['W'].sum(),
        'Y': peaksdb417['Y'].sum(),
        'c-carb': peaksdb417['c-carb'].sum(),
        'm-oxid': peaksdb417['m-oxid'].sum(),
        'n-deam': peaksdb417['n-deam'].sum(),
        'q-deam': peaksdb417['q-deam'].sum(),
        'Total area': peaksdb417['Area'].sum(),
        'Total length': peaksdb417['stripped_length'].sum()
       }

totalpeaksdb417 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                              'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                              'c-carb', 'm-oxid', 
                                              'n-deam', 'q-deam', 'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaksdb417['% C w/ carb'] = totalpeaksdb417['c-carb'] / totalpeaksdb417['C'] 

# calculate percentage of M's that are oxidized
totalpeaksdb417['% M w/ oxid'] = totalpeaksdb417['m-oxid'] / totalpeaksdb417['M'] 

# calculate percentage of N's that are deamidated
totalpeaksdb417['% N w/ deam'] = totalpeaksdb417['n-deam'] / totalpeaksdb417['N'] 

# calculate percentage of N's that are deamidated
totalpeaksdb417['% Q w/ deam'] = totalpeaksdb417['q-deam'] / totalpeaksdb417['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaksdb417['NAAF denom.'] = totalpeaksdb417['Total area'] / totalpeaksdb417['Total length']

# write modified dataframe to new txt file
totalpeaksdb417.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDB/417_MN_T24_GD_PDB/417B_MN_T24_GD_PDB_totals.csv")

totalpeaksdb417.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,115,26,70,73,40,88,24,85,72,148,...,12,21,11,640365234.0,1251,1.0,0.5,0.177966,0.268293,511882.681055

In [10]:
# use the calculated NAAF factor (in totalpeaksdb417 dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

NAAF20 = 511882.681055

# we'll use -10lgP > 20 as an approximate cutoff for the <1.0% FDR which is what we actually have
peaksdb417['NAAF factor'] = (peaksdb417['NAAF_num.'])/NAAF20

# make a dataframe that contains only what we need: sequences, AAs, PTMN
peaksdb417_NAAF = peaksdb417[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', \
                              'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                              'c-carb', 'm-oxid', 'n-deam', 'q-deam']].copy()

# multiply the NAAF20 factor by the AAs to normalize its abundance by peak area and peptide length

peaksdb417_NAAF['A-NAAF20'] = peaksdb417_NAAF['A'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['C-NAAF20'] = peaksdb417_NAAF['C'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['D-NAAF20'] = peaksdb417_NAAF['D'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['E-NAAF20'] = peaksdb417_NAAF['E'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['F-NAAF20'] = peaksdb417_NAAF['F'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['G-NAAF20'] = peaksdb417_NAAF['G'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['H-NAAF20'] = peaksdb417_NAAF['H'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['I-NAAF20'] = peaksdb417_NAAF['I'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['K-NAAF20'] = peaksdb417_NAAF['K'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['L-NAAF20'] = peaksdb417_NAAF['L'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['M-NAAF20'] = peaksdb417_NAAF['M'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['N-NAAF20'] = peaksdb417_NAAF['N'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['P-NAAF20'] = peaksdb417_NAAF['P'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['Q-NAAF20'] = peaksdb417_NAAF['Q'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['R-NAAF20'] = peaksdb417_NAAF['R'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['S-NAAF20'] = peaksdb417_NAAF['S'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['T-NAAF20'] = peaksdb417_NAAF['T'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['V-NAAF20'] = peaksdb417_NAAF['V'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['W-NAAF20'] = peaksdb417_NAAF['W'] * peaksdb417['NAAF factor']
peaksdb417_NAAF['Y-NAAF20'] = peaksdb417_NAAF['Y'] * peaksdb417['NAAF factor']

# multiply the NAAF20 factor by the PTMN normalize its abundance by peak area and peptide length

peaksdb417_NAAF['ccarb-NAAF20'] = peaksdb417_NAAF['c-carb'] * peaksdb417_NAAF['NAAF factor']
peaksdb417_NAAF['moxid-NAAF20'] = peaksdb417_NAAF['m-oxid'] * peaksdb417_NAAF['NAAF factor']
peaksdb417_NAAF['ndeam-NAAF20'] = peaksdb417_NAAF['n-deam'] * peaksdb417_NAAF['NAAF factor']
peaksdb417_NAAF['qdeam-NAAF20'] = peaksdb417_NAAF['q-deam'] * peaksdb417_NAAF['NAAF factor']


# write the dataframe to a new csv
peaksdb417_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDB/417_MN_T24_GD_PDB/417B_MN_T24_GD_PDB_naaf.csv")

peaksdb417_NAAF.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,I,...,R-NAAF20,S-NAAF20,T-NAAF20,V-NAAF20,W-NAAF20,Y-NAAF20,ccarb-NAAF20,moxid-NAAF20,ndeam-NAAF20,qdeam-NAAF20
0,SCLISGWGNTK,0.101231,3,2,0,1,0,3,0,1,...,0.0,0.202461,0.202461,0.000000,0.101231,0.000000,0.202461,0.0,0.000000,0.0
1,TNEFVTIKK,0.022792,1,0,0,2,1,0,0,1,...,0.0,0.000000,0.045583,0.022792,0.000000,0.000000,0.000000,0.0,0.045583,0.0
2,VLEGNEQFINAAK,0.610116,2,0,0,2,1,1,0,1,...,0.0,0.000000,0.000000,0.610116,0.000000,0.000000,0.000000,0.0,0.000000,0.0
3,LEGNEQFINAAK,0.018885,2,0,0,2,1,1,0,1,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0
4,ALEESNYELEGK,0.044118,1,0,0,4,0,1,0,0,...,0.0,0.044118,0.000000,0.000000,0.000000,0.044118,0.000000,0.0,0.000000,0.0

In [11]:
# made a new dataframe that contains the suMN of NAAF normalized AAs for peaksdb417 peaksdb results
# also contains the suMN of the NAAF-corrected PTMN occurances for each affected residue

index = ['sample total']

data = {'NAAF': peaksdb417_NAAF['NAAF factor'].sum(),
        'A': peaksdb417_NAAF['A-NAAF20'].sum(),
        'C': peaksdb417_NAAF['C-NAAF20'].sum(),
        'D': peaksdb417_NAAF['D-NAAF20'].sum(),
        'E': peaksdb417_NAAF['E-NAAF20'].sum(),
        'F': peaksdb417_NAAF['F-NAAF20'].sum(),
        'G': peaksdb417_NAAF['G-NAAF20'].sum(),
        'H': peaksdb417_NAAF['H-NAAF20'].sum(),
        'I': peaksdb417_NAAF['I-NAAF20'].sum(),
        'K': peaksdb417_NAAF['K-NAAF20'].sum(),
        'L': peaksdb417_NAAF['L-NAAF20'].sum(),
        'M': peaksdb417_NAAF['M-NAAF20'].sum(),
        'N': peaksdb417_NAAF['N-NAAF20'].sum(),
        'P': peaksdb417_NAAF['P-NAAF20'].sum(),
        'Q': peaksdb417_NAAF['Q-NAAF20'].sum(),
        'R': peaksdb417_NAAF['R-NAAF20'].sum(),
        'S': peaksdb417_NAAF['S-NAAF20'].sum(),
        'T': peaksdb417_NAAF['T-NAAF20'].sum(),
        'V': peaksdb417_NAAF['V-NAAF20'].sum(),
        'W': peaksdb417_NAAF['W-NAAF20'].sum(),
        'Y': peaksdb417_NAAF['Y-NAAF20'].sum(),
        'c-carb': peaksdb417_NAAF['ccarb-NAAF20'].sum(),
        'm-oxid': peaksdb417_NAAF['moxid-NAAF20'].sum(),
        'n-deam': peaksdb417_NAAF['ndeam-NAAF20'].sum(),
        'q-deam': peaksdb417_NAAF['qdeam-NAAF20'].sum()
       }

totalpeaksdb417_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', \
                                                   'G', 'H', 'I','K', 'L', 'M', \
                                                   'N', 'P', 'Q', 'R', 'S', \
                                                   'T', 'V', 'W', 'Y', 'c-carb', \
                                                   'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate the NAAF-corrected % modified C, M, N, Q, K, and Rs


# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaksdb417_NAAF['% C w/ carb.'] = totalpeaksdb417_NAAF['c-carb'] / totalpeaksdb417_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaksdb417_NAAF['% M w/ oxid'] = totalpeaksdb417_NAAF['m-oxid'] / totalpeaksdb417_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb417_NAAF['% N w/ deam'] = totalpeaksdb417_NAAF['n-deam'] / totalpeaksdb417_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb417_NAAF['% Q w/ deam'] = totalpeaksdb417_NAAF['q-deam'] / totalpeaksdb417_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaksdb417_NAAF['NAAF check'] = totalpeaksdb417_NAAF['NAAF'] / 511882.681055

# write modified dataframe to new txt file, same name + totals
totalpeaksdb417_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas7-incubations/processed/PeaksDB/417_MN_T24_GD_PDB/417B_MN_T24_GD_PDB_naaf_totals.csv")

totalpeaksdb417_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,149.659263,87.492343,4.165133,8.3603,7.690806,5.136685,11.889387,4.947076,10.740828,5.419202,...,1.29539,4.165133,0.34699,0.592228,0.222946,1.0,0.719863,0.01671,0.079269,0.000292