### Manipulation of PEAKS de novo results of Trocas 8 (low water, November 2019) non-incubation samples LC-MS/MS data using python.

Starting with:

    PEAKS de novo results (.csv) of PTM-optimized sequencing >50% ALC

Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 675) for another
#### 2. Change output file name in *IN 6*, *IN 7*, *IN 8*

In [1]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [3]:
    cd /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/675_Trocas8_June2021_DENOVO_102/

/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/675_Trocas8_June2021_DENOVO_102

In [5]:
# read the CSVs into a dataframe using the read_csv function and call 'peaks'

peaks675 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/675_Trocas8_June2021_DENOVO_102/675_Trocas8_June2021_DENOVO_102_DN50.csv")

print("# redundant Peaks peptides >50% ALC in combined dataframe:", len(peaks675))

print(peaks675.columns)

# These columns mess things up- get rid of them

del peaks675['Fraction']
del peaks675['Scan']
del peaks675['Source File']
del peaks675['Tag Length']
del peaks675['PTM']
del peaks675['tag (>=0%)']
del peaks675['mode']
del peaks675['local confidence (%)']


columns = ['Peptide', 'ALC', 'length', 'm/z', 'z', 'RT', 'Area',
       'Mass', 'ppm']

peaks675.columns = columns

mean_len = peaks675['length'].mean()
print(mean_len)

# look at the dataframe
peaks675.head()

# redundant Peaks peptides >50% ALC in combined dataframe: 71
Index(['Fraction', 'Scan', 'Source File', 'Peptide', 'Tag Length', 'ALC (%)',
       'length', 'm/z', 'z', 'RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'tag (>=0%)', 'mode'],
      dtype='object')
9.816901408450704

       Peptide  ALC  length       m/z  z      RT       Area       Mass  ppm
0   LSSPATLNSR   98      10  523.2849  2   45.20  6190000.0  1044.5564 -1.1
1   LSSPATLNSR   98      10  523.2852  2   45.70  6190000.0  1044.5564 -0.6
2   LSSPATLNSR   98      10  523.2845  2   44.69  6190000.0  1044.5564 -1.9
3  KNYLSWVVEAR   95      11  682.8648  2  124.02     4790.0  1363.7249 -7.2
4  ELYLSWVVEAR   94      11  682.8645  2  115.59     8420.0  1363.7136  0.6

The peptide column has the masses of modifications (e.g., 57.02 Da for carbamidomethylation of cysteine). We want to make new columns with all that information and make a column with only the 'stripped' peptide sequence that's just amino acids - this we can then align against other sequences, for example.

Modified residues were allowed for:

    fixed carbamodimethylation of cysteine 57.021464 C
    varialbe oxidation of methionine: 15.9949 M
    variable deamidation of asparagine, glumatine: 0.984016 NQ

We'll then write this manipulated dataframe to a new file.

In [10]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaks675['A'] = peaks675['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaks675['C'] = peaks675['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaks675['D'] = peaks675['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaks675['E'] = peaks675['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaks675['F'] = peaks675['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaks675['G'] = peaks675['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaks675['H'] = peaks675['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaks675 output, there will be no isoleucines (they're lumped in with leucines)
peaks675['I'] = peaks675['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaks675['K'] = peaks675['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaks675['L'] = peaks675['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaks675['M'] = peaks675['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaks675['N'] = peaks675['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaks675['P'] = peaks675['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaks675['Q'] = peaks675['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaks675['R'] = peaks675['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaks675['S'] = peaks675['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaks675['T'] = peaks675['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaks675['V'] = peaks675['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaks675['W'] = peaks675['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaks675['Y'] = peaks675['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaks675['c-carb'] = peaks675['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaks675['m-oxid'] = peaks675['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaks675['n-deam'] = peaks675['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a count function to enumerate the # of deamidated Q's in each peptide
peaks675['q-deam'] = peaks675['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaks675['stripped_peptide'] = peaks675['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaks675['stripped_length'] = peaks675['stripped_peptide'].apply(len)

# total the number of modifications in sequence
peaks675['ptm-total'] = peaks675['c-carb'] + peaks675['m-oxid'] + peaks675['n-deam'] + peaks675['q-deam']

# calculate NAAF numerator for each peptide k
peaks675['NAAF_num.'] = peaks675['Area'] / peaks675['stripped_length']

# write modified dataframe to new txt file, same name + 'stripped'
peaks675.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/675_BY_50_GF75_DN/675_BY_50_GF75_DN50.csv")

# check out the results
peaks675.head()

,Peptide,ALC,length,m/z,z,RT,Area,Mass,ppm,A,...,W,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,ptm-total,NAAF_num.
0,LSSPATLNSR,98,10,523.2849,2,45.20,6190000.0,1044.5564,-1.1,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,619000.000000
1,LSSPATLNSR,98,10,523.2852,2,45.70,6190000.0,1044.5564,-0.6,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,619000.000000
2,LSSPATLNSR,98,10,523.2845,2,44.69,6190000.0,1044.5564,-1.9,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,619000.000000
3,KNYLSWVVEAR,95,11,682.8648,2,124.02,4790.0,1363.7249,-7.2,1,...,1,1,0,0,0,0,KNYLSWVVEAR,11,0,435.454545
4,ELYLSWVVEAR,94,11,682.8645,2,115.59,8420.0,1363.7136,0.6,1,...,1,1,0,0,0,0,ELYLSWVVEAR,11,0,765.454545

In [11]:
# keep only stripped peptide I/L and NAAF
dn_675 = peaks675[['stripped_peptide', 'Area', 'NAAF_num.']]

dn_675.set_index('stripped_peptide')

# write modified dataframe to new txt file
dn_675.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/I-L_NAAFs/675_BY_50_GF75_DN50_ILnaafs.csv")

dn_675.head()

  stripped_peptide       Area      NAAF_num.
0       LSSPATLNSR  6190000.0  619000.000000
1       LSSPATLNSR  6190000.0  619000.000000
2       LSSPATLNSR  6190000.0  619000.000000
3      KNYLSWVVEAR     4790.0     435.454545
4      ELYLSWVVEAR     8420.0     765.454545

In [12]:
# made a new dataframe that contains the sums of certain columns 
# in the stripped peptide dataframe above (for >50% ALC)

index = ['sample total']

data = {'A': peaks675['A'].sum(),
        'C': peaks675['C'].sum(),
        'D': peaks675['D'].sum(),
        'E': peaks675['E'].sum(),
        'F': peaks675['F'].sum(),
        'G': peaks675['G'].sum(),
        'H': peaks675['H'].sum(),
        'I': peaks675['I'].sum(),
        'K': peaks675['K'].sum(),
        'L': peaks675['L'].sum(),
        'M': peaks675['M'].sum(),
        'N': peaks675['N'].sum(),
        'P': peaks675['P'].sum(),
        'Q': peaks675['Q'].sum(),
        'R': peaks675['R'].sum(),
        'S': peaks675['S'].sum(),
        'T': peaks675['T'].sum(),
        'V': peaks675['V'].sum(),
        'W': peaks675['W'].sum(),
        'Y': peaks675['Y'].sum(),
        'c-carb': peaks675['c-carb'].sum(),
        'm-oxid': peaks675['m-oxid'].sum(),
        'n-deam': peaks675['n-deam'].sum(),
        'q-deam': peaks675['q-deam'].sum(),
        'Total area': peaks675['Area'].sum(),
        'Total length': peaks675['stripped_length'].sum()
       }

totalpeaks675 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                            'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                            'c-carb', 'm-oxid', 'n-deam', 'q-deam', \
                                            'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaks675['% C w/ carb'] = totalpeaks675['c-carb'] / totalpeaks675['C'] 

# calculate percentage of M's that are oxidized
totalpeaks675['% M w/ oxid'] = totalpeaks675['m-oxid'] / totalpeaks675['M'] 

# calculate percentage of N's that are deamidated
totalpeaks675['% N w/ deam'] = totalpeaks675['n-deam'] / totalpeaks675['N'] 

# calculate percentage of N's that are deamidated
totalpeaks675['% Q w/ deam'] = totalpeaks675['q-deam'] / totalpeaks675['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaks675['NAAF denom.'] = totalpeaks675['Total area'] / totalpeaks675['Total length']

# write modified dataframe to new txt file
totalpeaks675.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/675_BY_50_GF75_DN/675_BY_50_GF75_DN50_totals.csv")

totalpeaks675.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,38,5,6,38,8,7,17,0,45,109,...,3,2,1,107647510.0,691,1.0,0.333333,0.060606,0.05,155785.108538

In [13]:
# use the calculated NAAF factor (in totalpeaks dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

# don't have to worry here about DECOY hits messing with Area totals
# but we would with Comet results

NAAF50 = 155785.108538

# use NAAF >50% ALC to get NAAF factor
peaks675['NAAF factor'] = (peaks675['NAAF_num.'])/NAAF50

# make a dataframe that contains only what we need: sequences, AAs, PTMs
peaksAAPTM_675 = peaks675[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'I', 'L', \
                                'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', 'c-carb', 'm-oxid', \
                                'n-deam', 'q-deam']].copy()

# multiply the NAAF50 factor by the AA total to normalize its abundance by peak area and peptide length

peaksAAPTM_675['A-NAAF50'] = peaksAAPTM_675['A'] * peaks675['NAAF factor']
peaksAAPTM_675['C-NAAF50'] = peaksAAPTM_675['C'] * peaks675['NAAF factor']
peaksAAPTM_675['D-NAAF50'] = peaksAAPTM_675['D'] * peaks675['NAAF factor']
peaksAAPTM_675['E-NAAF50'] = peaksAAPTM_675['E'] * peaks675['NAAF factor']
peaksAAPTM_675['F-NAAF50'] = peaksAAPTM_675['F'] * peaks675['NAAF factor']
peaksAAPTM_675['G-NAAF50'] = peaksAAPTM_675['G'] * peaks675['NAAF factor']
peaksAAPTM_675['H-NAAF50'] = peaksAAPTM_675['H'] * peaks675['NAAF factor']
peaksAAPTM_675['I-NAAF50'] = peaksAAPTM_675['I'] * peaks675['NAAF factor']
peaksAAPTM_675['K-NAAF50'] = peaksAAPTM_675['K'] * peaks675['NAAF factor']
peaksAAPTM_675['L-NAAF50'] = peaksAAPTM_675['L'] * peaks675['NAAF factor']
peaksAAPTM_675['M-NAAF50'] = peaksAAPTM_675['M'] * peaks675['NAAF factor']
peaksAAPTM_675['N-NAAF50'] = peaksAAPTM_675['N'] * peaks675['NAAF factor']
peaksAAPTM_675['P-NAAF50'] = peaksAAPTM_675['P'] * peaks675['NAAF factor']
peaksAAPTM_675['Q-NAAF50'] = peaksAAPTM_675['Q'] * peaks675['NAAF factor']
peaksAAPTM_675['R-NAAF50'] = peaksAAPTM_675['R'] * peaks675['NAAF factor']
peaksAAPTM_675['S-NAAF50'] = peaksAAPTM_675['S'] * peaks675['NAAF factor']
peaksAAPTM_675['T-NAAF50'] = peaksAAPTM_675['T'] * peaks675['NAAF factor']
peaksAAPTM_675['V-NAAF50'] = peaksAAPTM_675['V'] * peaks675['NAAF factor']
peaksAAPTM_675['W-NAAF50'] = peaksAAPTM_675['W'] * peaks675['NAAF factor']
peaksAAPTM_675['Y-NAAF50'] = peaksAAPTM_675['Y'] * peaks675['NAAF factor']

# multiply the NAAF50 factor by the PTMs normalize its abundance by peak area and peptide length

peaksAAPTM_675['ccarb-NAAF50'] = peaksAAPTM_675['c-carb'] * peaksAAPTM_675['NAAF factor']
peaksAAPTM_675['moxid-NAAF50'] = peaksAAPTM_675['m-oxid'] * peaksAAPTM_675['NAAF factor']
peaksAAPTM_675['ndeam-NAAF50'] = peaksAAPTM_675['n-deam'] * peaksAAPTM_675['NAAF factor']
peaksAAPTM_675['qdeam-NAAF50'] = peaksAAPTM_675['q-deam'] * peaksAAPTM_675['NAAF factor']


# write the dataframe to a new csv
peaksAAPTM_675.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/675_BY_50_GF75_DN/675_BY_50_GF75_DN50_naaf.csv")

peaksAAPTM_675.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,K,...,R-NAAF50,S-NAAF50,T-NAAF50,V-NAAF50,W-NAAF50,Y-NAAF50,ccarb-NAAF50,moxid-NAAF50,ndeam-NAAF50,qdeam-NAAF50
0,LSSPATLNSR,3.973422,1,0,0,0,0,0,0,0,...,3.973422,11.920266,3.973422,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
1,LSSPATLNSR,3.973422,1,0,0,0,0,0,0,0,...,3.973422,11.920266,3.973422,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
2,LSSPATLNSR,3.973422,1,0,0,0,0,0,0,0,...,3.973422,11.920266,3.973422,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
3,KNYLSWVVEAR,0.002795,1,0,0,1,0,0,0,1,...,0.002795,0.002795,0.000000,0.005590,0.002795,0.002795,0.0,0.0,0.0,0.0
4,ELYLSWVVEAR,0.004914,1,0,0,2,0,0,0,0,...,0.004914,0.004914,0.000000,0.009827,0.004914,0.004914,0.0,0.0,0.0,0.0

In [14]:
# made a dataframe that's the sum of NAAF corrected AAs and PTMs

index = ['sample total']

data = {'NAAF': peaksAAPTM_675['NAAF factor'].sum(),
        'A': peaksAAPTM_675['A-NAAF50'].sum(),
        'C': peaksAAPTM_675['C-NAAF50'].sum(),
        'D': peaksAAPTM_675['D-NAAF50'].sum(),
        'E': peaksAAPTM_675['E-NAAF50'].sum(),
        'F': peaksAAPTM_675['F-NAAF50'].sum(),
        'G': peaksAAPTM_675['G-NAAF50'].sum(),
        'H': peaksAAPTM_675['H-NAAF50'].sum(),
        'I': peaksAAPTM_675['I-NAAF50'].sum(),
        'K': peaksAAPTM_675['K-NAAF50'].sum(),
        'L': peaksAAPTM_675['L-NAAF50'].sum(),
        'M': peaksAAPTM_675['M-NAAF50'].sum(),
        'N': peaksAAPTM_675['N-NAAF50'].sum(),
        'P': peaksAAPTM_675['P-NAAF50'].sum(),
        'Q': peaksAAPTM_675['Q-NAAF50'].sum(),
        'R': peaksAAPTM_675['R-NAAF50'].sum(),
        'S': peaksAAPTM_675['S-NAAF50'].sum(),
        'T': peaksAAPTM_675['T-NAAF50'].sum(),
        'V': peaksAAPTM_675['V-NAAF50'].sum(),
        'W': peaksAAPTM_675['W-NAAF50'].sum(),
        'Y': peaksAAPTM_675['Y-NAAF50'].sum(),
        'c-carb': peaksAAPTM_675['ccarb-NAAF50'].sum(),
        'm-oxid': peaksAAPTM_675['moxid-NAAF50'].sum(),
        'n-deam': peaksAAPTM_675['ndeam-NAAF50'].sum(),
        'q-deam': peaksAAPTM_675['qdeam-NAAF50'].sum(),
       }

totalpeaks50_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', \
                                           'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', \
                                           'W', 'Y', 'c-carb', 'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaks50_NAAF['% C w/ carb.'] = totalpeaks50_NAAF['c-carb'] / totalpeaks50_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaks50_NAAF['% M w/ oxid'] = totalpeaks50_NAAF['m-oxid'] / totalpeaks50_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% N w/ deam'] = totalpeaks50_NAAF['n-deam'] / totalpeaks50_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% Q w/ deam'] = totalpeaks50_NAAF['q-deam'] / totalpeaks50_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaks50_NAAF['NAAF check'] = totalpeaks50_NAAF['NAAF'] / 155785.108538

# write modified dataframe to new txt file, same name + totals
totalpeaks50_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/675_BY_50_GF75_DN/675_BY_50_GF75_DN50_naaf_totals.csv")

totalpeaks50_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,82.265013,39.863017,0.057901,0.03493,0.153283,0.075474,5.445283,0.142635,0.0,1.008773,...,0.546849,0.057901,0.009081,0.001424,0.025676,1.0,0.276834,0.000086,0.093098,0.000528

## Export stripped peptides >50% ALC

In [15]:
##### keep only stripped peptide column 
pep50 = peaks675[["stripped_peptide"]]

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing

pep50.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/675_BY_50_GF75_DN/675_BY_50_GF75_DN50_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/675_BY_50_GF75_DN/675_BY_50_GF75_DN50_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/675_BY_50_GF75_DN/675_BY_50_GF75_DN50_stripped_peptides.fas

# removing redundancy
peaks50dedup = pd.DataFrame.drop_duplicates(pep50)

print("# redundant stripped Peaks peptides >50% ALC", len(pep50))
print("# nonredundant stripped Peaks peptides >50% ALC", len(peaks50dedup))
print("average peptide length Peaks peptides >50% ALC", peaks675['stripped_length'].mean())

# count all unique peptide (modified peptides included)
# keep only peptide column >50% ALC
pep50m = peaks675[["Peptide"]]

# deduplicate
pep50mdedup = pd.DataFrame.drop_duplicates(pep50m)

print("# redundant Peaks peptides >50% ALC", len(pep50m))
print("# nonredundant Peaks peptides", len(pep50mdedup))

# check
pep50.head()

# redundant stripped Peaks peptides >50% ALC 71
# nonredundant stripped Peaks peptides >50% ALC 47
average peptide length Peaks peptides >50% ALC 9.732394366197184
# redundant Peaks peptides >50% ALC 71
# nonredundant Peaks peptides 47

  stripped_peptide
0       LSSPATLNSR
1       LSSPATLNSR
2       LSSPATLNSR
3      KNYLSWVVEAR
4      ELYLSWVVEAR