### Manipulation of PEAKS de novo results of Trocas 8 (low water, November 2019) non-incubation samples LC-MS/MS data using python.

Starting with:

    PEAKS de novo results (.csv) of PTM-optimized sequencing >50% ALC

Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 675) for another
#### 2. Change output file name in *IN 6*, *IN 7*, *IN 8*

In [1]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [2]:
    cd /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/681_Trocas8_June2021_DENOVO_108/

/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/681_Trocas8_June2021_DENOVO_108

In [3]:
# read the CSVs into a dataframe using the read_csv function and call 'peaks'

peaks681 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/681_Trocas8_June2021_DENOVO_108/681_Trocas8_June2021_DENOVO_108_DN50.csv")

print("# redundant Peaks peptides >50% ALC in combined dataframe:", len(peaks681))

print(peaks681.columns)

# These columns mess things up- get rid of them

del peaks681['Fraction']
del peaks681['Scan']
del peaks681['Source File']
del peaks681['Tag Length']
del peaks681['PTM']
del peaks681['tag (>=0%)']
del peaks681['mode']
del peaks681['local confidence (%)']


columns = ['Peptide', 'ALC', 'length', 'm/z', 'z', 'RT', 'Area',
       'Mass', 'ppm']

peaks681.columns = columns

mean_len = peaks681['length'].mean()
print(mean_len)

# look at the dataframe
peaks681.head()

# redundant Peaks peptides >50% ALC in combined dataframe: 67
Index(['Fraction', 'Scan', 'Source File', 'Peptide', 'Tag Length', 'ALC (%)',
       'length', 'm/z', 'z', 'RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'tag (>=0%)', 'mode'],
      dtype='object')
9.104477611940299

      Peptide  ALC  length       m/z  z     RT       Area       Mass  ppm
0    SPATLNSR   98       8  423.2270  2  22.73    62000.0   844.4402 -1.0
1  LSSPATLNSR   98      10  523.2850  2  44.44  9990000.0  1044.5564 -0.8
2    SPATLNSR   98       8  423.2269  2  22.23    62000.0   844.4402 -1.3
3  LSSPATLNSR   98      10  523.2853  2  43.93  9990000.0  1044.5564 -0.4
4  LSSPATLDSR   98      10  523.7778  2  47.56   125000.0  1045.5403  0.8

The peptide column has the masses of modifications (e.g., 57.02 Da for carbamidomethylation of cysteine). We want to make new columns with all that information and make a column with only the 'stripped' peptide sequence that's just amino acids - this we can then align against other sequences, for example.

Modified residues were allowed for:

    fixed carbamodimethylation of cysteine 57.021464 C
    varialbe oxidation of methionine: 15.9949 M
    variable deamidation of asparagine, glumatine: 0.984016 NQ

We'll then write this manipulated dataframe to a new file.

In [5]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaks681['A'] = peaks681['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaks681['C'] = peaks681['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaks681['D'] = peaks681['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaks681['E'] = peaks681['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaks681['F'] = peaks681['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaks681['G'] = peaks681['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaks681['H'] = peaks681['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaks681 output, there will be no isoleucines (they're lumped in with leucines)
peaks681['I'] = peaks681['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaks681['K'] = peaks681['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaks681['L'] = peaks681['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaks681['M'] = peaks681['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaks681['N'] = peaks681['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaks681['P'] = peaks681['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaks681['Q'] = peaks681['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaks681['R'] = peaks681['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaks681['S'] = peaks681['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaks681['T'] = peaks681['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaks681['V'] = peaks681['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaks681['W'] = peaks681['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaks681['Y'] = peaks681['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaks681['c-carb'] = peaks681['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaks681['m-oxid'] = peaks681['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaks681['n-deam'] = peaks681['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a count function to enumerate the # of deamidated Q's in each peptide
peaks681['q-deam'] = peaks681['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaks681['stripped_peptide'] = peaks681['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaks681['stripped_length'] = peaks681['stripped_peptide'].apply(len)

# total the number of modifications in sequence
peaks681['ptm-total'] = peaks681['c-carb'] + peaks681['m-oxid'] + peaks681['n-deam'] + peaks681['q-deam']

# calculate NAAF numerator for each peptide k
peaks681['NAAF_num.'] = peaks681['Area'] / peaks681['stripped_length']

# write modified dataframe to new txt file, same name + 'stripped'
peaks681.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/681_NMCP_50_GF75_DN/681_NMCP_50_GF75_DN50.csv")

# check out the results
peaks681.head()

,Peptide,ALC,length,m/z,z,RT,Area,Mass,ppm,A,...,W,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,ptm-total,NAAF_num.
0,SPATLNSR,98,8,423.2270,2,22.73,62000.0,844.4402,-1.0,1,...,0,0,0,0,0,0,SPATLNSR,8,0,7750.0
1,LSSPATLNSR,98,10,523.2850,2,44.44,9990000.0,1044.5564,-0.8,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,999000.0
2,SPATLNSR,98,8,423.2269,2,22.23,62000.0,844.4402,-1.3,1,...,0,0,0,0,0,0,SPATLNSR,8,0,7750.0
3,LSSPATLNSR,98,10,523.2853,2,43.93,9990000.0,1044.5564,-0.4,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,999000.0
4,LSSPATLDSR,98,10,523.7778,2,47.56,125000.0,1045.5403,0.8,1,...,0,0,0,0,0,0,LSSPATLDSR,10,0,12500.0

In [6]:
# keep only stripped peptide I/L and NAAF
dn_681 = peaks681[['stripped_peptide', 'Area', 'NAAF_num.']]

dn_681.set_index('stripped_peptide')

# write modified dataframe to new txt file
dn_681.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/I-L_NAAFs/681_NMCP_50_GF75_DN50_ILnaafs.csv")

dn_681.head()

  stripped_peptide       Area  NAAF_num.
0         SPATLNSR    62000.0     7750.0
1       LSSPATLNSR  9990000.0   999000.0
2         SPATLNSR    62000.0     7750.0
3       LSSPATLNSR  9990000.0   999000.0
4       LSSPATLDSR   125000.0    12500.0

In [7]:
# made a new dataframe that contains the sums of certain columns 
# in the stripped peptide dataframe above (for >50% ALC)

index = ['sample total']

data = {'A': peaks681['A'].sum(),
        'C': peaks681['C'].sum(),
        'D': peaks681['D'].sum(),
        'E': peaks681['E'].sum(),
        'F': peaks681['F'].sum(),
        'G': peaks681['G'].sum(),
        'H': peaks681['H'].sum(),
        'I': peaks681['I'].sum(),
        'K': peaks681['K'].sum(),
        'L': peaks681['L'].sum(),
        'M': peaks681['M'].sum(),
        'N': peaks681['N'].sum(),
        'P': peaks681['P'].sum(),
        'Q': peaks681['Q'].sum(),
        'R': peaks681['R'].sum(),
        'S': peaks681['S'].sum(),
        'T': peaks681['T'].sum(),
        'V': peaks681['V'].sum(),
        'W': peaks681['W'].sum(),
        'Y': peaks681['Y'].sum(),
        'c-carb': peaks681['c-carb'].sum(),
        'm-oxid': peaks681['m-oxid'].sum(),
        'n-deam': peaks681['n-deam'].sum(),
        'q-deam': peaks681['q-deam'].sum(),
        'Total area': peaks681['Area'].sum(),
        'Total length': peaks681['stripped_length'].sum()
       }

totalpeaks681 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                            'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                            'c-carb', 'm-oxid', 'n-deam', 'q-deam', \
                                            'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaks681['% C w/ carb'] = totalpeaks681['c-carb'] / totalpeaks681['C'] 

# calculate percentage of M's that are oxidized
totalpeaks681['% M w/ oxid'] = totalpeaks681['m-oxid'] / totalpeaks681['M'] 

# calculate percentage of N's that are deamidated
totalpeaks681['% N w/ deam'] = totalpeaks681['n-deam'] / totalpeaks681['N'] 

# calculate percentage of N's that are deamidated
totalpeaks681['% Q w/ deam'] = totalpeaks681['q-deam'] / totalpeaks681['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaks681['NAAF denom.'] = totalpeaks681['Total area'] / totalpeaks681['Total length']

# write modified dataframe to new txt file
totalpeaks681.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/681_NMCP_50_GF75_DN/681_NMCP_50_GF75_DN50_totals.csv")

totalpeaks681.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,49,3,11,26,12,15,29,0,26,91,...,10,3,3,122674029.0,596,1.0,0.27027,0.115385,0.272727,205828.907718

In [8]:
# use the calculated NAAF factor (in totalpeaks dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

# don't have to worry here about DECOY hits messing with Area totals
# but we would with Comet results

NAAF50 = 205828.907718

# use NAAF >50% ALC to get NAAF factor
peaks681['NAAF factor'] = (peaks681['NAAF_num.'])/NAAF50

# make a dataframe that contains only what we need: sequences, AAs, PTMs
peaksAAPTM_681 = peaks681[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'I', 'L', \
                                'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', 'c-carb', 'm-oxid', \
                                'n-deam', 'q-deam']].copy()

# multiply the NAAF50 factor by the AA total to normalize its abundance by peak area and peptide length

peaksAAPTM_681['A-NAAF50'] = peaksAAPTM_681['A'] * peaks681['NAAF factor']
peaksAAPTM_681['C-NAAF50'] = peaksAAPTM_681['C'] * peaks681['NAAF factor']
peaksAAPTM_681['D-NAAF50'] = peaksAAPTM_681['D'] * peaks681['NAAF factor']
peaksAAPTM_681['E-NAAF50'] = peaksAAPTM_681['E'] * peaks681['NAAF factor']
peaksAAPTM_681['F-NAAF50'] = peaksAAPTM_681['F'] * peaks681['NAAF factor']
peaksAAPTM_681['G-NAAF50'] = peaksAAPTM_681['G'] * peaks681['NAAF factor']
peaksAAPTM_681['H-NAAF50'] = peaksAAPTM_681['H'] * peaks681['NAAF factor']
peaksAAPTM_681['I-NAAF50'] = peaksAAPTM_681['I'] * peaks681['NAAF factor']
peaksAAPTM_681['K-NAAF50'] = peaksAAPTM_681['K'] * peaks681['NAAF factor']
peaksAAPTM_681['L-NAAF50'] = peaksAAPTM_681['L'] * peaks681['NAAF factor']
peaksAAPTM_681['M-NAAF50'] = peaksAAPTM_681['M'] * peaks681['NAAF factor']
peaksAAPTM_681['N-NAAF50'] = peaksAAPTM_681['N'] * peaks681['NAAF factor']
peaksAAPTM_681['P-NAAF50'] = peaksAAPTM_681['P'] * peaks681['NAAF factor']
peaksAAPTM_681['Q-NAAF50'] = peaksAAPTM_681['Q'] * peaks681['NAAF factor']
peaksAAPTM_681['R-NAAF50'] = peaksAAPTM_681['R'] * peaks681['NAAF factor']
peaksAAPTM_681['S-NAAF50'] = peaksAAPTM_681['S'] * peaks681['NAAF factor']
peaksAAPTM_681['T-NAAF50'] = peaksAAPTM_681['T'] * peaks681['NAAF factor']
peaksAAPTM_681['V-NAAF50'] = peaksAAPTM_681['V'] * peaks681['NAAF factor']
peaksAAPTM_681['W-NAAF50'] = peaksAAPTM_681['W'] * peaks681['NAAF factor']
peaksAAPTM_681['Y-NAAF50'] = peaksAAPTM_681['Y'] * peaks681['NAAF factor']

# multiply the NAAF50 factor by the PTMs normalize its abundance by peak area and peptide length

peaksAAPTM_681['ccarb-NAAF50'] = peaksAAPTM_681['c-carb'] * peaksAAPTM_681['NAAF factor']
peaksAAPTM_681['moxid-NAAF50'] = peaksAAPTM_681['m-oxid'] * peaksAAPTM_681['NAAF factor']
peaksAAPTM_681['ndeam-NAAF50'] = peaksAAPTM_681['n-deam'] * peaksAAPTM_681['NAAF factor']
peaksAAPTM_681['qdeam-NAAF50'] = peaksAAPTM_681['q-deam'] * peaksAAPTM_681['NAAF factor']


# write the dataframe to a new csv
peaksAAPTM_681.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/681_NMCP_50_GF75_DN/681_NMCP_50_GF75_DN50_naaf.csv")

peaksAAPTM_681.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,K,...,R-NAAF50,S-NAAF50,T-NAAF50,V-NAAF50,W-NAAF50,Y-NAAF50,ccarb-NAAF50,moxid-NAAF50,ndeam-NAAF50,qdeam-NAAF50
0,SPATLNSR,0.037653,1,0,0,0,0,0,0,0,...,0.037653,0.075305,0.037653,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,LSSPATLNSR,4.853546,1,0,0,0,0,0,0,0,...,4.853546,14.560637,4.853546,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SPATLNSR,0.037653,1,0,0,0,0,0,0,0,...,0.037653,0.075305,0.037653,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,LSSPATLNSR,4.853546,1,0,0,0,0,0,0,0,...,4.853546,14.560637,4.853546,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,LSSPATLDSR,0.060730,1,0,1,0,0,0,0,0,...,0.060730,0.182190,0.060730,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
# made a dataframe that's the sum of NAAF corrected AAs and PTMs

index = ['sample total']

data = {'NAAF': peaksAAPTM_681['NAAF factor'].sum(),
        'A': peaksAAPTM_681['A-NAAF50'].sum(),
        'C': peaksAAPTM_681['C-NAAF50'].sum(),
        'D': peaksAAPTM_681['D-NAAF50'].sum(),
        'E': peaksAAPTM_681['E-NAAF50'].sum(),
        'F': peaksAAPTM_681['F-NAAF50'].sum(),
        'G': peaksAAPTM_681['G-NAAF50'].sum(),
        'H': peaksAAPTM_681['H-NAAF50'].sum(),
        'I': peaksAAPTM_681['I-NAAF50'].sum(),
        'K': peaksAAPTM_681['K-NAAF50'].sum(),
        'L': peaksAAPTM_681['L-NAAF50'].sum(),
        'M': peaksAAPTM_681['M-NAAF50'].sum(),
        'N': peaksAAPTM_681['N-NAAF50'].sum(),
        'P': peaksAAPTM_681['P-NAAF50'].sum(),
        'Q': peaksAAPTM_681['Q-NAAF50'].sum(),
        'R': peaksAAPTM_681['R-NAAF50'].sum(),
        'S': peaksAAPTM_681['S-NAAF50'].sum(),
        'T': peaksAAPTM_681['T-NAAF50'].sum(),
        'V': peaksAAPTM_681['V-NAAF50'].sum(),
        'W': peaksAAPTM_681['W-NAAF50'].sum(),
        'Y': peaksAAPTM_681['Y-NAAF50'].sum(),
        'c-carb': peaksAAPTM_681['ccarb-NAAF50'].sum(),
        'm-oxid': peaksAAPTM_681['moxid-NAAF50'].sum(),
        'n-deam': peaksAAPTM_681['ndeam-NAAF50'].sum(),
        'q-deam': peaksAAPTM_681['qdeam-NAAF50'].sum(),
       }

totalpeaks50_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', \
                                           'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', \
                                           'W', 'Y', 'c-carb', 'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaks50_NAAF['% C w/ carb.'] = totalpeaks50_NAAF['c-carb'] / totalpeaks50_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaks50_NAAF['% M w/ oxid'] = totalpeaks50_NAAF['m-oxid'] / totalpeaks50_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% N w/ deam'] = totalpeaks50_NAAF['n-deam'] / totalpeaks50_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% Q w/ deam'] = totalpeaks50_NAAF['q-deam'] / totalpeaks50_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaks50_NAAF['NAAF check'] = totalpeaks50_NAAF['NAAF'] / 205828.907718

# write modified dataframe to new txt file, same name + totals
totalpeaks50_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/681_NMCP_50_GF75_DN/681_NMCP_50_GF75_DN50_naaf_totals.csv")

totalpeaks50_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,70.78551,55.510992,0.160165,0.825263,0.159297,0.776175,3.488512,1.079866,0.0,1.266317,...,2.611093,0.160165,0.689685,0.187237,0.236604,1.0,0.317418,0.011841,0.430827,0.000344

## Export stripped peptides >50% ALC

In [10]:
###### keep only stripped peptide column 
pep50 = peaks681[["stripped_peptide"]]

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing

pep50.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/681_NMCP_50_GF75_DN/681_NMCP_50_GF75_DN50_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/681_NMCP_50_GF75_DN/681_NMCP_50_GF75_DN50_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/681_NMCP_50_GF75_DN/681_NMCP_50_GF75_DN50_stripped_peptides.fas

# removing redundancy
peaks50dedup = pd.DataFrame.drop_duplicates(pep50)

print("# redundant stripped Peaks peptides >50% ALC", len(pep50))
print("# nonredundant stripped Peaks peptides >50% ALC", len(peaks50dedup))
print("average peptide length Peaks peptides >50% ALC", peaks681['stripped_length'].mean())

# count all unique peptide (modified peptides included)
# keep only peptide column >50% ALC
pep50m = peaks681[["Peptide"]]

# deduplicate
pep50mdedup = pd.DataFrame.drop_duplicates(pep50m)

print("# redundant Peaks peptides >50% ALC", len(pep50m))
print("# nonredundant Peaks peptides", len(pep50mdedup))

# check
pep50.head()

# redundant stripped Peaks peptides >50% ALC 67
# nonredundant stripped Peaks peptides >50% ALC 53
average peptide length Peaks peptides >50% ALC 8.895522388059701
# redundant Peaks peptides >50% ALC 67
# nonredundant Peaks peptides 53

  stripped_peptide
0         SPATLNSR
1       LSSPATLNSR
2         SPATLNSR
3       LSSPATLNSR
4       LSSPATLDSR