### Manipulation of PEAKS de novo results of Trocas 8 (low water, November 2019) non-incubation samples LC-MS/MS data using python.

Starting with:

    PEAKS de novo results (.csv) of PTM-optimized sequencing >50% ALC

Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 675) for another
#### 2. Change output file name in *IN 6*, *IN 7*, *IN 8*

In [1]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [2]:
    cd /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/688_Trocas8_June2021_DENOVO_116/

/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/688_Trocas8_June2021_DENOVO_116

In [3]:
# read the CSVs into a dataframe using the read_csv function and call 'peaks'

peaks688 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/688_Trocas8_June2021_DENOVO_116/de novo peptides.csv")

print("# redundant Peaks peptides >50% ALC in combined dataframe:", len(peaks688))

print(peaks688.columns)

# These columns mess things up- get rid of them

del peaks688['Fraction']
del peaks688['Scan']
del peaks688['Source File']
del peaks688['Tag Length']
del peaks688['PTM']
del peaks688['tag (>=0%)']
del peaks688['mode']
del peaks688['local confidence (%)']


columns = ['Peptide', 'ALC', 'length', 'm/z', 'z', 'RT', 'Area',
       'Mass', 'ppm']

peaks688.columns = columns

mean_len = peaks688['length'].mean()
print(mean_len)

# look at the dataframe
peaks688.head()

# redundant Peaks peptides >50% ALC in combined dataframe: 74
Index(['Fraction', 'Scan', 'Source File', 'Peptide', 'Tag Length', 'ALC (%)',
       'length', 'm/z', 'z', 'RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'tag (>=0%)', 'mode'],
      dtype='object')
8.81081081081081

      Peptide  ALC  length       m/z  z     RT        Area       Mass  ppm
0  LSSPATLNSR   98      10  523.2848  2  45.33   9880000.0  1044.5564 -1.3
1  LSSPATLNSR   98      10  523.2854  2  44.83   9880000.0  1044.5564 -0.1
2  LVNELTEFAK   98      10  582.3184  2  86.14     42500.0  1162.6233 -0.9
3     ATEQELK   97       7  409.7160  2  21.60     10700.0   817.4182 -0.9
4    VATVSPLR   95       8  421.7583  2  58.40  17100000.0   841.5021 -0.2

The peptide column has the masses of modifications (e.g., 57.02 Da for carbamidomethylation of cysteine). We want to make new columns with all that information and make a column with only the 'stripped' peptide sequence that's just amino acids - this we can then align against other sequences, for example.

Modified residues were allowed for:

    fixed carbamodimethylation of cysteine 57.021464 C
    varialbe oxidation of methionine: 15.9949 M
    variable deamidation of asparagine, glumatine: 0.984016 NQ

We'll then write this manipulated dataframe to a new file.

In [4]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaks688['A'] = peaks688['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaks688['C'] = peaks688['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaks688['D'] = peaks688['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaks688['E'] = peaks688['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaks688['F'] = peaks688['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaks688['G'] = peaks688['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaks688['H'] = peaks688['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaks688 output, there will be no isoleucines (they're lumped in with leucines)
peaks688['I'] = peaks688['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaks688['K'] = peaks688['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaks688['L'] = peaks688['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaks688['M'] = peaks688['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaks688['N'] = peaks688['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaks688['P'] = peaks688['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaks688['Q'] = peaks688['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaks688['R'] = peaks688['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaks688['S'] = peaks688['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaks688['T'] = peaks688['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaks688['V'] = peaks688['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaks688['W'] = peaks688['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaks688['Y'] = peaks688['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaks688['c-carb'] = peaks688['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaks688['m-oxid'] = peaks688['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaks688['n-deam'] = peaks688['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a count function to enumerate the # of deamidated Q's in each peptide
peaks688['q-deam'] = peaks688['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaks688['stripped_peptide'] = peaks688['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaks688['stripped_length'] = peaks688['stripped_peptide'].apply(len)

# total the number of modifications in sequence
peaks688['ptm-total'] = peaks688['c-carb'] + peaks688['m-oxid'] + peaks688['n-deam'] + peaks688['q-deam']

# calculate NAAF numerator for each peptide k
peaks688['NAAF_num.'] = peaks688['Area'] / peaks688['stripped_length']

# write modified dataframe to new txt file, same name + 'stripped'
peaks688.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/680_SMCP_surf_GF75_DN/688_SMCP_surf_GF75_DN50.csv")

# check out the results
peaks688.head()

,Peptide,ALC,length,m/z,z,RT,Area,Mass,ppm,A,...,W,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,ptm-total,NAAF_num.
0,LSSPATLNSR,98,10,523.2848,2,45.33,9880000.0,1044.5564,-1.3,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,9.880000e+05
1,LSSPATLNSR,98,10,523.2854,2,44.83,9880000.0,1044.5564,-0.1,1,...,0,0,0,0,0,0,LSSPATLNSR,10,0,9.880000e+05
2,LVNELTEFAK,98,10,582.3184,2,86.14,42500.0,1162.6233,-0.9,1,...,0,0,0,0,0,0,LVNELTEFAK,10,0,4.250000e+03
3,ATEQELK,97,7,409.7160,2,21.60,10700.0,817.4182,-0.9,1,...,0,0,0,0,0,0,ATEQELK,7,0,1.528571e+03
4,VATVSPLR,95,8,421.7583,2,58.40,17100000.0,841.5021,-0.2,1,...,0,0,0,0,0,0,VATVSPLR,8,0,2.137500e+06

In [5]:
# keep only stripped peptide I/L and NAAF
dn_688 = peaks688[['stripped_peptide', 'Area', 'NAAF_num.']]

dn_688.set_index('stripped_peptide')

# write modified dataframe to new txt file
dn_688.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/I-L_NAAFs/688_SMCP_surf_GF75_DN50_ILnaafs.csv")

dn_688.head()

  stripped_peptide        Area     NAAF_num.
0       LSSPATLNSR   9880000.0  9.880000e+05
1       LSSPATLNSR   9880000.0  9.880000e+05
2       LVNELTEFAK     42500.0  4.250000e+03
3          ATEQELK     10700.0  1.528571e+03
4         VATVSPLR  17100000.0  2.137500e+06

In [6]:
# made a new dataframe that contains the sums of certain columns 
# in the stripped peptide dataframe above (for >50% ALC)

index = ['sample total']

data = {'A': peaks688['A'].sum(),
        'C': peaks688['C'].sum(),
        'D': peaks688['D'].sum(),
        'E': peaks688['E'].sum(),
        'F': peaks688['F'].sum(),
        'G': peaks688['G'].sum(),
        'H': peaks688['H'].sum(),
        'I': peaks688['I'].sum(),
        'K': peaks688['K'].sum(),
        'L': peaks688['L'].sum(),
        'M': peaks688['M'].sum(),
        'N': peaks688['N'].sum(),
        'P': peaks688['P'].sum(),
        'Q': peaks688['Q'].sum(),
        'R': peaks688['R'].sum(),
        'S': peaks688['S'].sum(),
        'T': peaks688['T'].sum(),
        'V': peaks688['V'].sum(),
        'W': peaks688['W'].sum(),
        'Y': peaks688['Y'].sum(),
        'c-carb': peaks688['c-carb'].sum(),
        'm-oxid': peaks688['m-oxid'].sum(),
        'n-deam': peaks688['n-deam'].sum(),
        'q-deam': peaks688['q-deam'].sum(),
        'Total area': peaks688['Area'].sum(),
        'Total length': peaks688['stripped_length'].sum()
       }

totalpeaks688 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                            'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                            'c-carb', 'm-oxid', 'n-deam', 'q-deam', \
                                            'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaks688['% C w/ carb'] = totalpeaks688['c-carb'] / totalpeaks688['C'] 

# calculate percentage of M's that are oxidized
totalpeaks688['% M w/ oxid'] = totalpeaks688['m-oxid'] / totalpeaks688['M'] 

# calculate percentage of N's that are deamidated
totalpeaks688['% N w/ deam'] = totalpeaks688['n-deam'] / totalpeaks688['N'] 

# calculate percentage of N's that are deamidated
totalpeaks688['% Q w/ deam'] = totalpeaks688['q-deam'] / totalpeaks688['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaks688['NAAF denom.'] = totalpeaks688['Total area'] / totalpeaks688['Total length']

# write modified dataframe to new txt file
totalpeaks688.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/680_SMCP_surf_GF75_DN/688_SMCP_surf_GF75_DN50_totals.csv")

totalpeaks688.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,46,5,12,14,9,32,37,0,65,91,...,7,2,1,135933840.4,642,1.0,0.175,0.083333,0.090909,211734.953894

In [7]:
# use the calculated NAAF factor (in totalpeaks dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

# don't have to worry here about DECOY hits messing with Area totals
# but we would with Comet results

NAAF50 = 211734.953894

# use NAAF >50% ALC to get NAAF factor
peaks688['NAAF factor'] = (peaks688['NAAF_num.'])/NAAF50

# make a dataframe that contains only what we need: sequences, AAs, PTMs
peaksAAPTM_688 = peaks688[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'I', 'L', \
                                'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', 'c-carb', 'm-oxid', \
                                'n-deam', 'q-deam']].copy()

# multiply the NAAF50 factor by the AA total to normalize its abundance by peak area and peptide length

peaksAAPTM_688['A-NAAF50'] = peaksAAPTM_688['A'] * peaks688['NAAF factor']
peaksAAPTM_688['C-NAAF50'] = peaksAAPTM_688['C'] * peaks688['NAAF factor']
peaksAAPTM_688['D-NAAF50'] = peaksAAPTM_688['D'] * peaks688['NAAF factor']
peaksAAPTM_688['E-NAAF50'] = peaksAAPTM_688['E'] * peaks688['NAAF factor']
peaksAAPTM_688['F-NAAF50'] = peaksAAPTM_688['F'] * peaks688['NAAF factor']
peaksAAPTM_688['G-NAAF50'] = peaksAAPTM_688['G'] * peaks688['NAAF factor']
peaksAAPTM_688['H-NAAF50'] = peaksAAPTM_688['H'] * peaks688['NAAF factor']
peaksAAPTM_688['I-NAAF50'] = peaksAAPTM_688['I'] * peaks688['NAAF factor']
peaksAAPTM_688['K-NAAF50'] = peaksAAPTM_688['K'] * peaks688['NAAF factor']
peaksAAPTM_688['L-NAAF50'] = peaksAAPTM_688['L'] * peaks688['NAAF factor']
peaksAAPTM_688['M-NAAF50'] = peaksAAPTM_688['M'] * peaks688['NAAF factor']
peaksAAPTM_688['N-NAAF50'] = peaksAAPTM_688['N'] * peaks688['NAAF factor']
peaksAAPTM_688['P-NAAF50'] = peaksAAPTM_688['P'] * peaks688['NAAF factor']
peaksAAPTM_688['Q-NAAF50'] = peaksAAPTM_688['Q'] * peaks688['NAAF factor']
peaksAAPTM_688['R-NAAF50'] = peaksAAPTM_688['R'] * peaks688['NAAF factor']
peaksAAPTM_688['S-NAAF50'] = peaksAAPTM_688['S'] * peaks688['NAAF factor']
peaksAAPTM_688['T-NAAF50'] = peaksAAPTM_688['T'] * peaks688['NAAF factor']
peaksAAPTM_688['V-NAAF50'] = peaksAAPTM_688['V'] * peaks688['NAAF factor']
peaksAAPTM_688['W-NAAF50'] = peaksAAPTM_688['W'] * peaks688['NAAF factor']
peaksAAPTM_688['Y-NAAF50'] = peaksAAPTM_688['Y'] * peaks688['NAAF factor']

# multiply the NAAF50 factor by the PTMs normalize its abundance by peak area and peptide length

peaksAAPTM_688['ccarb-NAAF50'] = peaksAAPTM_688['c-carb'] * peaksAAPTM_688['NAAF factor']
peaksAAPTM_688['moxid-NAAF50'] = peaksAAPTM_688['m-oxid'] * peaksAAPTM_688['NAAF factor']
peaksAAPTM_688['ndeam-NAAF50'] = peaksAAPTM_688['n-deam'] * peaksAAPTM_688['NAAF factor']
peaksAAPTM_688['qdeam-NAAF50'] = peaksAAPTM_688['q-deam'] * peaksAAPTM_688['NAAF factor']


# write the dataframe to a new csv
peaksAAPTM_688.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/680_SMCP_surf_GF75_DN/688_SMCP_surf_GF75_DN50_naaf.csv")

peaksAAPTM_688.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,K,...,R-NAAF50,S-NAAF50,T-NAAF50,V-NAAF50,W-NAAF50,Y-NAAF50,ccarb-NAAF50,moxid-NAAF50,ndeam-NAAF50,qdeam-NAAF50
0,LSSPATLNSR,4.666211,1,0,0,0,0,0,0,0,...,4.666211,13.998633,4.666211,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,LSSPATLNSR,4.666211,1,0,0,0,0,0,0,0,...,4.666211,13.998633,4.666211,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,LVNELTEFAK,0.020072,1,0,0,2,1,0,0,1,...,0.000000,0.000000,0.020072,0.020072,0.0,0.0,0.0,0.0,0.0,0.0
3,ATEQELK,0.007219,1,0,0,2,0,0,0,1,...,0.000000,0.000000,0.007219,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,VATVSPLR,10.095168,1,0,0,0,0,0,0,0,...,10.095168,10.095168,10.095168,20.190337,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
# made a dataframe that's the sum of NAAF corrected AAs and PTMs

index = ['sample total']

data = {'NAAF': peaksAAPTM_688['NAAF factor'].sum(),
        'A': peaksAAPTM_688['A-NAAF50'].sum(),
        'C': peaksAAPTM_688['C-NAAF50'].sum(),
        'D': peaksAAPTM_688['D-NAAF50'].sum(),
        'E': peaksAAPTM_688['E-NAAF50'].sum(),
        'F': peaksAAPTM_688['F-NAAF50'].sum(),
        'G': peaksAAPTM_688['G-NAAF50'].sum(),
        'H': peaksAAPTM_688['H-NAAF50'].sum(),
        'I': peaksAAPTM_688['I-NAAF50'].sum(),
        'K': peaksAAPTM_688['K-NAAF50'].sum(),
        'L': peaksAAPTM_688['L-NAAF50'].sum(),
        'M': peaksAAPTM_688['M-NAAF50'].sum(),
        'N': peaksAAPTM_688['N-NAAF50'].sum(),
        'P': peaksAAPTM_688['P-NAAF50'].sum(),
        'Q': peaksAAPTM_688['Q-NAAF50'].sum(),
        'R': peaksAAPTM_688['R-NAAF50'].sum(),
        'S': peaksAAPTM_688['S-NAAF50'].sum(),
        'T': peaksAAPTM_688['T-NAAF50'].sum(),
        'V': peaksAAPTM_688['V-NAAF50'].sum(),
        'W': peaksAAPTM_688['W-NAAF50'].sum(),
        'Y': peaksAAPTM_688['Y-NAAF50'].sum(),
        'c-carb': peaksAAPTM_688['ccarb-NAAF50'].sum(),
        'm-oxid': peaksAAPTM_688['moxid-NAAF50'].sum(),
        'n-deam': peaksAAPTM_688['ndeam-NAAF50'].sum(),
        'q-deam': peaksAAPTM_688['qdeam-NAAF50'].sum(),
       }

totalpeaks50_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', \
                                           'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', \
                                           'W', 'Y', 'c-carb', 'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaks50_NAAF['% C w/ carb.'] = totalpeaks50_NAAF['c-carb'] / totalpeaks50_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaks50_NAAF['% M w/ oxid'] = totalpeaks50_NAAF['m-oxid'] / totalpeaks50_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% N w/ deam'] = totalpeaks50_NAAF['n-deam'] / totalpeaks50_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaks50_NAAF['% Q w/ deam'] = totalpeaks50_NAAF['q-deam'] / totalpeaks50_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaks50_NAAF['NAAF check'] = totalpeaks50_NAAF['NAAF'] / 211734.953894

# write modified dataframe to new txt file, same name + totals
totalpeaks50_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/680_SMCP_surf_GF75_DN/688_SMCP_surf_GF75_DN50_naaf_totals.csv")

totalpeaks50_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,77.819067,62.360439,0.108966,0.625266,0.1223,0.209262,3.959677,0.635092,0.0,1.599926,...,0.691168,0.108966,0.196363,0.005193,0.031171,1.0,0.16329,0.000527,0.084882,0.000368

## Export stripped peptides >50% ALC

In [9]:
###### keep only stripped peptide column 
pep50 = peaks688[["stripped_peptide"]]

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing

pep50.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/680_SMCP_surf_GF75_DN/688_SMCP_surf_GF75_DN50_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/680_SMCP_surf_GF75_DN/688_SMCP_surf_GF75_DN50_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDN/680_SMCP_surf_GF75_DN/688_SMCP_surf_GF75_DN50_stripped_peptides.fas

# removing redundancy
peaks50dedup = pd.DataFrame.drop_duplicates(pep50)

print("# redundant stripped Peaks peptides >50% ALC", len(pep50))
print("# nonredundant stripped Peaks peptides >50% ALC", len(peaks50dedup))
print("average peptide length Peaks peptides >50% ALC", peaks688['stripped_length'].mean())

# count all unique peptide (modified peptides included)
# keep only peptide column >50% ALC
pep50m = peaks688[["Peptide"]]

# deduplicate
pep50mdedup = pd.DataFrame.drop_duplicates(pep50m)

print("# redundant Peaks peptides >50% ALC", len(pep50m))
print("# nonredundant Peaks peptides", len(pep50mdedup))

# check
pep50.head()

# redundant stripped Peaks peptides >50% ALC 74
# nonredundant stripped Peaks peptides >50% ALC 60
average peptide length Peaks peptides >50% ALC 8.675675675675675
# redundant Peaks peptides >50% ALC 74
# nonredundant Peaks peptides 60

  stripped_peptide
0       LSSPATLNSR
1       LSSPATLNSR
2       LVNELTEFAK
3          ATEQELK
4         VATVSPLR