### Manipulation of PeaskDB de novo-assisted database search results of Trocas 8 (low water, November 2019) non incubation samples LC-MS/MS data using python.

Starting with:

    PeaksDB search results (.csv) of PTM-optimized database searches
    These were all searched with 15 ppm precursor tolerance and 0.5 ppm fragement ion tolerance
    Exported at <1.0% FDR
    
Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use for a different file:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 675) for another
#### 3. Update the NAAF factor calculated in *IN 6* into *IN 7*

In [14]:
cd /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/675_Trocas8_June2021_PEAKS_136/

/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/675_Trocas8_June2021_PEAKS_136

In [15]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [16]:
ls

 675_Trocas8_June2021_PEAKS_136_peptide.csv     'de novo only peptides.csv'
 675_Trocas8_June2021_PEAKS_136_proteins.csv     peptides_1_1_0.mzid
 675_Trocas8_June2021_PEAKS_136_proteins.fasta   protein-peptides.csv
'DB search psm.csv'

In [17]:
# read the CSV into a dataframe using the pandas read_csv function
peaksdbdup675 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/675_Trocas8_June2021_PEAKS_136/675_Trocas8_June2021_PEAKS_136_peptide.csv")

# remove redundant rows
peaksdb675 = pd.DataFrame.drop_duplicates(peaksdbdup675)

print(peaksdb675.columns)

columns = ['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area', 'Fraction', 'Scan', 'Source_File',
       '#Spec', '#Spec', 'Accession', 'PTM',
       'AScore']

peaksdb675.columns = columns

#remmove # spec and accession columns because they mess parsing up

del peaksdb675['#Spec']
del peaksdb675['Accession']
del peaksdb675['PTM']
del peaksdb675['AScore']

mean_length = peaksdb675['Length'].mean()
print(mean_length)

print("# redundant peaksdb peptides in combined dataframe", len(peaksdbdup675))
print("# nonredundant peaksdb peptides in combined dataframe", len(peaksdb675))

#look at the dataframe
peaksdb675.head()

Index(['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area Sample 1', 'Fraction', 'Scan', 'Source File', '#Spec',
       '#Spec Sample 1', 'Accession', 'PTM', 'AScore'],
      dtype='object')
10.980392156862745
# redundant peaksdb peptides in combined dataframe 51
# nonredundant peaksdb peptides in combined dataframe 51

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,Source_File
0,LSSPATLNSR,40.44,1044.5564,10,-0.6,523.2852,45.70,6190000.0,1,7681,20210622_Trocas8_675_Bay53_50%_DDA_120min.raw
1,LATVLSPR,34.23,855.5178,8,-0.3,428.7660,59.73,6900000.0,1,10285,20210622_Trocas8_675_Bay53_50%_DDA_120min.raw
2,LATVISPR,34.23,855.5178,8,-0.3,428.7660,59.73,6900000.0,1,10285,20210622_Trocas8_675_Bay53_50%_DDA_120min.raw
3,SLVNLGGSK,33.44,873.4919,9,-0.4,437.7531,58.42,59000.0,1,10049,20210622_Trocas8_675_Bay53_50%_DDA_120min.raw
4,VATVSLPR,30.28,841.5021,8,0.3,421.7585,57.79,15700000.0,1,9939,20210622_Trocas8_675_Bay53_50%_DDA_120min.raw

In [18]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaksdb675['A'] = peaksdb675['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaksdb675['C'] = peaksdb675['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaksdb675['D'] = peaksdb675['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaksdb675['E'] = peaksdb675['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaksdb675['F'] = peaksdb675['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaksdb675['G'] = peaksdb675['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaksdb675['H'] = peaksdb675['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaksdb675 output, there will be no isoleucines (they're lumped in with leucines)
peaksdb675['I'] = peaksdb675['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaksdb675['K'] = peaksdb675['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaksdb675['L'] = peaksdb675['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaksdb675['M'] = peaksdb675['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaksdb675['N'] = peaksdb675['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaksdb675['P'] = peaksdb675['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaksdb675['Q'] = peaksdb675['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaksdb675['R'] = peaksdb675['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaksdb675['S'] = peaksdb675['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaksdb675['T'] = peaksdb675['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaksdb675['V'] = peaksdb675['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaksdb675['W'] = peaksdb675['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaksdb675['Y'] = peaksdb675['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaksdb675['c-carb'] = peaksdb675['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaksdb675['m-oxid'] = peaksdb675['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaksdb675['n-deam'] = peaksdb675['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a lamba function to enumerate the # of deamidated Q's in each peptide
peaksdb675['q-deam'] = peaksdb675['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaksdb675['stripped_peptide'] = peaksdb675['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaksdb675['stripped_length'] = peaksdb675['stripped_peptide'].apply(len)

peaksdb675['NAAF_num.'] = peaksdb675['Area'] / peaksdb675['stripped_length']

# total the number of modifications in sequence
peaksdb675['ptm-total'] = peaksdb675['c-carb'] + peaksdb675['m-oxid'] + peaksdb675['n-deam'] + peaksdb675['q-deam']

# turn all isoleucines into leucines
# this helps later in comparing Unipept peptides to PeaksDB and Comet ones
peaksdb675['stripped_IL']= peaksdb675['stripped_peptide'].str.replace('I','L')

# write modified dataframe to new txt file
peaksdb675.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/675_BY_50_GF75_PDB/675_BY_50_GF75_PDB.csv")

# check out the results
peaksdb675.head()

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,...,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,NAAF_num.,ptm-total,stripped_IL
0,LSSPATLNSR,40.44,1044.5564,10,-0.6,523.2852,45.70,6190000.0,1,7681,...,0,0,0,0,0,LSSPATLNSR,10,6.190000e+05,0,LSSPATLNSR
1,LATVLSPR,34.23,855.5178,8,-0.3,428.7660,59.73,6900000.0,1,10285,...,0,0,0,0,0,LATVLSPR,8,8.625000e+05,0,LATVLSPR
2,LATVISPR,34.23,855.5178,8,-0.3,428.7660,59.73,6900000.0,1,10285,...,0,0,0,0,0,LATVISPR,8,8.625000e+05,0,LATVLSPR
3,SLVNLGGSK,33.44,873.4919,9,-0.4,437.7531,58.42,59000.0,1,10049,...,0,0,0,0,0,SLVNLGGSK,9,6.555556e+03,0,SLVNLGGSK
4,VATVSLPR,30.28,841.5021,8,0.3,421.7585,57.79,15700000.0,1,9939,...,0,0,0,0,0,VATVSLPR,8,1.962500e+06,0,VATVSLPR

In [19]:
# keep only stripped peptide I/L and NAAF
db_675 = peaksdb675[['stripped_IL', 'Area', 'NAAF_num.']]

db_675.set_index('stripped_IL')

# write modified dataframe to new txt file
db_675.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/I-L_NAAFs/675_BY_50_GF75_PDB_ILnaafs.csv")

db_675.head()

  stripped_IL        Area     NAAF_num.
0  LSSPATLNSR   6190000.0  6.190000e+05
1    LATVLSPR   6900000.0  8.625000e+05
2    LATVLSPR   6900000.0  8.625000e+05
3   SLVNLGGSK     59000.0  6.555556e+03
4    VATVSLPR  15700000.0  1.962500e+06

### Exporting txt files of stripped peptides at confidence cutoffs:

In [20]:
# keep only peptide column peptides <1% FDR (this is what we exported)
pep675moddup = peaksdb675[["Peptide"]]

# keep only the stripped peptide column <1% FDR
# this is what we'll use for UniPept input, etc
pep675dup = peaksdb675[["stripped_peptide"]]

# deduplicate both of these lists
pep675mod = pep675moddup.drop_duplicates()
pep675 = pep675dup.drop_duplicates()

# print out the #s of modified and stripped peptides, deduplicated and not

print("Total modified PeaksDB peptides in 675:", len(pep675moddup))
print("Deduplicated modified PeaksDB peptides in 675:", len(pep675mod))
print("Total stripped PeaksDB peptides in 675:", len(pep675dup))
print("Deduplicated stripped PeaksDB peptides in 675:", len(pep675))

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing
pep675.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/675_BY_50_GF75_PDB/675_BY_50_GF75_PDB_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/675_BY_50_GF75_PDB/675_BY_50_GF75_PDB_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/675_BY_50_GF75_PDB/675_BY_50_GF75_PDB_stripped_peptides.fas

# look at the stripped peptides
pep675.head()

Total modified PeaksDB peptides in 675: 51
Deduplicated modified PeaksDB peptides in 675: 51
Total stripped PeaksDB peptides in 675: 51
Deduplicated stripped PeaksDB peptides in 675: 51

  stripped_peptide
0       LSSPATLNSR
1         LATVLSPR
2         LATVISPR
3        SLVNLGGSK
4         VATVSLPR

## NAAF correction and exporting files with AA and PTM totals:

In [21]:
# made a new dataframe that contains the sums of certain columns in the modified
# peptide dataframe above 

index = ['sample total']

data = {'A': peaksdb675['A'].sum(),
        'C': peaksdb675['C'].sum(),
        'D': peaksdb675['D'].sum(),
        'E': peaksdb675['E'].sum(),
        'F': peaksdb675['F'].sum(),
        'G': peaksdb675['G'].sum(),
        'H': peaksdb675['H'].sum(),
        'I': peaksdb675['I'].sum(),
        'K': peaksdb675['K'].sum(),
        'L': peaksdb675['L'].sum(),
        'M': peaksdb675['M'].sum(),
        'N': peaksdb675['N'].sum(),
        'P': peaksdb675['P'].sum(),
        'Q': peaksdb675['Q'].sum(),
        'R': peaksdb675['R'].sum(),
        'S': peaksdb675['S'].sum(),
        'T': peaksdb675['T'].sum(),
        'V': peaksdb675['V'].sum(),
        'W': peaksdb675['W'].sum(),
        'Y': peaksdb675['Y'].sum(),
        'c-carb': peaksdb675['c-carb'].sum(),
        'm-oxid': peaksdb675['m-oxid'].sum(),
        'n-deam': peaksdb675['n-deam'].sum(),
        'q-deam': peaksdb675['q-deam'].sum(),
        'Total area': peaksdb675['Area'].sum(),
        'Total length': peaksdb675['stripped_length'].sum()
       }

totalpeaksdb675 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                              'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                              'c-carb', 'm-oxid', 
                                              'n-deam', 'q-deam', 'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaksdb675['% C w/ carb'] = totalpeaksdb675['c-carb'] / totalpeaksdb675['C'] 

# calculate percentage of M's that are oxidized
totalpeaksdb675['% M w/ oxid'] = totalpeaksdb675['m-oxid'] / totalpeaksdb675['M'] 

# calculate percentage of N's that are deamidated
totalpeaksdb675['% N w/ deam'] = totalpeaksdb675['n-deam'] / totalpeaksdb675['N'] 

# calculate percentage of N's that are deamidated
totalpeaksdb675['% Q w/ deam'] = totalpeaksdb675['q-deam'] / totalpeaksdb675['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaksdb675['NAAF denom.'] = totalpeaksdb675['Total area'] / totalpeaksdb675['Total length']

# write modified dataframe to new txt file
totalpeaksdb675.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/675_BY_50_GF75_PDB/675_BY_50_GF75_PDB_totals.csv")

totalpeaksdb675.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,50,1,16,24,11,40,8,36,37,74,...,2,2,4,73143990.0,542,1.0,0.2,0.153846,0.210526,134952.01107

In [22]:
# use the calculated NAAF factor (in totalpeaksdb675 dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

NAAF20 = 134952.01107

# we'll use -10lgP > 20 as an approximate cutoff for the <1.0% FDR which is what we actually have
peaksdb675['NAAF factor'] = (peaksdb675['NAAF_num.'])/NAAF20

# make a dataframe that contains only what we need: sequences, AAs, PTMs
peaksdb675_NAAF = peaksdb675[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', \
                              'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                              'c-carb', 'm-oxid', 'n-deam', 'q-deam']].copy()

# multiply the NAAF20 factor by the AAs to normalize its abundance by peak area and peptide length

peaksdb675_NAAF['A-NAAF20'] = peaksdb675_NAAF['A'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['C-NAAF20'] = peaksdb675_NAAF['C'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['D-NAAF20'] = peaksdb675_NAAF['D'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['E-NAAF20'] = peaksdb675_NAAF['E'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['F-NAAF20'] = peaksdb675_NAAF['F'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['G-NAAF20'] = peaksdb675_NAAF['G'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['H-NAAF20'] = peaksdb675_NAAF['H'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['I-NAAF20'] = peaksdb675_NAAF['I'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['K-NAAF20'] = peaksdb675_NAAF['K'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['L-NAAF20'] = peaksdb675_NAAF['L'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['M-NAAF20'] = peaksdb675_NAAF['M'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['N-NAAF20'] = peaksdb675_NAAF['N'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['P-NAAF20'] = peaksdb675_NAAF['P'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['Q-NAAF20'] = peaksdb675_NAAF['Q'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['R-NAAF20'] = peaksdb675_NAAF['R'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['S-NAAF20'] = peaksdb675_NAAF['S'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['T-NAAF20'] = peaksdb675_NAAF['T'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['V-NAAF20'] = peaksdb675_NAAF['V'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['W-NAAF20'] = peaksdb675_NAAF['W'] * peaksdb675['NAAF factor']
peaksdb675_NAAF['Y-NAAF20'] = peaksdb675_NAAF['Y'] * peaksdb675['NAAF factor']

# multiply the NAAF20 factor by the PTMs normalize its abundance by peak area and peptide length

peaksdb675_NAAF['ccarb-NAAF20'] = peaksdb675_NAAF['c-carb'] * peaksdb675_NAAF['NAAF factor']
peaksdb675_NAAF['moxid-NAAF20'] = peaksdb675_NAAF['m-oxid'] * peaksdb675_NAAF['NAAF factor']
peaksdb675_NAAF['ndeam-NAAF20'] = peaksdb675_NAAF['n-deam'] * peaksdb675_NAAF['NAAF factor']
peaksdb675_NAAF['qdeam-NAAF20'] = peaksdb675_NAAF['q-deam'] * peaksdb675_NAAF['NAAF factor']


# write the dataframe to a new csv
peaksdb675_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/675_BY_50_GF75_PDB/675_BY_50_GF75_PDB_naaf.csv")

peaksdb675_NAAF.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,I,...,R-NAAF20,S-NAAF20,T-NAAF20,V-NAAF20,W-NAAF20,Y-NAAF20,ccarb-NAAF20,moxid-NAAF20,ndeam-NAAF20,qdeam-NAAF20
0,LSSPATLNSR,4.586816,1,0,0,0,0,0,0,0,...,4.586816,13.760447,4.586816,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,LATVLSPR,6.391161,1,0,0,0,0,0,0,0,...,6.391161,6.391161,6.391161,6.391161,0.0,0.0,0.0,0.0,0.0,0.0
2,LATVISPR,6.391161,1,0,0,0,0,0,0,1,...,6.391161,6.391161,6.391161,6.391161,0.0,0.0,0.0,0.0,0.0,0.0
3,SLVNLGGSK,0.048577,0,0,0,0,0,2,0,0,...,0.000000,0.097154,0.000000,0.048577,0.0,0.0,0.0,0.0,0.0,0.0
4,VATVSLPR,14.542206,1,0,0,0,0,0,0,0,...,14.542206,14.542206,14.542206,29.084413,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
# made a new dataframe that contains the sums of NAAF normalized AAs for peaksdb675 peaksdb results
# also contains the sums of the NAAF-corrected PTMs occurances for each affected residue

index = ['sample total']

data = {'NAAF': peaksdb675_NAAF['NAAF factor'].sum(),
        'A': peaksdb675_NAAF['A-NAAF20'].sum(),
        'C': peaksdb675_NAAF['C-NAAF20'].sum(),
        'D': peaksdb675_NAAF['D-NAAF20'].sum(),
        'E': peaksdb675_NAAF['E-NAAF20'].sum(),
        'F': peaksdb675_NAAF['F-NAAF20'].sum(),
        'G': peaksdb675_NAAF['G-NAAF20'].sum(),
        'H': peaksdb675_NAAF['H-NAAF20'].sum(),
        'I': peaksdb675_NAAF['I-NAAF20'].sum(),
        'K': peaksdb675_NAAF['K-NAAF20'].sum(),
        'L': peaksdb675_NAAF['L-NAAF20'].sum(),
        'M': peaksdb675_NAAF['M-NAAF20'].sum(),
        'N': peaksdb675_NAAF['N-NAAF20'].sum(),
        'P': peaksdb675_NAAF['P-NAAF20'].sum(),
        'Q': peaksdb675_NAAF['Q-NAAF20'].sum(),
        'R': peaksdb675_NAAF['R-NAAF20'].sum(),
        'S': peaksdb675_NAAF['S-NAAF20'].sum(),
        'T': peaksdb675_NAAF['T-NAAF20'].sum(),
        'V': peaksdb675_NAAF['V-NAAF20'].sum(),
        'W': peaksdb675_NAAF['W-NAAF20'].sum(),
        'Y': peaksdb675_NAAF['Y-NAAF20'].sum(),
        'c-carb': peaksdb675_NAAF['ccarb-NAAF20'].sum(),
        'm-oxid': peaksdb675_NAAF['moxid-NAAF20'].sum(),
        'n-deam': peaksdb675_NAAF['ndeam-NAAF20'].sum(),
        'q-deam': peaksdb675_NAAF['qdeam-NAAF20'].sum()
       }

totalpeaksdb675_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', \
                                                   'G', 'H', 'I','K', 'L', 'M', \
                                                   'N', 'P', 'Q', 'R', 'S', \
                                                   'T', 'V', 'W', 'Y', 'c-carb', \
                                                   'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate the NAAF-corrected % modified C, M, N, Q, K, and Rs


# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaksdb675_NAAF['% C w/ carb.'] = totalpeaksdb675_NAAF['c-carb'] / totalpeaksdb675_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaksdb675_NAAF['% M w/ oxid'] = totalpeaksdb675_NAAF['m-oxid'] / totalpeaksdb675_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb675_NAAF['% N w/ deam'] = totalpeaksdb675_NAAF['n-deam'] / totalpeaksdb675_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb675_NAAF['% Q w/ deam'] = totalpeaksdb675_NAAF['q-deam'] / totalpeaksdb675_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaksdb675_NAAF['NAAF check'] = totalpeaksdb675_NAAF['NAAF'] / 134952.01107

# write modified dataframe to new txt file, same name + totals
totalpeaksdb675_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/675_BY_50_GF75_PDB/675_BY_50_GF75_PDB_naaf_totals.csv")

totalpeaksdb675_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,66.698387,32.561091,0.0,0.159777,0.235664,0.231384,0.806591,0.109651,27.744278,0.577774,...,0.309042,0.0,0.015232,0.002272,0.004446,NaN,0.427486,0.000473,0.017531,0.000494