### Manipulation of PeaskDB de novo-assisted database search results of Trocas 8 (low water, November 2019) non incubation samples LC-MS/MS data using python.

Starting with:

    PeaksDB search results (.csv) of PTM-optimized database searches
    These were all searched with 15 ppm precursor tolerance and 0.5 ppm fragement ion tolerance
    Exported at <1.0% FDR
    
Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use for a different file:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 675) for another
#### 3. Update the NAAF factor calculated in *IN 6* into *IN 7*

In [1]:
cd /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/678_Trocas8_June2021_PEAKS_139/

/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/678_Trocas8_June2021_PEAKS_139

In [2]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [3]:
ls

 678_Trocas8_June2021_PEAKS_139_peptide.csv     'de novo only peptides.csv'
 678_Trocas8_June2021_PEAKS_139_proteins.csv     peptides_1_1_0.mzid
 678_Trocas8_June2021_PEAKS_139_proteins.fasta   protein-peptides.csv
'DB search psm.csv'

In [4]:
# read the CSV into a dataframe using the pandas read_csv function
peaksdbdup678 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/678_Trocas8_June2021_PEAKS_139/678_Trocas8_June2021_PEAKS_139_peptide.csv")

# remove redundant rows
peaksdb678 = pd.DataFrame.drop_duplicates(peaksdbdup678)

print(peaksdb678.columns)

columns = ['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area', 'Fraction', 'Scan', 'Source_File',
       '#Spec', '#Spec', 'Accession', 'PTM',
       'AScore']

peaksdb678.columns = columns

#remmove # spec and accession columns because they mess parsing up

del peaksdb678['#Spec']
del peaksdb678['Accession']
del peaksdb678['PTM']
del peaksdb678['AScore']

mean_length = peaksdb678['Length'].mean()
print(mean_length)

print("# redundant peaksdb peptides in combined dataframe", len(peaksdbdup678))
print("# nonredundant peaksdb peptides in combined dataframe", len(peaksdb678))

#look at the dataframe
peaksdb678.head()

Index(['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area Sample 4', 'Fraction', 'Scan', 'Source File', '#Spec',
       '#Spec Sample 4', 'Accession', 'PTM', 'AScore'],
      dtype='object')
10.11111111111111
# redundant peaksdb peptides in combined dataframe 36
# nonredundant peaksdb peptides in combined dataframe 36

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,Source_File
0,LSSPATLNSR,41.34,1044.5564,10,-2.1,523.2844,51.40,8990000.0,4,8821,20210623_Trocas8_678_Chaves60_surface_DDA_120m...
1,LATVISPR,34.23,855.5178,8,-1.3,428.7656,67.82,3390000.0,4,11507,20210623_Trocas8_678_Chaves60_surface_DDA_120m...
2,LATVLSPR,34.23,855.5178,8,-1.3,428.7656,67.82,3390000.0,4,11507,20210623_Trocas8_678_Chaves60_surface_DDA_120m...
3,SC(+57.02)AAAGTEC(+57.02)L,30.92,1038.4110,10,-0.6,520.2125,49.03,106000.0,4,8351,20210623_Trocas8_678_Chaves60_surface_DDA_120m...
4,SC(+57.02)AAAGTEC(+57.02)LISGWGN,29.70,1652.6923,16,-1.0,827.3525,95.84,124000.0,4,15785,20210623_Trocas8_678_Chaves60_surface_DDA_120m...

In [6]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaksdb678['A'] = peaksdb678['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaksdb678['C'] = peaksdb678['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaksdb678['D'] = peaksdb678['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaksdb678['E'] = peaksdb678['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaksdb678['F'] = peaksdb678['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaksdb678['G'] = peaksdb678['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaksdb678['H'] = peaksdb678['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaksdb678 output, there will be no isoleucines (they're lumped in with leucines)
peaksdb678['I'] = peaksdb678['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaksdb678['K'] = peaksdb678['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaksdb678['L'] = peaksdb678['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaksdb678['M'] = peaksdb678['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaksdb678['N'] = peaksdb678['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaksdb678['P'] = peaksdb678['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaksdb678['Q'] = peaksdb678['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaksdb678['R'] = peaksdb678['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaksdb678['S'] = peaksdb678['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaksdb678['T'] = peaksdb678['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaksdb678['V'] = peaksdb678['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaksdb678['W'] = peaksdb678['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaksdb678['Y'] = peaksdb678['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaksdb678['c-carb'] = peaksdb678['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaksdb678['m-oxid'] = peaksdb678['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaksdb678['n-deam'] = peaksdb678['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a lamba function to enumerate the # of deamidated Q's in each peptide
peaksdb678['q-deam'] = peaksdb678['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaksdb678['stripped_peptide'] = peaksdb678['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaksdb678['stripped_length'] = peaksdb678['stripped_peptide'].apply(len)

peaksdb678['NAAF_num.'] = peaksdb678['Area'] / peaksdb678['stripped_length']

# total the number of modifications in sequence
peaksdb678['ptm-total'] = peaksdb678['c-carb'] + peaksdb678['m-oxid'] + peaksdb678['n-deam'] + peaksdb678['q-deam']

# turn all isoleucines into leucines
# this helps later in comparing Unipept peptides to PeaksDB and Comet ones
peaksdb678['stripped_IL']= peaksdb678['stripped_peptide'].str.replace('I','L')

# write modified dataframe to new txt file
peaksdb678.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/678_CV_surf_GF75_PDB/678_CV_surf_GF75_PDB.csv")

# check out the results
peaksdb678.head()

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,...,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,NAAF_num.,ptm-total,stripped_IL
0,LSSPATLNSR,41.34,1044.5564,10,-2.1,523.2844,51.40,8990000.0,4,8821,...,0,0,0,0,0,LSSPATLNSR,10,899000.000000,0,LSSPATLNSR
1,LATVISPR,34.23,855.5178,8,-1.3,428.7656,67.82,3390000.0,4,11507,...,0,0,0,0,0,LATVISPR,8,423750.000000,0,LATVLSPR
2,LATVLSPR,34.23,855.5178,8,-1.3,428.7656,67.82,3390000.0,4,11507,...,0,0,0,0,0,LATVLSPR,8,423750.000000,0,LATVLSPR
3,SC(+57.02)AAAGTEC(+57.02)L,30.92,1038.4110,10,-0.6,520.2125,49.03,106000.0,4,8351,...,0,2,0,0,0,SCL,3,35333.333333,2,SCL
4,SC(+57.02)AAAGTEC(+57.02)LISGWGN,29.70,1652.6923,16,-1.0,827.3525,95.84,124000.0,4,15785,...,0,2,0,0,0,SCLISGWGN,9,13777.777778,2,SCLLSGWGN

In [7]:
# keep only stripped peptide I/L and NAAF
db_678 = peaksdb678[['stripped_IL', 'Area', 'NAAF_num.']]

db_678.set_index('stripped_IL')

# write modified dataframe to new txt file
db_678.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/I-L_NAAFs/678_CV_surf_GF75_PDB_ILnaafs.csv")

db_678.head()

  stripped_IL       Area      NAAF_num.
0  LSSPATLNSR  8990000.0  899000.000000
1    LATVLSPR  3390000.0  423750.000000
2    LATVLSPR  3390000.0  423750.000000
3         SCL   106000.0   35333.333333
4   SCLLSGWGN   124000.0   13777.777778

### Exporting txt files of stripped peptides at confidence cutoffs:

In [8]:
# keep only peptide column peptides <1% FDR (this is what we exported)
pep678moddup = peaksdb678[["Peptide"]]

# keep only the stripped peptide column <1% FDR
# this is what we'll use for UniPept input, etc
pep678dup = peaksdb678[["stripped_peptide"]]

# deduplicate both of these lists
pep678mod = pep678moddup.drop_duplicates()
pep678 = pep678dup.drop_duplicates()

# print out the #s of modified and stripped peptides, deduplicated and not

print("Total modified PeaksDB peptides in 678:", len(pep678moddup))
print("Deduplicated modified PeaksDB peptides in 678:", len(pep678mod))
print("Total stripped PeaksDB peptides in 678:", len(pep678dup))
print("Deduplicated stripped PeaksDB peptides in 678:", len(pep678))

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing
pep678.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/678_CV_surf_GF75_PDB/678_CV_surf_GF75_PDB_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/678_CV_surf_GF75_PDB/678_CV_surf_GF75_PDB_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/678_CV_surf_GF75_PDB/678_CV_surf_GF75_PDB_stripped_peptides.fas

# look at the stripped peptides
pep678.head()

Total modified PeaksDB peptides in 678: 36
Deduplicated modified PeaksDB peptides in 678: 36
Total stripped PeaksDB peptides in 678: 36
Deduplicated stripped PeaksDB peptides in 678: 36

  stripped_peptide
0       LSSPATLNSR
1         LATVISPR
2         LATVLSPR
3              SCL
4        SCLISGWGN

## NAAF correction and exporting files with AA and PTM totals:

In [9]:
# made a new dataframe that contains the sums of certain columns in the modified
# peptide dataframe above 

index = ['sample total']

data = {'A': peaksdb678['A'].sum(),
        'C': peaksdb678['C'].sum(),
        'D': peaksdb678['D'].sum(),
        'E': peaksdb678['E'].sum(),
        'F': peaksdb678['F'].sum(),
        'G': peaksdb678['G'].sum(),
        'H': peaksdb678['H'].sum(),
        'I': peaksdb678['I'].sum(),
        'K': peaksdb678['K'].sum(),
        'L': peaksdb678['L'].sum(),
        'M': peaksdb678['M'].sum(),
        'N': peaksdb678['N'].sum(),
        'P': peaksdb678['P'].sum(),
        'Q': peaksdb678['Q'].sum(),
        'R': peaksdb678['R'].sum(),
        'S': peaksdb678['S'].sum(),
        'T': peaksdb678['T'].sum(),
        'V': peaksdb678['V'].sum(),
        'W': peaksdb678['W'].sum(),
        'Y': peaksdb678['Y'].sum(),
        'c-carb': peaksdb678['c-carb'].sum(),
        'm-oxid': peaksdb678['m-oxid'].sum(),
        'n-deam': peaksdb678['n-deam'].sum(),
        'q-deam': peaksdb678['q-deam'].sum(),
        'Total area': peaksdb678['Area'].sum(),
        'Total length': peaksdb678['stripped_length'].sum()
       }

totalpeaksdb678 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                              'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                              'c-carb', 'm-oxid', 
                                              'n-deam', 'q-deam', 'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaksdb678['% C w/ carb'] = totalpeaksdb678['c-carb'] / totalpeaksdb678['C'] 

# calculate percentage of M's that are oxidized
totalpeaksdb678['% M w/ oxid'] = totalpeaksdb678['m-oxid'] / totalpeaksdb678['M'] 

# calculate percentage of N's that are deamidated
totalpeaksdb678['% N w/ deam'] = totalpeaksdb678['n-deam'] / totalpeaksdb678['N'] 

# calculate percentage of N's that are deamidated
totalpeaksdb678['% Q w/ deam'] = totalpeaksdb678['q-deam'] / totalpeaksdb678['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaksdb678['NAAF denom.'] = totalpeaksdb678['Total area'] / totalpeaksdb678['Total length']

# write modified dataframe to new txt file
totalpeaksdb678.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/678_CV_surf_GF75_PDB/678_CV_surf_GF75_PDB_totals.csv")

totalpeaksdb678.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,34,6,7,11,4,26,9,24,19,44,...,1,2,1,34632636.0,333,1.0,0.25,0.4,0.111111,104001.90991

In [10]:
# use the calculated NAAF factor (in totalpeaksdb678 dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

NAAF20 = 104001.90991

# we'll use -10lgP > 20 as an approximate cutoff for the <1.0% FDR which is what we actually have
peaksdb678['NAAF factor'] = (peaksdb678['NAAF_num.'])/NAAF20

# make a dataframe that contains only what we need: sequences, AAs, PTMs
peaksdb678_NAAF = peaksdb678[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', \
                              'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                              'c-carb', 'm-oxid', 'n-deam', 'q-deam']].copy()

# multiply the NAAF20 factor CV the AAs to normalize its abundance CV peak area and peptide length

peaksdb678_NAAF['A-NAAF20'] = peaksdb678_NAAF['A'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['C-NAAF20'] = peaksdb678_NAAF['C'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['D-NAAF20'] = peaksdb678_NAAF['D'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['E-NAAF20'] = peaksdb678_NAAF['E'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['F-NAAF20'] = peaksdb678_NAAF['F'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['G-NAAF20'] = peaksdb678_NAAF['G'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['H-NAAF20'] = peaksdb678_NAAF['H'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['I-NAAF20'] = peaksdb678_NAAF['I'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['K-NAAF20'] = peaksdb678_NAAF['K'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['L-NAAF20'] = peaksdb678_NAAF['L'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['M-NAAF20'] = peaksdb678_NAAF['M'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['N-NAAF20'] = peaksdb678_NAAF['N'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['P-NAAF20'] = peaksdb678_NAAF['P'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['Q-NAAF20'] = peaksdb678_NAAF['Q'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['R-NAAF20'] = peaksdb678_NAAF['R'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['S-NAAF20'] = peaksdb678_NAAF['S'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['T-NAAF20'] = peaksdb678_NAAF['T'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['V-NAAF20'] = peaksdb678_NAAF['V'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['W-NAAF20'] = peaksdb678_NAAF['W'] * peaksdb678['NAAF factor']
peaksdb678_NAAF['Y-NAAF20'] = peaksdb678_NAAF['Y'] * peaksdb678['NAAF factor']

# multiply the NAAF20 factor CV the PTMs normalize its abundance CV peak area and peptide length

peaksdb678_NAAF['ccarb-NAAF20'] = peaksdb678_NAAF['c-carb'] * peaksdb678_NAAF['NAAF factor']
peaksdb678_NAAF['moxid-NAAF20'] = peaksdb678_NAAF['m-oxid'] * peaksdb678_NAAF['NAAF factor']
peaksdb678_NAAF['ndeam-NAAF20'] = peaksdb678_NAAF['n-deam'] * peaksdb678_NAAF['NAAF factor']
peaksdb678_NAAF['qdeam-NAAF20'] = peaksdb678_NAAF['q-deam'] * peaksdb678_NAAF['NAAF factor']


# write the dataframe to a new csv
peaksdb678_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/678_CV_surf_GF75_PDB/678_CV_surf_GF75_PDB_naaf.csv")

peaksdb678_NAAF.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,I,...,R-NAAF20,S-NAAF20,T-NAAF20,V-NAAF20,W-NAAF20,Y-NAAF20,ccarb-NAAF20,moxid-NAAF20,ndeam-NAAF20,qdeam-NAAF20
0,LSSPATLNSR,8.644072,1,0,0,0,0,0,0,0,...,8.644072,25.932216,8.644072,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
1,LATVISPR,4.074444,1,0,0,0,0,0,0,1,...,4.074444,4.074444,4.074444,4.074444,0.000000,0.0,0.000000,0.0,0.0,0.0
2,LATVLSPR,4.074444,1,0,0,0,0,0,0,0,...,4.074444,4.074444,4.074444,4.074444,0.000000,0.0,0.000000,0.0,0.0,0.0
3,SCL,0.339737,3,2,0,1,0,1,0,0,...,0.000000,0.339737,0.339737,0.000000,0.000000,0.0,0.679475,0.0,0.0,0.0
4,SCLISGWGN,0.132476,3,2,0,1,0,3,0,1,...,0.000000,0.264952,0.132476,0.000000,0.132476,0.0,0.264952,0.0,0.0,0.0

In [11]:
# made a new dataframe that contains the sums of NAAF normalized AAs for peaksdb678 peaksdb results
# also contains the sums of the NAAF-corrected PTMs occurances for each affected residue

index = ['sample total']

data = {'NAAF': peaksdb678_NAAF['NAAF factor'].sum(),
        'A': peaksdb678_NAAF['A-NAAF20'].sum(),
        'C': peaksdb678_NAAF['C-NAAF20'].sum(),
        'D': peaksdb678_NAAF['D-NAAF20'].sum(),
        'E': peaksdb678_NAAF['E-NAAF20'].sum(),
        'F': peaksdb678_NAAF['F-NAAF20'].sum(),
        'G': peaksdb678_NAAF['G-NAAF20'].sum(),
        'H': peaksdb678_NAAF['H-NAAF20'].sum(),
        'I': peaksdb678_NAAF['I-NAAF20'].sum(),
        'K': peaksdb678_NAAF['K-NAAF20'].sum(),
        'L': peaksdb678_NAAF['L-NAAF20'].sum(),
        'M': peaksdb678_NAAF['M-NAAF20'].sum(),
        'N': peaksdb678_NAAF['N-NAAF20'].sum(),
        'P': peaksdb678_NAAF['P-NAAF20'].sum(),
        'Q': peaksdb678_NAAF['Q-NAAF20'].sum(),
        'R': peaksdb678_NAAF['R-NAAF20'].sum(),
        'S': peaksdb678_NAAF['S-NAAF20'].sum(),
        'T': peaksdb678_NAAF['T-NAAF20'].sum(),
        'V': peaksdb678_NAAF['V-NAAF20'].sum(),
        'W': peaksdb678_NAAF['W-NAAF20'].sum(),
        'Y': peaksdb678_NAAF['Y-NAAF20'].sum(),
        'c-carb': peaksdb678_NAAF['ccarb-NAAF20'].sum(),
        'm-oxid': peaksdb678_NAAF['moxid-NAAF20'].sum(),
        'n-deam': peaksdb678_NAAF['ndeam-NAAF20'].sum(),
        'q-deam': peaksdb678_NAAF['qdeam-NAAF20'].sum()
       }

totalpeaksdb678_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', \
                                                   'G', 'H', 'I','K', 'L', 'M', \
                                                   'N', 'P', 'Q', 'R', 'S', \
                                                   'T', 'V', 'W', 'Y', 'c-carb', \
                                                   'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate the NAAF-corrected % modified C, M, N, Q, K, and Rs


# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaksdb678_NAAF['% C w/ carb.'] = totalpeaksdb678_NAAF['c-carb'] / totalpeaksdb678_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaksdb678_NAAF['% M w/ oxid'] = totalpeaksdb678_NAAF['m-oxid'] / totalpeaksdb678_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb678_NAAF['% N w/ deam'] = totalpeaksdb678_NAAF['n-deam'] / totalpeaksdb678_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb678_NAAF['% Q w/ deam'] = totalpeaksdb678_NAAF['q-deam'] / totalpeaksdb678_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaksdb678_NAAF['NAAF check'] = totalpeaksdb678_NAAF['NAAF'] / 104001.90991

# write modified dataframe to new txt file, same name + totals
totalpeaksdb678_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/678_CV_surf_GF75_PDB/678_CV_surf_GF75_PDB_naaf_totals.csv")

totalpeaksdb678_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,39.566247,29.644122,0.98436,0.116211,0.52574,0.078584,2.565498,0.393715,12.830313,0.291268,...,0.705041,0.98436,0.003101,0.006202,0.000751,1.0,0.027489,0.000706,0.003722,0.00038