### Manipulation of PeaskDB de novo-assisted database search results of Trocas 8 (low water, November 2019) non incubation samples LC-MS/MS data using python.

Starting with:

    PeaksDB search results (.csv) of PTM-optimized database searches
    These were all searched with 15 ppm precursor tolerance and 0.5 ppm fragement ion tolerance
    Exported at <1.0% FDR
    
Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use for a different file:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 675) for another
#### 3. Update the NAAF factor calculated in *IN 6* into *IN 7*

In [3]:
cd /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/679_Trocas8_June2021_PEAKS_137/

/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/679_Trocas8_June2021_PEAKS_137

In [4]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [5]:
ls

 679_Trocas8_June2021_PEAKS_137_peptide.csv     'de novo only peptides.csv'
 679_Trocas8_June2021_PEAKS_137_proteins.csv     peptides_1_1_0.mzid
 679_Trocas8_June2021_PEAKS_137_proteins.fasta   protein-peptides.csv
'DB search psm.csv'

In [6]:
# read the CSV into a dataframe using the pandas read_csv function
peaksdbdup679 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/679_Trocas8_June2021_PEAKS_137/679_Trocas8_June2021_PEAKS_137_peptide.csv")

# remove redundant rows
peaksdb679 = pd.DataFrame.drop_duplicates(peaksdbdup679)

print(peaksdb679.columns)

columns = ['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area', 'Fraction', 'Scan', 'Source_File',
       '#Spec', '#Spec', 'Accession', 'PTM',
       'AScore']

peaksdb679.columns = columns

#remmove # spec and accession columns because they mess parsing up

del peaksdb679['#Spec']
del peaksdb679['Accession']
del peaksdb679['PTM']
del peaksdb679['AScore']

mean_length = peaksdb679['Length'].mean()
print(mean_length)

print("# redundant peaksdb peptides in combined dataframe", len(peaksdbdup679))
print("# nonredundant peaksdb peptides in combined dataframe", len(peaksdb679))

#look at the dataframe
peaksdb679.head()

Index(['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area Sample 5', 'Fraction', 'Scan', 'Source File', '#Spec',
       '#Spec Sample 5', 'Accession', 'PTM', 'AScore'],
      dtype='object')
9.392857142857142
# redundant peaksdb peptides in combined dataframe 56
# nonredundant peaksdb peptides in combined dataframe 56

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,Source_File
0,VLEGNEQFINAAK,42.56,1431.7357,13,-1.0,716.8744,67.68,65300.0,5,10393,20210623_Trocas8_679_SMCP65_50%_DDA_120min.raw
1,LSSPATLNSR,41.01,1044.5564,10,0.3,523.2856,44.06,6660000.0,5,6655,20210623_Trocas8_679_SMCP65_50%_DDA_120min.raw
2,YYTLEEIQK,40.04,1185.5917,9,-0.6,593.8027,72.48,32500.0,5,11097,20210623_Trocas8_679_SMCP65_50%_DDA_120min.raw
3,LSSPATLN(+.98)SR,38.37,1045.5404,10,0.8,523.7779,46.68,86100.0,5,7215,20210623_Trocas8_679_SMCP65_50%_DDA_120min.raw
4,STSSFSC(+57.02)LSR,33.10,1130.5026,10,0.0,566.2585,52.59,26400.0,5,8134,20210623_Trocas8_679_SMCP65_50%_DDA_120min.raw

In [8]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaksdb679['A'] = peaksdb679['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaksdb679['C'] = peaksdb679['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaksdb679['D'] = peaksdb679['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaksdb679['E'] = peaksdb679['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaksdb679['F'] = peaksdb679['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaksdb679['G'] = peaksdb679['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaksdb679['H'] = peaksdb679['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaksdb679 output, there will be no isoleucines (they're lumped in with leucines)
peaksdb679['I'] = peaksdb679['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaksdb679['K'] = peaksdb679['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaksdb679['L'] = peaksdb679['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaksdb679['M'] = peaksdb679['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaksdb679['N'] = peaksdb679['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaksdb679['P'] = peaksdb679['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaksdb679['Q'] = peaksdb679['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaksdb679['R'] = peaksdb679['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaksdb679['S'] = peaksdb679['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaksdb679['T'] = peaksdb679['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaksdb679['V'] = peaksdb679['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaksdb679['W'] = peaksdb679['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaksdb679['Y'] = peaksdb679['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaksdb679['c-carb'] = peaksdb679['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaksdb679['m-oxid'] = peaksdb679['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaksdb679['n-deam'] = peaksdb679['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a lamba function to enumerate the # of deamidated Q's in each peptide
peaksdb679['q-deam'] = peaksdb679['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaksdb679['stripped_peptide'] = peaksdb679['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaksdb679['stripped_length'] = peaksdb679['stripped_peptide'].apply(len)

peaksdb679['NAAF_num.'] = peaksdb679['Area'] / peaksdb679['stripped_length']

# total the number of modifications in sequence
peaksdb679['ptm-total'] = peaksdb679['c-carb'] + peaksdb679['m-oxid'] + peaksdb679['n-deam'] + peaksdb679['q-deam']

# turn all isoleucines into leucines
# this helps later in comparing Unipept peptides to PeaksDB and Comet ones
peaksdb679['stripped_IL']= peaksdb679['stripped_peptide'].str.replace('I','L')

# write modified dataframe to new txt file
peaksdb679.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/679_SMCP_50_GF75_PDB/679_SMCP_50_GF75_PDB.csv")

# check out the results
peaksdb679.head()

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,...,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,NAAF_num.,ptm-total,stripped_IL
0,VLEGNEQFINAAK,42.56,1431.7357,13,-1.0,716.8744,67.68,65300.0,5,10393,...,0,0,0,0,0,VLEGNEQFINAAK,13,5023.076923,0,VLEGNEQFLNAAK
1,LSSPATLNSR,41.01,1044.5564,10,0.3,523.2856,44.06,6660000.0,5,6655,...,0,0,0,0,0,LSSPATLNSR,10,666000.000000,0,LSSPATLNSR
2,YYTLEEIQK,40.04,1185.5917,9,-0.6,593.8027,72.48,32500.0,5,11097,...,2,0,0,0,0,YYTLEEIQK,9,3611.111111,0,YYTLEELQK
3,LSSPATLN(+.98)SR,38.37,1045.5404,10,0.8,523.7779,46.68,86100.0,5,7215,...,0,0,0,1,0,LSSPATLNSR,10,8610.000000,1,LSSPATLNSR
4,STSSFSC(+57.02)LSR,33.10,1130.5026,10,0.0,566.2585,52.59,26400.0,5,8134,...,0,1,0,0,0,STSSFSCLSR,10,2640.000000,1,STSSFSCLSR

In [9]:
# keep only stripped peptide I/L and NAAF
db_679 = peaksdb679[['stripped_IL', 'Area', 'NAAF_num.']]

db_679.set_index('stripped_IL')

# write modified dataframe to new txt file
db_679.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/I-L_NAAFs/679_SMCP_50_GF75_PDB_ILnaafs.csv")

db_679.head()

     stripped_IL       Area      NAAF_num.
0  VLEGNEQFLNAAK    65300.0    5023.076923
1     LSSPATLNSR  6660000.0  666000.000000
2      YYTLEELQK    32500.0    3611.111111
3     LSSPATLNSR    86100.0    8610.000000
4     STSSFSCLSR    26400.0    2640.000000

### Exporting txt files of stripped peptides at confidence cutoffs:

In [10]:
# keep only peptide column peptides <1% FDR (this is what we exported)
pep679moddup = peaksdb679[["Peptide"]]

# keep only the stripped peptide column <1% FDR
# this is what we'll use for UniPept input, etc
pep679dup = peaksdb679[["stripped_peptide"]]

# deduplicate both of these lists
pep679mod = pep679moddup.drop_duplicates()
pep679 = pep679dup.drop_duplicates()

# print out the #s of modified and stripped peptides, deduplicated and not

print("Total modified PeaksDB peptides in 679:", len(pep679moddup))
print("Deduplicated modified PeaksDB peptides in 679:", len(pep679mod))
print("Total stripped PeaksDB peptides in 679:", len(pep679dup))
print("Deduplicated stripped PeaksDB peptides in 679:", len(pep679))

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing
pep679.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/679_SMCP_50_GF75_PDB/679_SMCP_50_GF75_PDB_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/679_SMCP_50_GF75_PDB/679_SMCP_50_GF75_PDB_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/679_SMCP_50_GF75_PDB/679_SMCP_50_GF75_PDB_stripped_peptides.fas

# look at the stripped peptides
pep679.head()

Total modified PeaksDB peptides in 679: 56
Deduplicated modified PeaksDB peptides in 679: 56
Total stripped PeaksDB peptides in 679: 56
Deduplicated stripped PeaksDB peptides in 679: 55

  stripped_peptide
0    VLEGNEQFINAAK
1       LSSPATLNSR
2        YYTLEEIQK
4       STSSFSCLSR
5         LATVLSPR

## NAAF correction and exporting files with AA and PTM totals:

In [11]:
# made a new dataframe that contains the sums of certain columns in the modified
# peptide dataframe above 

index = ['sample total']

data = {'A': peaksdb679['A'].sum(),
        'C': peaksdb679['C'].sum(),
        'D': peaksdb679['D'].sum(),
        'E': peaksdb679['E'].sum(),
        'F': peaksdb679['F'].sum(),
        'G': peaksdb679['G'].sum(),
        'H': peaksdb679['H'].sum(),
        'I': peaksdb679['I'].sum(),
        'K': peaksdb679['K'].sum(),
        'L': peaksdb679['L'].sum(),
        'M': peaksdb679['M'].sum(),
        'N': peaksdb679['N'].sum(),
        'P': peaksdb679['P'].sum(),
        'Q': peaksdb679['Q'].sum(),
        'R': peaksdb679['R'].sum(),
        'S': peaksdb679['S'].sum(),
        'T': peaksdb679['T'].sum(),
        'V': peaksdb679['V'].sum(),
        'W': peaksdb679['W'].sum(),
        'Y': peaksdb679['Y'].sum(),
        'c-carb': peaksdb679['c-carb'].sum(),
        'm-oxid': peaksdb679['m-oxid'].sum(),
        'n-deam': peaksdb679['n-deam'].sum(),
        'q-deam': peaksdb679['q-deam'].sum(),
        'Total area': peaksdb679['Area'].sum(),
        'Total length': peaksdb679['stripped_length'].sum()
       }

totalpeaksdb679 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                              'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                              'c-carb', 'm-oxid', 
                                              'n-deam', 'q-deam', 'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaksdb679['% C w/ carb'] = totalpeaksdb679['c-carb'] / totalpeaksdb679['C'] 

# calculate percentage of M's that are oxidized
totalpeaksdb679['% M w/ oxid'] = totalpeaksdb679['m-oxid'] / totalpeaksdb679['M'] 

# calculate percentage of N's that are deamidated
totalpeaksdb679['% N w/ deam'] = totalpeaksdb679['n-deam'] / totalpeaksdb679['N'] 

# calculate percentage of N's that are deamidated
totalpeaksdb679['% Q w/ deam'] = totalpeaksdb679['q-deam'] / totalpeaksdb679['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaksdb679['NAAF denom.'] = totalpeaksdb679['Total area'] / totalpeaksdb679['Total length']

# write modified dataframe to new txt file
totalpeaksdb679.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/679_SMCP_50_GF75_PDB/679_SMCP_50_GF75_PDB_totals.csv")

totalpeaksdb679.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,42,9,13,42,14,27,21,36,36,61,...,0,2,4,36112010.0,507,1.0,0.0,0.071429,0.2,71226.844181

In [12]:
# use the calculated NAAF factor (in totalpeaksdb679 dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

NAAF20 = 71226.844181

# we'll use -10lgP > 20 as an approximate cutoff for the <1.0% FDR which is what we actually have
peaksdb679['NAAF factor'] = (peaksdb679['NAAF_num.'])/NAAF20

# make a dataframe that contains only what we need: sequences, AAs, PTMs
peaksdb679_NAAF = peaksdb679[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', \
                              'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                              'c-carb', 'm-oxid', 'n-deam', 'q-deam']].copy()

# multiply the NAAF20 factor SMCP the AAs to normalize its abundance SMCP peak area and peptide length

peaksdb679_NAAF['A-NAAF20'] = peaksdb679_NAAF['A'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['C-NAAF20'] = peaksdb679_NAAF['C'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['D-NAAF20'] = peaksdb679_NAAF['D'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['E-NAAF20'] = peaksdb679_NAAF['E'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['F-NAAF20'] = peaksdb679_NAAF['F'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['G-NAAF20'] = peaksdb679_NAAF['G'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['H-NAAF20'] = peaksdb679_NAAF['H'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['I-NAAF20'] = peaksdb679_NAAF['I'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['K-NAAF20'] = peaksdb679_NAAF['K'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['L-NAAF20'] = peaksdb679_NAAF['L'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['M-NAAF20'] = peaksdb679_NAAF['M'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['N-NAAF20'] = peaksdb679_NAAF['N'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['P-NAAF20'] = peaksdb679_NAAF['P'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['Q-NAAF20'] = peaksdb679_NAAF['Q'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['R-NAAF20'] = peaksdb679_NAAF['R'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['S-NAAF20'] = peaksdb679_NAAF['S'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['T-NAAF20'] = peaksdb679_NAAF['T'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['V-NAAF20'] = peaksdb679_NAAF['V'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['W-NAAF20'] = peaksdb679_NAAF['W'] * peaksdb679['NAAF factor']
peaksdb679_NAAF['Y-NAAF20'] = peaksdb679_NAAF['Y'] * peaksdb679['NAAF factor']

# multiply the NAAF20 factor SMCP the PTMs normalize its abundance SMCP peak area and peptide length

peaksdb679_NAAF['ccarb-NAAF20'] = peaksdb679_NAAF['c-carb'] * peaksdb679_NAAF['NAAF factor']
peaksdb679_NAAF['moxid-NAAF20'] = peaksdb679_NAAF['m-oxid'] * peaksdb679_NAAF['NAAF factor']
peaksdb679_NAAF['ndeam-NAAF20'] = peaksdb679_NAAF['n-deam'] * peaksdb679_NAAF['NAAF factor']
peaksdb679_NAAF['qdeam-NAAF20'] = peaksdb679_NAAF['q-deam'] * peaksdb679_NAAF['NAAF factor']


# write the dataframe to a new csv
peaksdb679_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/679_SMCP_50_GF75_PDB/679_SMCP_50_GF75_PDB_naaf.csv")

peaksdb679_NAAF.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,I,...,R-NAAF20,S-NAAF20,T-NAAF20,V-NAAF20,W-NAAF20,Y-NAAF20,ccarb-NAAF20,moxid-NAAF20,ndeam-NAAF20,qdeam-NAAF20
0,VLEGNEQFINAAK,0.070522,2,0,0,2,1,1,0,1,...,0.000000,0.000000,0.000000,0.070522,0.0,0.000000,0.000000,0.0,0.000000,0.0
1,LSSPATLNSR,9.350407,1,0,0,0,0,0,0,0,...,9.350407,28.051222,9.350407,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0
2,YYTLEEIQK,0.050699,0,0,0,2,0,0,0,1,...,0.000000,0.000000,0.050699,0.000000,0.0,0.101397,0.000000,0.0,0.000000,0.0
3,LSSPATLNSR,0.120881,1,0,0,0,0,0,0,0,...,0.120881,0.362644,0.120881,0.000000,0.0,0.000000,0.000000,0.0,0.120881,0.0
4,STSSFSCLSR,0.037065,0,1,0,0,1,0,0,0,...,0.037065,0.185323,0.037065,0.000000,0.0,0.000000,0.037065,0.0,0.000000,0.0

In [13]:
# made a new dataframe that contains the sums of NAAF normalized AAs for peaksdb679 peaksdb results
# also contains the sums of the NAAF-corrected PTMs occurances for each affected residue

index = ['sample total']

data = {'NAAF': peaksdb679_NAAF['NAAF factor'].sum(),
        'A': peaksdb679_NAAF['A-NAAF20'].sum(),
        'C': peaksdb679_NAAF['C-NAAF20'].sum(),
        'D': peaksdb679_NAAF['D-NAAF20'].sum(),
        'E': peaksdb679_NAAF['E-NAAF20'].sum(),
        'F': peaksdb679_NAAF['F-NAAF20'].sum(),
        'G': peaksdb679_NAAF['G-NAAF20'].sum(),
        'H': peaksdb679_NAAF['H-NAAF20'].sum(),
        'I': peaksdb679_NAAF['I-NAAF20'].sum(),
        'K': peaksdb679_NAAF['K-NAAF20'].sum(),
        'L': peaksdb679_NAAF['L-NAAF20'].sum(),
        'M': peaksdb679_NAAF['M-NAAF20'].sum(),
        'N': peaksdb679_NAAF['N-NAAF20'].sum(),
        'P': peaksdb679_NAAF['P-NAAF20'].sum(),
        'Q': peaksdb679_NAAF['Q-NAAF20'].sum(),
        'R': peaksdb679_NAAF['R-NAAF20'].sum(),
        'S': peaksdb679_NAAF['S-NAAF20'].sum(),
        'T': peaksdb679_NAAF['T-NAAF20'].sum(),
        'V': peaksdb679_NAAF['V-NAAF20'].sum(),
        'W': peaksdb679_NAAF['W-NAAF20'].sum(),
        'Y': peaksdb679_NAAF['Y-NAAF20'].sum(),
        'c-carb': peaksdb679_NAAF['ccarb-NAAF20'].sum(),
        'm-oxid': peaksdb679_NAAF['moxid-NAAF20'].sum(),
        'n-deam': peaksdb679_NAAF['ndeam-NAAF20'].sum(),
        'q-deam': peaksdb679_NAAF['qdeam-NAAF20'].sum()
       }

totalpeaksdb679_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', \
                                                   'G', 'H', 'I','K', 'L', 'M', \
                                                   'N', 'P', 'Q', 'R', 'S', \
                                                   'T', 'V', 'W', 'Y', 'c-carb', \
                                                   'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate the NAAF-corrected % modified C, M, N, Q, K, and Rs


# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaksdb679_NAAF['% C w/ carb.'] = totalpeaksdb679_NAAF['c-carb'] / totalpeaksdb679_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaksdb679_NAAF['% M w/ oxid'] = totalpeaksdb679_NAAF['m-oxid'] / totalpeaksdb679_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb679_NAAF['% N w/ deam'] = totalpeaksdb679_NAAF['n-deam'] / totalpeaksdb679_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb679_NAAF['% Q w/ deam'] = totalpeaksdb679_NAAF['q-deam'] / totalpeaksdb679_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaksdb679_NAAF['NAAF check'] = totalpeaksdb679_NAAF['NAAF'] / 71226.844181

# write modified dataframe to new txt file, same name + totals
totalpeaksdb679_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/679_SMCP_50_GF75_PDB/679_SMCP_50_GF75_PDB_naaf_totals.csv")

totalpeaksdb679_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,62.262488,50.48503,0.655932,1.25773,13.909864,2.622531,2.453641,15.006021,24.434122,23.682478,...,0.416307,0.655932,0.0,0.133296,4.203427,1.0,0.0,0.011467,0.472149,0.000874