### Manipulation of PeaskDB de novo-assisted database search results of Trocas 8 (low water, November 2019) non incubation samples LC-MS/MS data using python.

Starting with:

    PeaksDB search results (.csv) of PTM-optimized database searches
    These were all searched with 15 ppm precursor tolerance and 0.5 ppm fragement ion tolerance
    Exported at <1.0% FDR
    
Goal:

    Files with stripped (no PTMs) peptide lists and
    Columns with #'s of each modification in every sequence
    Column with stripped peptide lengths (# amino acids)
    
### To use for a different file:

#### 1. Change the input file name in *IN 4*
#### 2. Use 'find + replace' (Esc + F) to replace the TROCAS # (e.g., 675) for another
#### 3. Update the NAAF factor calculated in *IN 6* into *IN 7*

In [1]:
cd /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/682_Trocas8_June2021_PEAKS_141/

/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/682_Trocas8_June2021_PEAKS_141

In [2]:
# LIBRARIES
#import pandas library for working with tabular data
import os
os.getcwd()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kde
#import regular expresson (regex)
import re
#check pandas version
pd.__version__

'1.0.5'

In [3]:
ls

 682_Trocas8_June2021_PEAKS_141_peptide.csv     'de novo only peptides.csv'
 682_Trocas8_June2021_PEAKS_141_proteins.csv     peptides_1_1_0.mzid
 682_Trocas8_June2021_PEAKS_141_proteins.fasta   protein-peptides.csv
'DB search psm.csv'

In [4]:
# read the CSV into a dataframe using the pandas read_csv function
peaksdbdup682 = pd.read_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/T8-June2021-UWPR-DN50_10lgP15/682_Trocas8_June2021_PEAKS_141/682_Trocas8_June2021_PEAKS_141_peptide.csv")

# remove redundant rows
peaksdb682 = pd.DataFrame.drop_duplicates(peaksdbdup682)

print(peaksdb682.columns)

columns = ['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area', 'Fraction', 'Scan', 'Source_File',
       '#Spec', '#Spec', 'Accession', 'PTM',
       'AScore']

peaksdb682.columns = columns

#remmove # spec and accession columns because they mess parsing up

del peaksdb682['#Spec']
del peaksdb682['Accession']
del peaksdb682['PTM']
del peaksdb682['AScore']

mean_length = peaksdb682['Length'].mean()
print(mean_length)

print("# redundant peaksdb peptides in combined dataframe", len(peaksdbdup682))
print("# nonredundant peaksdb peptides in combined dataframe", len(peaksdb682))

#look at the dataframe
peaksdb682.head()

Index(['Peptide', '-10lgP', 'Mass', 'Length', 'ppm', 'm/z', 'RT',
       'Area Sample 8', 'Fraction', 'Scan', 'Source File', '#Spec',
       '#Spec Sample 8', 'Accession', 'PTM', 'AScore'],
      dtype='object')
10.270833333333334
# redundant peaksdb peptides in combined dataframe 48
# nonredundant peaksdb peptides in combined dataframe 48

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,Source_File
0,LSSPATLNSR,48.28,1044.5564,10,-1.0,523.2850,44.70,5110000.0,8,8058,20210624_Trocas8_682_NMCP82_surface_DDA_120min...
1,LATVISPR,35.72,855.5178,8,0.1,428.7662,59.14,6200000.0,8,10575,20210624_Trocas8_682_NMCP82_surface_DDA_120min...
2,LATVLSPR,35.72,855.5178,8,0.1,428.7662,59.14,6200000.0,8,10575,20210624_Trocas8_682_NMCP82_surface_DDA_120min...
3,YLYEIAR,33.70,926.4861,7,-0.6,464.2501,69.21,17700.0,8,12178,20210624_Trocas8_682_NMCP82_surface_DDA_120min...
4,YLYELAR,33.70,926.4861,7,-0.6,464.2501,69.21,17700.0,8,12178,20210624_Trocas8_682_NMCP82_surface_DDA_120min...

In [6]:
# use a count function to enumerate the # of A's (alanines) in each peptide
peaksdb682['A'] = peaksdb682['Peptide'].str.count("A")

# use a count function to enumerate the # of C's (cysteines) in each peptide
peaksdb682['C'] = peaksdb682['Peptide'].str.count("C")

# use a count function to enumerate the # of D's (aspartic acids) in each peptide
peaksdb682['D'] = peaksdb682['Peptide'].str.count("D")

# use a count function to enumerate the # of E's (glutamic acids) in each peptide
peaksdb682['E'] = peaksdb682['Peptide'].str.count("E")

# use a count function to enumerate the # of F's (phenylalanines) in each peptide
peaksdb682['F'] = peaksdb682['Peptide'].str.count("F")

# use a count function to enumerate the # of G's (glycines) in each peptide
peaksdb682['G'] = peaksdb682['Peptide'].str.count("G")

# use a count function to enumerate the # of H's (histidines) in each peptide
peaksdb682['H'] = peaksdb682['Peptide'].str.count("H")

# use a count function to enumerate the # of I's (isoleucines) in each peptide
# in peaksdb682 output, there will be no isoleucines (they're lumped in with leucines)
peaksdb682['I'] = peaksdb682['Peptide'].str.count("I")

# use a count function to enumerate the # of K's (lysines) in each peptide
peaksdb682['K'] = peaksdb682['Peptide'].str.count("K")

# use a count function to enumerate the # of L's (leucines) in each peptide
# also these include the isoleucines
peaksdb682['L'] = peaksdb682['Peptide'].str.count("L")

# use a count function to enumerate the # of M's (methionines) in each peptide
peaksdb682['M'] = peaksdb682['Peptide'].str.count("M")

# use a count function to enumerate the # of N's (asparagines) in each peptide
peaksdb682['N'] = peaksdb682['Peptide'].str.count("N")

# use a count function to enumerate the # of P's ([prolines]) in each peptide
peaksdb682['P'] = peaksdb682['Peptide'].str.count("P")

# use a count function to enumerate the # of Q's (glutamines) in each peptide
peaksdb682['Q'] = peaksdb682['Peptide'].str.count("Q")

# use a count function to enumerate the # of R's (arginines) in each peptide
peaksdb682['R'] = peaksdb682['Peptide'].str.count("R")

# use a count function to enumerate the # of S's (serines) in each peptide
peaksdb682['S'] = peaksdb682['Peptide'].str.count("S")

# use a count function to enumerate the # of T's (threonines) in each peptide
peaksdb682['T'] = peaksdb682['Peptide'].str.count("T")

# use a count function to enumerate the # of V's (valines) in each peptide
peaksdb682['V'] = peaksdb682['Peptide'].str.count("V")

# use a count function to enumerate the # of W's (tryptophans) in each peptide
peaksdb682['W'] = peaksdb682['Peptide'].str.count("W")

# use a count function to enumerate the # of Y's (tyrosines) in each peptide
peaksdb682['Y'] = peaksdb682['Peptide'].str.count("Y")

# use a count function to enumerate the # of carbamidomethylated C's in each peptide
peaksdb682['c-carb'] = peaksdb682['Peptide'].str.count("57.02")

# use a count function to enumerate the # of oxidized M's in each peptide
peaksdb682['m-oxid'] = peaksdb682['Peptide'].apply(lambda x: x.count('M(+15.99)'))

# use a lamba function to enumerate the # of deamidated N's in each peptide
peaksdb682['n-deam'] = peaksdb682['Peptide'].apply(lambda x: x.count('N(+.98)'))

# use a lamba function to enumerate the # of deamidated Q's in each peptide
peaksdb682['q-deam'] = peaksdb682['Peptide'].apply(lambda x: x.count('Q(+.98)'))

# create a column with 'stripped' peptide sequences using strip
peaksdb682['stripped_peptide'] = peaksdb682['Peptide'].str.replace(r"\(.*\)","")

# add a column with the stripped peptide length (number of AAs)
peaksdb682['stripped_length'] = peaksdb682['stripped_peptide'].apply(len)

peaksdb682['NAAF_num.'] = peaksdb682['Area'] / peaksdb682['stripped_length']

# total the number of modifications in sequence
peaksdb682['ptm-total'] = peaksdb682['c-carb'] + peaksdb682['m-oxid'] + peaksdb682['n-deam'] + peaksdb682['q-deam']

# turn all isoleucines into leucines
# this helps later in comparing Unipept peptides to PeaksDB and Comet ones
peaksdb682['stripped_IL']= peaksdb682['stripped_peptide'].str.replace('I','L')

# write modified dataframe to new txt file
peaksdb682.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/682_NMCP_surf_GF75_PDB/682_NMCP_surf_GF75_PDB.csv")

# check out the results
peaksdb682.head()

,Peptide,-10lgP,Mass,Length,ppm,m/z,RT,Area,Fraction,Scan,...,Y,c-carb,m-oxid,n-deam,q-deam,stripped_peptide,stripped_length,NAAF_num.,ptm-total,stripped_IL
0,LSSPATLNSR,48.28,1044.5564,10,-1.0,523.2850,44.70,5110000.0,8,8058,...,0,0,0,0,0,LSSPATLNSR,10,511000.000000,0,LSSPATLNSR
1,LATVISPR,35.72,855.5178,8,0.1,428.7662,59.14,6200000.0,8,10575,...,0,0,0,0,0,LATVISPR,8,775000.000000,0,LATVLSPR
2,LATVLSPR,35.72,855.5178,8,0.1,428.7662,59.14,6200000.0,8,10575,...,0,0,0,0,0,LATVLSPR,8,775000.000000,0,LATVLSPR
3,YLYEIAR,33.70,926.4861,7,-0.6,464.2501,69.21,17700.0,8,12178,...,2,0,0,0,0,YLYEIAR,7,2528.571429,0,YLYELAR
4,YLYELAR,33.70,926.4861,7,-0.6,464.2501,69.21,17700.0,8,12178,...,2,0,0,0,0,YLYELAR,7,2528.571429,0,YLYELAR

In [7]:
# keep only stripped peptide I/L and NAAF
db_682 = peaksdb682[['stripped_IL', 'Area', 'NAAF_num.']]

db_682.set_index('stripped_IL')

# write modified dataframe to new txt file
db_682.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/I-L_NAAFs/682_NMCP_surf_GF75_PDB_ILnaafs.csv")

db_682.head()

  stripped_IL       Area      NAAF_num.
0  LSSPATLNSR  5110000.0  511000.000000
1    LATVLSPR  6200000.0  775000.000000
2    LATVLSPR  6200000.0  775000.000000
3     YLYELAR    17700.0    2528.571429
4     YLYELAR    17700.0    2528.571429

### Exporting txt files of stripped peptides at confidence cutoffs:

In [8]:
# keep only peptide column peptides <1% FDR (this is what we exported)
pep682moddup = peaksdb682[["Peptide"]]

# keep only the stripped peptide column <1% FDR
# this is what we'll use for UniPept input, etc
pep682dup = peaksdb682[["stripped_peptide"]]

# deduplicate both of these lists
pep682mod = pep682moddup.drop_duplicates()
pep682 = pep682dup.drop_duplicates()

# print out the #s of modified and stripped peptides, deduplicated and not

print("Total modified PeaksDB peptides in 682:", len(pep682moddup))
print("Deduplicated modified PeaksDB peptides in 682:", len(pep682mod))
print("Total stripped PeaksDB peptides in 682:", len(pep682dup))
print("Deduplicated stripped PeaksDB peptides in 682:", len(pep682))

# write altered dataframe to new txt file
# used header and index parameters to get rid of 'Peptide' header and the indexing
pep682.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/682_NMCP_surf_GF75_PDB/682_NMCP_surf_GF75_PDB_stripped_peptides.txt", header=False, index=False)

# made the text file into a FASTA 
!awk '{print ">"NR"\n"$0}' /home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/682_NMCP_surf_GF75_PDB/682_NMCP_surf_GF75_PDB_stripped_peptides.txt > \
/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/682_NMCP_surf_GF75_PDB/682_NMCP_surf_GF75_PDB_stripped_peptides.fas

# look at the stripped peptides
pep682.head()

Total modified PeaksDB peptides in 682: 48
Deduplicated modified PeaksDB peptides in 682: 48
Total stripped PeaksDB peptides in 682: 48
Deduplicated stripped PeaksDB peptides in 682: 48

  stripped_peptide
0       LSSPATLNSR
1         LATVISPR
2         LATVLSPR
3          YLYEIAR
4          YLYELAR

## NAAF correction and exporting files with AA and PTM totals:

In [9]:
# made a new dataframe that contains the sums of certain columns in the modified
# peptide dataframe above 

index = ['sample total']

data = {'A': peaksdb682['A'].sum(),
        'C': peaksdb682['C'].sum(),
        'D': peaksdb682['D'].sum(),
        'E': peaksdb682['E'].sum(),
        'F': peaksdb682['F'].sum(),
        'G': peaksdb682['G'].sum(),
        'H': peaksdb682['H'].sum(),
        'I': peaksdb682['I'].sum(),
        'K': peaksdb682['K'].sum(),
        'L': peaksdb682['L'].sum(),
        'M': peaksdb682['M'].sum(),
        'N': peaksdb682['N'].sum(),
        'P': peaksdb682['P'].sum(),
        'Q': peaksdb682['Q'].sum(),
        'R': peaksdb682['R'].sum(),
        'S': peaksdb682['S'].sum(),
        'T': peaksdb682['T'].sum(),
        'V': peaksdb682['V'].sum(),
        'W': peaksdb682['W'].sum(),
        'Y': peaksdb682['Y'].sum(),
        'c-carb': peaksdb682['c-carb'].sum(),
        'm-oxid': peaksdb682['m-oxid'].sum(),
        'n-deam': peaksdb682['n-deam'].sum(),
        'q-deam': peaksdb682['q-deam'].sum(),
        'Total area': peaksdb682['Area'].sum(),
        'Total length': peaksdb682['stripped_length'].sum()
       }

totalpeaksdb682 = pd.DataFrame(data, columns=['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', \
                                              'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                                              'c-carb', 'm-oxid', 
                                              'n-deam', 'q-deam', 'Total area', 'Total length'], index=index)

# calculate percentage of C's with carb (should be 1.0)
totalpeaksdb682['% C w/ carb'] = totalpeaksdb682['c-carb'] / totalpeaksdb682['C'] 

# calculate percentage of M's that are oxidized
totalpeaksdb682['% M w/ oxid'] = totalpeaksdb682['m-oxid'] / totalpeaksdb682['M'] 

# calculate percentage of N's that are deamidated
totalpeaksdb682['% N w/ deam'] = totalpeaksdb682['n-deam'] / totalpeaksdb682['N'] 

# calculate percentage of N's that are deamidated
totalpeaksdb682['% Q w/ deam'] = totalpeaksdb682['q-deam'] / totalpeaksdb682['Q'] 

# calculate NAAF denominator for all peptides in dataset i
totalpeaksdb682['NAAF denom.'] = totalpeaksdb682['Total area'] / totalpeaksdb682['Total length']

# write modified dataframe to new txt file
totalpeaksdb682.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/682_NMCP_surf_GF75_PDB/682_NMCP_surf_GF75_PDB_totals.csv")

totalpeaksdb682.head()

,A,C,D,E,F,G,H,I,K,L,...,m-oxid,n-deam,q-deam,Total area,Total length,% C w/ carb,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF denom.
sample total,44,2,6,24,11,29,11,42,28,58,...,3,1,5,61046822.98,486,1.0,0.75,0.071429,0.294118,125610.746872

In [10]:
# use the calculated NAAF factor (in totalpeaksdb682 dataframe, above) to caluclate the NAAF 
# NAAF: normalized normalized area abundance factor

NAAF20 = 125610.746872

# we'll use -10lgP > 20 as an approximate cutoff for the <1.0% FDR which is what we actually have
peaksdb682['NAAF factor'] = (peaksdb682['NAAF_num.'])/NAAF20

# make a dataframe that contains only what we need: sequences, AAs, PTMs
peaksdb682_NAAF = peaksdb682[['stripped_peptide', 'NAAF factor', 'A', 'C', 'D', 'E', 'F', 'G', 'H', \
                              'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', \
                              'c-carb', 'm-oxid', 'n-deam', 'q-deam']].copy()

# multiply the NAAF20 factor NMCP the AAs to normalize its abundance NMCP peak area and peptide length

peaksdb682_NAAF['A-NAAF20'] = peaksdb682_NAAF['A'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['C-NAAF20'] = peaksdb682_NAAF['C'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['D-NAAF20'] = peaksdb682_NAAF['D'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['E-NAAF20'] = peaksdb682_NAAF['E'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['F-NAAF20'] = peaksdb682_NAAF['F'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['G-NAAF20'] = peaksdb682_NAAF['G'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['H-NAAF20'] = peaksdb682_NAAF['H'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['I-NAAF20'] = peaksdb682_NAAF['I'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['K-NAAF20'] = peaksdb682_NAAF['K'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['L-NAAF20'] = peaksdb682_NAAF['L'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['M-NAAF20'] = peaksdb682_NAAF['M'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['N-NAAF20'] = peaksdb682_NAAF['N'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['P-NAAF20'] = peaksdb682_NAAF['P'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['Q-NAAF20'] = peaksdb682_NAAF['Q'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['R-NAAF20'] = peaksdb682_NAAF['R'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['S-NAAF20'] = peaksdb682_NAAF['S'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['T-NAAF20'] = peaksdb682_NAAF['T'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['V-NAAF20'] = peaksdb682_NAAF['V'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['W-NAAF20'] = peaksdb682_NAAF['W'] * peaksdb682['NAAF factor']
peaksdb682_NAAF['Y-NAAF20'] = peaksdb682_NAAF['Y'] * peaksdb682['NAAF factor']

# multiply the NAAF20 factor NMCP the PTMs normalize its abundance NMCP peak area and peptide length

peaksdb682_NAAF['ccarb-NAAF20'] = peaksdb682_NAAF['c-carb'] * peaksdb682_NAAF['NAAF factor']
peaksdb682_NAAF['moxid-NAAF20'] = peaksdb682_NAAF['m-oxid'] * peaksdb682_NAAF['NAAF factor']
peaksdb682_NAAF['ndeam-NAAF20'] = peaksdb682_NAAF['n-deam'] * peaksdb682_NAAF['NAAF factor']
peaksdb682_NAAF['qdeam-NAAF20'] = peaksdb682_NAAF['q-deam'] * peaksdb682_NAAF['NAAF factor']


# write the dataframe to a new csv
peaksdb682_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/682_NMCP_surf_GF75_PDB/682_NMCP_surf_GF75_PDB_naaf.csv")

peaksdb682_NAAF.head()

,stripped_peptide,NAAF factor,A,C,D,E,F,G,H,I,...,R-NAAF20,S-NAAF20,T-NAAF20,V-NAAF20,W-NAAF20,Y-NAAF20,ccarb-NAAF20,moxid-NAAF20,ndeam-NAAF20,qdeam-NAAF20
0,LSSPATLNSR,4.068123,1,0,0,0,0,0,0,0,...,4.068123,12.204370,4.068123,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0
1,LATVISPR,6.169854,1,0,0,0,0,0,0,1,...,6.169854,6.169854,6.169854,6.169854,0.0,0.00000,0.0,0.0,0.0,0.0
2,LATVLSPR,6.169854,1,0,0,0,0,0,0,0,...,6.169854,6.169854,6.169854,6.169854,0.0,0.00000,0.0,0.0,0.0,0.0
3,YLYEIAR,0.020130,1,0,0,1,0,0,0,1,...,0.020130,0.000000,0.000000,0.000000,0.0,0.04026,0.0,0.0,0.0,0.0
4,YLYELAR,0.020130,1,0,0,1,0,0,0,0,...,0.020130,0.000000,0.000000,0.000000,0.0,0.04026,0.0,0.0,0.0,0.0

In [11]:
# made a new dataframe that contains the sums of NAAF normalized AAs for peaksdb682 peaksdb results
# also contains the sums of the NAAF-corrected PTMs occurances for each affected residue

index = ['sample total']

data = {'NAAF': peaksdb682_NAAF['NAAF factor'].sum(),
        'A': peaksdb682_NAAF['A-NAAF20'].sum(),
        'C': peaksdb682_NAAF['C-NAAF20'].sum(),
        'D': peaksdb682_NAAF['D-NAAF20'].sum(),
        'E': peaksdb682_NAAF['E-NAAF20'].sum(),
        'F': peaksdb682_NAAF['F-NAAF20'].sum(),
        'G': peaksdb682_NAAF['G-NAAF20'].sum(),
        'H': peaksdb682_NAAF['H-NAAF20'].sum(),
        'I': peaksdb682_NAAF['I-NAAF20'].sum(),
        'K': peaksdb682_NAAF['K-NAAF20'].sum(),
        'L': peaksdb682_NAAF['L-NAAF20'].sum(),
        'M': peaksdb682_NAAF['M-NAAF20'].sum(),
        'N': peaksdb682_NAAF['N-NAAF20'].sum(),
        'P': peaksdb682_NAAF['P-NAAF20'].sum(),
        'Q': peaksdb682_NAAF['Q-NAAF20'].sum(),
        'R': peaksdb682_NAAF['R-NAAF20'].sum(),
        'S': peaksdb682_NAAF['S-NAAF20'].sum(),
        'T': peaksdb682_NAAF['T-NAAF20'].sum(),
        'V': peaksdb682_NAAF['V-NAAF20'].sum(),
        'W': peaksdb682_NAAF['W-NAAF20'].sum(),
        'Y': peaksdb682_NAAF['Y-NAAF20'].sum(),
        'c-carb': peaksdb682_NAAF['ccarb-NAAF20'].sum(),
        'm-oxid': peaksdb682_NAAF['moxid-NAAF20'].sum(),
        'n-deam': peaksdb682_NAAF['ndeam-NAAF20'].sum(),
        'q-deam': peaksdb682_NAAF['qdeam-NAAF20'].sum()
       }

totalpeaksdb682_NAAF = pd.DataFrame(data, columns=['NAAF', 'A', 'C', 'D', 'E', 'F', \
                                                   'G', 'H', 'I','K', 'L', 'M', \
                                                   'N', 'P', 'Q', 'R', 'S', \
                                                   'T', 'V', 'W', 'Y', 'c-carb', \
                                                   'm-oxid', 'n-deam', 'q-deam'], index=index)

# calculate the NAAF-corrected % modified C, M, N, Q, K, and Rs


# calculate NAAF-corrected percentage of C's with carb (should be 1.0)
totalpeaksdb682_NAAF['% C w/ carb.'] = totalpeaksdb682_NAAF['c-carb'] / totalpeaksdb682_NAAF['C'] 

# calculate NAAF-corrected percentage of M's that are oxidized
totalpeaksdb682_NAAF['% M w/ oxid'] = totalpeaksdb682_NAAF['m-oxid'] / totalpeaksdb682_NAAF['M'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb682_NAAF['% N w/ deam'] = totalpeaksdb682_NAAF['n-deam'] / totalpeaksdb682_NAAF['N'] 

# calculate NAAF-corrected percentage of N's that are deamidated
totalpeaksdb682_NAAF['% Q w/ deam'] = totalpeaksdb682_NAAF['q-deam'] / totalpeaksdb682_NAAF['Q'] 

# calculate NAAF summed numerator over denominator (in above cell) for all peptides in dataset i: a check
totalpeaksdb682_NAAF['NAAF check'] = totalpeaksdb682_NAAF['NAAF'] / 125610.746872

# write modified dataframe to new txt file, same name + totals
totalpeaksdb682_NAAF.to_csv("/home/millieginty/Documents/git-repos/amazon/data/Trocas8-notincs/processed/PeaksDB/682_NMCP_surf_GF75_PDB/682_NMCP_surf_GF75_PDB_naaf_totals.csv")

totalpeaksdb682_NAAF.head()

,NAAF,A,C,D,E,F,G,H,I,K,...,Y,c-carb,m-oxid,n-deam,q-deam,% C w/ carb.,% M w/ oxid,% N w/ deam,% Q w/ deam,NAAF check
sample total,59.859329,29.618262,0.028081,0.403577,0.56954,0.109955,0.885696,0.334669,26.039625,0.387943,...,0.223453,0.028081,0.017681,0.000146,0.001463,1.0,0.566433,0.000033,0.017305,0.000477